// packages/module/src/index.ts —— @proteus-vue/module 公共入口（module-plan B1：模块契约）
// 导出：defineModule（契约声明 + 编译期校验）+ validateModuleConfig（纯校验）+ 扫描/汇总（CLI module:check）
export { defineModule, validateModuleConfig } from './contract'
export type { ModuleConfig, ModuleValidationIssue, ModuleValidationResult } from './contract'
export { walkModuleConfigs, loadModuleConfig, scanModuleConfigs, formatModuleCheck } from './scan'
export type { ModuleScanEntry, ModuleScanResult } from './scan'
export { DependencyGraph, CycleError, buildModuleGraphManifest, moduleGraphToMermaid } from './graph'
export type { ModuleNode, Cycle, VersionConflict } from './graph'
export { createModuleSystem, createModuleEventBus, satisfies, parseSemver, VersionMismatchError } from './orchestrator'
export type { ModuleDefinition, ModuleInstance, ModuleSystem, ModuleEventBus, ModuleState } from './orchestrator'
export { generateRollupOptions } from './web-codegen'
export type { WebCodegenOptions } from './web-codegen'
export { SUBPACKAGE_LIMITS, scanSubPackages, evaluateSubPackageSizes } from './size'
export type { SubPackageStat } from './size'
export { readSubPackageRoots, scanDuplicateModules } from './duplicates'
export type { DuplicateEntry } from './duplicates'
export { auditModule } from './audit'
export type { ModuleAuditResult } from './audit'
