// AUTO-GENERATED by hosts/shared/bridge/gen-app-screen-content.mjs —— 勿手改
// ★★★App 三端对齐 · 阶段 1b（B5）：**SFC 产物 → 屏内容**（编译器 buildLayoutTemplate + 转换器
//   screenContentFromLayoutTemplate）。内容确定（无时间戳）；两端宿主共用同一 bundle 入口。
//   屏名 → ScreenContent（来自真实 SFC 模板，inline style；CSS class 展开属缺口 C1）
/* eslint-disable */
import type { ScreenContent } from '../../../packages/render-backend/src/screen-executor'
export const APP_SCREEN_CONTENT: Record<string, ScreenContent> = {
  "index": {
    "viewport": {
      "width": 390,
      "height": 844
    },
    "nodes": [
      {
        "id": 0,
        "parentId": null,
        "widthRatio": 1,
        "flexDirection": "column",
        "padding": {
          "top": 24,
          "left": 16,
          "right": 16
        },
        "semantic": "view"
      },
      {
        "id": 1,
        "parentId": 0,
        "height": 56,
        "flexDirection": "row",
        "alignItems": "center",
        "backgroundColor": "#5B5BD6",
        "borderRadius": 12,
        "padding": {
          "left": 16
        },
        "semantic": "view"
      },
      {
        "id": 2,
        "parentId": 1,
        "color": "#FFFFFF",
        "fontSize": 20,
        "text": "index 页",
        "semantic": "text"
      },
      {
        "id": 3,
        "parentId": 0,
        "height": 120,
        "margin": {
          "top": 12
        },
        "backgroundColor": "#FFFFFF",
        "borderRadius": 12,
        "semantic": "view"
      },
      {
        "id": 4,
        "parentId": 0,
        "height": 72,
        "margin": {
          "top": 12
        },
        "backgroundColor": "#F2F3F6",
        "borderRadius": 12,
        "semantic": "view"
      }
    ]
  },
  "messages": {
    "viewport": {
      "width": 390,
      "height": 844
    },
    "nodes": [
      {
        "id": 0,
        "parentId": null,
        "widthRatio": 1,
        "flexDirection": "column",
        "padding": {
          "top": 24,
          "left": 16,
          "right": 16
        },
        "semantic": "view"
      },
      {
        "id": 1,
        "parentId": 0,
        "height": 56,
        "flexDirection": "row",
        "alignItems": "center",
        "backgroundColor": "#5B5BD6",
        "borderRadius": 12,
        "padding": {
          "left": 16
        },
        "semantic": "view"
      },
      {
        "id": 2,
        "parentId": 1,
        "color": "#FFFFFF",
        "fontSize": 20,
        "text": "messages 页",
        "semantic": "text"
      },
      {
        "id": 3,
        "parentId": 0,
        "height": 120,
        "margin": {
          "top": 12
        },
        "backgroundColor": "#FFFFFF",
        "borderRadius": 12,
        "semantic": "view"
      },
      {
        "id": 4,
        "parentId": 0,
        "height": 72,
        "margin": {
          "top": 12
        },
        "backgroundColor": "#F2F3F6",
        "borderRadius": 12,
        "semantic": "view"
      }
    ]
  },
  "mine": {
    "viewport": {
      "width": 390,
      "height": 844
    },
    "nodes": [
      {
        "id": 0,
        "parentId": null,
        "widthRatio": 1,
        "flexDirection": "column",
        "padding": {
          "top": 24,
          "left": 16,
          "right": 16
        },
        "semantic": "view"
      },
      {
        "id": 1,
        "parentId": 0,
        "height": 56,
        "flexDirection": "row",
        "alignItems": "center",
        "backgroundColor": "#5B5BD6",
        "borderRadius": 12,
        "padding": {
          "left": 16
        },
        "semantic": "view"
      },
      {
        "id": 2,
        "parentId": 1,
        "color": "#FFFFFF",
        "fontSize": 20,
        "text": "mine 页",
        "semantic": "text"
      },
      {
        "id": 3,
        "parentId": 0,
        "height": 120,
        "margin": {
          "top": 12
        },
        "backgroundColor": "#FFFFFF",
        "borderRadius": 12,
        "semantic": "view"
      },
      {
        "id": 4,
        "parentId": 0,
        "height": 72,
        "margin": {
          "top": 12
        },
        "backgroundColor": "#F2F3F6",
        "borderRadius": 12,
        "semantic": "view"
      }
    ]
  },
  "home": {
    "viewport": {
      "width": 390,
      "height": 844
    },
    "nodes": [
      {
        "id": 0,
        "parentId": null,
        "widthRatio": 1,
        "flexDirection": "column",
        "padding": {
          "top": 24,
          "left": 16,
          "right": 16
        },
        "semantic": "view"
      },
      {
        "id": 1,
        "parentId": 0,
        "height": 56,
        "flexDirection": "row",
        "alignItems": "center",
        "backgroundColor": "#5B5BD6",
        "borderRadius": 12,
        "padding": {
          "left": 16
        },
        "semantic": "view"
      },
      {
        "id": 2,
        "parentId": 1,
        "color": "#FFFFFF",
        "fontSize": 20,
        "text": "home 页",
        "semantic": "text"
      },
      {
        "id": 3,
        "parentId": 0,
        "height": 120,
        "margin": {
          "top": 12
        },
        "backgroundColor": "#FFFFFF",
        "borderRadius": 12,
        "semantic": "view"
      },
      {
        "id": 4,
        "parentId": 0,
        "height": 72,
        "margin": {
          "top": 12
        },
        "backgroundColor": "#F2F3F6",
        "borderRadius": 12,
        "semantic": "view"
      }
    ]
  },
  "detail": {
    "viewport": {
      "width": 390,
      "height": 844
    },
    "nodes": [
      {
        "id": 0,
        "parentId": null,
        "widthRatio": 1,
        "flexDirection": "column",
        "padding": {
          "top": 24,
          "left": 16,
          "right": 16
        },
        "semantic": "view"
      },
      {
        "id": 1,
        "parentId": 0,
        "height": 56,
        "flexDirection": "row",
        "alignItems": "center",
        "backgroundColor": "#5B5BD6",
        "borderRadius": 12,
        "padding": {
          "left": 16
        },
        "semantic": "view"
      },
      {
        "id": 2,
        "parentId": 1,
        "color": "#FFFFFF",
        "fontSize": 20,
        "text": "detail 页",
        "semantic": "text"
      },
      {
        "id": 3,
        "parentId": 0,
        "height": 120,
        "margin": {
          "top": 12
        },
        "backgroundColor": "#FFFFFF",
        "borderRadius": 12,
        "semantic": "view"
      },
      {
        "id": 4,
        "parentId": 0,
        "height": 72,
        "margin": {
          "top": 12
        },
        "backgroundColor": "#F2F3F6",
        "borderRadius": 12,
        "semantic": "view"
      }
    ]
  },
  "third": {
    "viewport": {
      "width": 390,
      "height": 844
    },
    "nodes": [
      {
        "id": 0,
        "parentId": null,
        "widthRatio": 1,
        "flexDirection": "column",
        "padding": {
          "top": 24,
          "left": 16,
          "right": 16
        },
        "semantic": "view"
      },
      {
        "id": 1,
        "parentId": 0,
        "height": 56,
        "flexDirection": "row",
        "alignItems": "center",
        "backgroundColor": "#5B5BD6",
        "borderRadius": 12,
        "padding": {
          "left": 16
        },
        "semantic": "view"
      },
      {
        "id": 2,
        "parentId": 1,
        "color": "#FFFFFF",
        "fontSize": 20,
        "text": "third 页",
        "semantic": "text"
      },
      {
        "id": 3,
        "parentId": 0,
        "height": 120,
        "margin": {
          "top": 12
        },
        "backgroundColor": "#FFFFFF",
        "borderRadius": 12,
        "semantic": "view"
      },
      {
        "id": 4,
        "parentId": 0,
        "height": 72,
        "margin": {
          "top": 12
        },
        "backgroundColor": "#F2F3F6",
        "borderRadius": 12,
        "semantic": "view"
      }
    ]
  },
  "r-home": {
    "viewport": {
      "width": 390,
      "height": 844
    },
    "nodes": [
      {
        "id": 0,
        "parentId": null,
        "widthRatio": 1,
        "flexDirection": "column",
        "padding": {
          "top": 24,
          "left": 16,
          "right": 16
        },
        "semantic": "view"
      },
      {
        "id": 1,
        "parentId": 0,
        "height": 56,
        "flexDirection": "row",
        "alignItems": "center",
        "backgroundColor": "#5B5BD6",
        "borderRadius": 12,
        "padding": {
          "left": 16
        },
        "semantic": "view"
      },
      {
        "id": 2,
        "parentId": 1,
        "color": "#FFFFFF",
        "fontSize": 20,
        "text": "r-home 页",
        "semantic": "text"
      },
      {
        "id": 3,
        "parentId": 0,
        "height": 120,
        "margin": {
          "top": 12
        },
        "backgroundColor": "#FFFFFF",
        "borderRadius": 12,
        "semantic": "view"
      },
      {
        "id": 4,
        "parentId": 0,
        "height": 72,
        "margin": {
          "top": 12
        },
        "backgroundColor": "#F2F3F6",
        "borderRadius": 12,
        "semantic": "view"
      }
    ]
  },
  "r-detail": {
    "viewport": {
      "width": 390,
      "height": 844
    },
    "nodes": [
      {
        "id": 0,
        "parentId": null,
        "widthRatio": 1,
        "flexDirection": "column",
        "padding": {
          "top": 24,
          "left": 16,
          "right": 16
        },
        "semantic": "view"
      },
      {
        "id": 1,
        "parentId": 0,
        "height": 56,
        "flexDirection": "row",
        "alignItems": "center",
        "backgroundColor": "#5B5BD6",
        "borderRadius": 12,
        "padding": {
          "left": 16
        },
        "semantic": "view"
      },
      {
        "id": 2,
        "parentId": 1,
        "color": "#FFFFFF",
        "fontSize": 20,
        "text": "r-detail 页",
        "semantic": "text"
      },
      {
        "id": 3,
        "parentId": 0,
        "height": 120,
        "margin": {
          "top": 12
        },
        "backgroundColor": "#FFFFFF",
        "borderRadius": 12,
        "semantic": "view"
      },
      {
        "id": 4,
        "parentId": 0,
        "height": 72,
        "margin": {
          "top": 12
        },
        "backgroundColor": "#F2F3F6",
        "borderRadius": 12,
        "semantic": "view"
      }
    ]
  },
  "r-user": {
    "viewport": {
      "width": 390,
      "height": 844
    },
    "nodes": [
      {
        "id": 0,
        "parentId": null,
        "widthRatio": 1,
        "flexDirection": "column",
        "padding": {
          "top": 24,
          "left": 16,
          "right": 16
        },
        "semantic": "view"
      },
      {
        "id": 1,
        "parentId": 0,
        "height": 56,
        "flexDirection": "row",
        "alignItems": "center",
        "backgroundColor": "#5B5BD6",
        "borderRadius": 12,
        "padding": {
          "left": 16
        },
        "semantic": "view"
      },
      {
        "id": 2,
        "parentId": 1,
        "color": "#FFFFFF",
        "fontSize": 20,
        "text": "r-user 页",
        "semantic": "text"
      },
      {
        "id": 3,
        "parentId": 0,
        "height": 120,
        "margin": {
          "top": 12
        },
        "backgroundColor": "#FFFFFF",
        "borderRadius": 12,
        "semantic": "view"
      },
      {
        "id": 4,
        "parentId": 0,
        "height": 72,
        "margin": {
          "top": 12
        },
        "backgroundColor": "#F2F3F6",
        "borderRadius": 12,
        "semantic": "view"
      }
    ]
  }
}
