// src/router/auto-routes.ts
// AUTO-GENERATED by scripts/gen-routes.ts. DO NOT EDIT.
import type { RouteRecord } from './types'

export const routes: RouteRecord[] = [
  { name: "components-demo", path: "pages/components-demo", component: "../pages/components-demo.vue", parent: "index", meta: {"title":"组件演示"} },
  { name: "config-demo", path: "pages/config-demo", component: "../pages/config-demo.vue", parent: "index", meta: {"title":"配置演示"} },
  { name: "forms", path: "pages/forms", component: "../pages/forms.vue", parent: "index", meta: {"title":"表单与指令"} },
  { name: "index", path: "pages/index", component: "../pages/index.vue", meta: {"title":"首页","isTab":true} },
  { name: "mine", path: "pages/mine", component: "../pages/mine.vue", parent: "index", meta: {"title":"我的","isTab":true} },
  { name: "showcase", path: "pages/showcase", component: "../pages/showcase.vue", parent: "index", meta: {"title":"转场演示"} },
  { name: "user", path: "pages/user/index", component: "../pages/user/index.vue", meta: {"title":"用户中心"} },
  { name: "user-profile", path: "pages/user/profile", component: "../pages/user/profile.vue", parent: "user", meta: {"title":"个人资料","requiresAuth":true} },
  { name: "order-pages-list", path: "subpackages/order/pages/list", component: "../subpackages/order/pages/list.vue", subPackage: "order", meta: {"title":"订单列表"} },
]

export const tabRoutes: RouteRecord[] = routes.filter(r => r.meta?.isTab)
export const routeMap: Record<string, RouteRecord> = routes.reduce((m, r) => { m[r.name] = r; return m }, {} as Record<string, RouteRecord>)
