// showcase/data/catalog.ts —— 组件/能力目录数据（AUTO-GENERATED by scripts/gen-showcase-catalog.mjs，勿手动编辑）
// ★单一事实源：官网内容 website/content/{components,capabilities}/*.md（分组/排序/名称/描述）。
// ★route 非空 = 该条目已有详情页（目录页渲染为可点击）；空 = 规划中（诚实标注）。
// 重新生成：node scripts/gen-showcase-catalog.mjs
export interface CatalogItem {
  /** 组件名（p-button）或 Hook 名（useCamera） */
  name: string
  /** 能力原语标识（capability.camera；组件为空） */
  id?: string
  /** 一句话描述 */
  desc: string
  /** 详情页路径（'' = 规划中） */
  route: string
}

export interface CatalogGroup {
  name: string
  desc: string
  items: CatalogItem[]
}

/** 组件：6 域 / 72 个（已备详情页 2） */
export const COMPONENT_GROUPS: CatalogGroup[] = [
  {
    name: "布局",
    desc: "网格 / 弹性栈 / 分区 / 安全区 / 滚动 / 虚拟列表",
    items: [
      { name: "p-adaptive", desc: "容器形态自适应", route: "" },
      { name: "p-aspect", desc: "纵横比容器", route: "" },
      { name: "p-box", desc: "原子容器", route: "" },
      { name: "p-divider", desc: "分隔线", route: "" },
      { name: "p-fit", desc: "内在尺寸", route: "" },
      { name: "p-grid", desc: "自适应网格", route: "" },
      { name: "p-inline", desc: "行内容器", route: "" },
      { name: "p-masonry", desc: "瀑布流", route: "" },
      { name: "p-safe", desc: "安全区避让", route: "" },
      { name: "p-scroll", desc: "显式滚动容器", route: "" },
      { name: "p-scroll-view", desc: "滚动容器", route: "" },
      { name: "p-sidebar", desc: "自适应导航栏", route: "" },
      { name: "p-spacer", desc: "弹性空白", route: "" },
      { name: "p-stack", desc: "弹性栈", route: "" },
      { name: "p-view", desc: "通用容器", route: "" },
      { name: "p-virtual-list", desc: "虚拟化长列表", route: "" },
      { name: "p-zone", desc: "容器断点分区", route: "" },
    ],
  },
  {
    name: "内容与表单",
    desc: "文本 / 图标 / 图片 / 表单控件 / 按钮 / 进度 / 骨架屏",
    items: [
      { name: "p-avatar", desc: "头像", route: "" },
      { name: "p-button", desc: "按钮", route: "/subpackages/components/pages/p-button" },
      { name: "p-camera", desc: "相机", route: "" },
      { name: "p-canvas", desc: "画布", route: "" },
      { name: "p-checkbox", desc: "多选", route: "" },
      { name: "p-form", desc: "表单容器", route: "" },
      { name: "p-heading", desc: "标题", route: "" },
      { name: "p-icon", desc: "图标", route: "" },
      { name: "p-image", desc: "图片", route: "" },
      { name: "p-input", desc: "输入框", route: "/subpackages/components/pages/p-input" },
      { name: "p-label", desc: "表单标签 / 控件关联", route: "" },
      { name: "p-list-view", desc: "虚拟长列表", route: "" },
      { name: "p-loading", desc: "加载中", route: "" },
      { name: "p-map", desc: "地图", route: "" },
      { name: "p-media", desc: "媒体统一入口", route: "" },
      { name: "p-nav-bar", desc: "导航栏", route: "" },
      { name: "p-picker", desc: "原生日期/时间/城市选择", route: "" },
      { name: "p-progress", desc: "进度条", route: "" },
      { name: "p-radio", desc: "单选", route: "" },
      { name: "p-rich-text", desc: "富文本", route: "" },
      { name: "p-scale", desc: "动态字号/密度", route: "" },
      { name: "p-select", desc: "选择器 / 弹层型", route: "" },
      { name: "p-selection", desc: "局部文本选区", route: "" },
      { name: "p-skeleton", desc: "骨架屏", route: "" },
      { name: "p-slider", desc: "滑块", route: "" },
      { name: "p-svg", desc: "矢量图形", route: "" },
      { name: "p-switch", desc: "开关", route: "" },
      { name: "p-text", desc: "文本", route: "" },
      { name: "p-textarea", desc: "多行文本域", route: "" },
    ],
  },
  {
    name: "页面外壳",
    desc: "页面 / 导航栏 / 弹窗 / 抽屉 / 轻提示 / 分段 / 标签栏",
    items: [
      { name: "p-action-sheet", desc: "动作面板", route: "" },
      { name: "p-ad", desc: "广告位", route: "" },
      { name: "p-drawer", desc: "侧滑抽屉", route: "" },
      { name: "p-keyboard-accessory", desc: "键盘上方工具栏", route: "" },
      { name: "p-mask", desc: "遮罩", route: "" },
      { name: "p-modal", desc: "弹窗", route: "" },
      { name: "p-nav", desc: "导航栏", route: "" },
      { name: "p-page", desc: "页面根容器", route: "" },
      { name: "p-page-container", desc: "页面容器 / 底部弹出层", route: "" },
      { name: "p-popover", desc: "气泡浮层", route: "" },
      { name: "p-popup", desc: "弹层", route: "" },
      { name: "p-segment", desc: "分段控制器", route: "" },
      { name: "p-split", desc: "自适应分栏", route: "" },
      { name: "p-tabbar", desc: "底部标签栏", route: "" },
      { name: "p-toast", desc: "轻提示", route: "" },
      { name: "p-toolbar", desc: "工具栏溢出折叠", route: "" },
      { name: "p-webview", desc: "内嵌网页", route: "" },
    ],
  },
  {
    name: "工程",
    desc: "路由链接 / 转场 / 动画 / 错误边界",
    items: [
      { name: "p-animate", desc: "动画声明——animation CSS 语义面", route: "" },
      { name: "p-error-boundary", desc: "错误兜底", route: "" },
      { name: "p-router-link", desc: "声明式导航", route: "" },
      { name: "p-transition", desc: "过渡", route: "" },
    ],
  },
  {
    name: "手势",
    desc: "可拖拽 / 可滚动",
    items: [
      { name: "p-draggable", desc: "可拖拽元素", route: "" },
      { name: "p-scrollable", desc: "可滚动区域", route: "" },
    ],
  },
  {
    name: "能力入口",
    desc: "扫码 / 选照片 / 定位",
    items: [
      { name: "p-location", desc: "定位能力入口", route: "" },
      { name: "p-pick-photo", desc: "拍照/相册能力入口", route: "" },
      { name: "p-scan-qr", desc: "扫码能力入口", route: "" },
    ],
  },
]

/** 能力：10 域 / 81 个（已备详情页 1） */
export const CAPABILITY_GROUPS: CatalogGroup[] = [
  {
    name: "网络与通信",
    desc: "请求 / WebSocket / 上传下载 / 蓝牙 / NFC",
    items: [
      { name: "useFetch", id: "capability.fetch", desc: "通信/权限/存储", route: "" },
      { name: "useWebSocket", id: "capability.websocket", desc: "WebSocket 连接句柄", route: "" },
      { name: "useSocketTask", id: "capability.socket-task", desc: "底层 SocketTask 句柄", route: "" },
      { name: "useUpload", id: "capability.upload", desc: "上传文件", route: "" },
      { name: "useDownload", id: "capability.download", desc: "下载文件", route: "" },
      { name: "useDataChannel", id: "capability.data-channel", desc: "数据通道", route: "" },
      { name: "useBluetooth", id: "capability.bluetooth", desc: "蓝牙状态", route: "" },
      { name: "useNFC", id: "capability.nfc", desc: "NFC 状态", route: "" },
      { name: "useSocket", id: "capability.socket", desc: "底层网络 Socket", route: "" },
      { name: "useLocalService", id: "capability.local-service", desc: "局域网 mDNS", route: "" },
    ],
  },
  {
    name: "设备与系统",
    desc: "传感器 / 电池 / 网络 / 剪贴板 / 屏幕 / 亮度",
    items: [
      { name: "useSensor", id: "capability.sensor", desc: "传感器一次性读取", route: "" },
      { name: "useVibrate", id: "capability.vibrate", desc: "震动", route: "" },
      { name: "useBattery", id: "capability.battery", desc: "电量", route: "" },
      { name: "useNetwork", id: "capability.network", desc: "网络", route: "" },
      { name: "useClipboard", id: "capability.clipboard", desc: "剪贴板", route: "" },
      { name: "useScreen", id: "capability.screen", desc: "屏幕", route: "" },
      { name: "useDevice", id: "capability.device", desc: "设备", route: "" },
      { name: "useOrientation", id: "capability.orientation", desc: "屏幕方向", route: "" },
      { name: "useBrightness", id: "capability.brightness", desc: "读取当前亮度", route: "" },
      { name: "useKeyboard", id: "capability.keyboard", desc: "键盘生命周期句柄", route: "" },
      { name: "useElement", id: "capability.element-query", desc: "元素查询句柄", route: "" },
      { name: "useIntersection", id: "capability.intersection", desc: "交叉观察句柄", route: "" },
      { name: "useMediaQuery", id: "capability.media-query", desc: "媒体查询句柄", route: "" },
      { name: "useScreenCapture", id: "capability.screen-capture", desc: "录屏/截屏", route: "" },
      { name: "useCacheManager", id: "capability.cache-manager", desc: "缓存管理", route: "" },
      { name: "useAR", id: "capability.ar", desc: "AR/XR 视觉算法", route: "" },
      { name: "useBeacon", id: "capability.beacon", desc: "iBeacon", route: "" },
      { name: "useDeviceCapability", id: "capability.device-capability", desc: "设备能力探测", route: "" },
    ],
  },
  {
    name: "媒体与扫码",
    desc: "相机 / 录音 / 视频 / 图片编辑 / 二维码",
    items: [
      { name: "useCamera", id: "capability.camera", desc: "摄像头访问", route: "/subpackages/capabilities/pages/camera" },
      { name: "useMicrophone", id: "capability.microphone", desc: "麦克风访问", route: "" },
      { name: "useQRCode", id: "capability.qr-code", desc: "扫码", route: "" },
      { name: "useLive", id: "capability.live", desc: "直播房间", route: "" },
      { name: "useCanvas", id: "capability.canvas", desc: "画布控制器", route: "" },
      { name: "useVideo", id: "capability.video", desc: "视频控制器", route: "" },
      { name: "useAudio", id: "capability.audio", desc: "音频控制器", route: "" },
      { name: "useLivePusher", id: "capability.live-pusher", desc: "直播推流控制器", route: "" },
      { name: "useImageEdit", id: "capability.image-edit", desc: "图像编辑句柄", route: "" },
      { name: "useMediaProcessing", id: "capability.media-processing", desc: "媒体高级", route: "" },
    ],
  },
  {
    name: "存储与文件",
    desc: "存储 / 文件系统 / 压缩 / Cookie",
    items: [
      { name: "useStorage", id: "capability.storage", desc: "存储句柄", route: "" },
      { name: "useCookie", id: "capability.cookie", desc: "Cookie 罐", route: "" },
      { name: "useFileSystem", id: "capability.file-system", desc: "文件系统句柄", route: "" },
      { name: "useArchive", id: "capability.archive", desc: "压缩文件", route: "" },
    ],
  },
  {
    name: "应用与生命周期",
    desc: "应用与页面生命周期 / 前后台 / 嵌入",
    items: [
      { name: "useAppLifecycle", id: "capability.app-lifecycle", desc: "应用生命周期订阅句柄", route: "" },
      { name: "usePageLifecycle", id: "capability.page-lifecycle", desc: "页面生命周期订阅句柄", route: "" },
      { name: "useBackground", id: "capability.background", desc: "后台/前台切换订阅", route: "" },
      { name: "useMiniProgram", id: "capability.mini-program", desc: "跳小程序", route: "" },
      { name: "useEmbedded", id: "capability.embedded", desc: "宿主嵌入上下文", route: "" },
      { name: "useExtension", id: "capability.extension", desc: "扩展/插件", route: "" },
      { name: "usePreload", id: "capability.preload", desc: "预加载句柄", route: "" },
      { name: "useIdle", id: "capability.idle", desc: "空闲调度", route: "" },
      { name: "useWindow", id: "capability.window", desc: "窗口", route: "" },
      { name: "useNavigationGuard", id: "capability.navigation-guard", desc: "卸载拦截", route: "" },
    ],
  },
  {
    name: "位置与地图",
    desc: "定位 / 地图 / 地址",
    items: [
      { name: "useLocation", id: "capability.location", desc: "位置", route: "" },
      { name: "useMap", id: "capability.map", desc: "地图上下文句柄", route: "" },
    ],
  },
  {
    name: "通知与分享",
    desc: "分享 / 订阅消息 / 短信 / 语音",
    items: [
      { name: "useNotification", id: "capability.notification", desc: "消息订阅授权", route: "" },
      { name: "useShare", id: "capability.share", desc: "通知/分享", route: "" },
      { name: "useContact", id: "capability.contact", desc: "联系人选择", route: "" },
      { name: "useCalendar", id: "capability.calendar", desc: "添加日历事件", route: "" },
      { name: "usePhoneCall", id: "capability.phone-call", desc: "拨打电话", route: "" },
      { name: "useSMS", id: "capability.sms", desc: "发送短信", route: "" },
      { name: "useShortcut", id: "capability.shortcut", desc: "添加桌面快捷方式", route: "" },
      { name: "useAd", id: "capability.ad", desc: "广告句柄", route: "" },
      { name: "useTranslation", id: "capability.translation", desc: "翻译", route: "" },
      { name: "usePoster", id: "capability.poster", desc: "分享海报", route: "" },
    ],
  },
  {
    name: "账号与支付",
    desc: "登录 / 支付 / 生物识别 / 联系人",
    items: [
      { name: "usePermission", id: "capability.permission", desc: "权限状态", route: "" },
      { name: "useAuth", id: "capability.auth", desc: "认证状态组合", route: "" },
      { name: "useBiometric", id: "capability.biometric", desc: "生物识别支持性检测", route: "" },
      { name: "useFaceID", id: "capability.face-id", desc: "人脸识别认证", route: "" },
      { name: "usePayment", id: "capability.payment", desc: "拉起支付", route: "" },
      { name: "useLogin", id: "capability.login", desc: "登录", route: "" },
      { name: "useInAppPurchase", id: "capability.in-app-purchase", desc: "内购", route: "" },
      { name: "usePrivacy", id: "capability.privacy", desc: "隐私协议句柄", route: "" },
    ],
  },
  {
    name: "可观测与调试",
    desc: "日志 / 性能 / 埋点",
    items: [
      { name: "useAnalytics", id: "capability.analytics", desc: "埋点句柄", route: "" },
      { name: "useLog", id: "capability.log", desc: "日志句柄", route: "" },
      { name: "usePerformance", id: "capability.performance", desc: "性能句柄", route: "" },
    ],
  },
  {
    name: "其他",
    desc: "WiFi / Worker / 相册 / 更新 / 小程序",
    items: [
      { name: "useUpdate", id: "capability.update", desc: "小程序热更新管理器", route: "" },
      { name: "useAlbum", id: "capability.album", desc: "相册句柄", route: "" },
      { name: "useWorker", id: "capability.worker", desc: "多线程 Worker", route: "" },
      { name: "useAddress", id: "capability.address", desc: "收货地址", route: "" },
      { name: "useWifi", id: "capability.wifi", desc: "WiFi 句柄", route: "" },
      { name: "useWeRun", id: "capability.we-run", desc: "微信运动数据", route: "" },
    ],
  },
]

export const CATALOG_STATS = {
  componentGroups: 6,
  componentTotal: 72,
  componentReady: 2,
  capabilityGroups: 10,
  capabilityTotal: 81,
  capabilityReady: 1,
}
