// router/auto-routes.ts —— 全端统一导航产物（AUTO-GENERATED by scripts/gen-routes.ts，勿手动编辑）
// ★三份投影同源（同一棵路由树）：routes（Web/MP）· screens（App）· RouteParamsByName（类型提示）
// 来源：pages/**/*.vue（约定式页面发现）+ proteus.config.ts 的 router.pages（每页配置）
import type { RouteRecord } from '@proteus-vue/router/types'
import type { AppScreenSpec } from '@proteus-vue/router/app-stack'

// ─── ① 全端页面清单（Web/MP：createRouter(routes)）───
export const routes: RouteRecord[] = [
  { name: "border", path: "pages/border", component: "../pages/border.vue", meta: {"title":"CSS 验收 · 边框"} },
  { name: "text", path: "pages/text", component: "../pages/text.vue", meta: {"title":"CSS 验收 · 文本"} },
]

export const tabRoutes: RouteRecord[] = routes.filter(r => r.meta?.isTab)
export const routeMap: Record<string, RouteRecord> = routes.reduce((m, r) => { m[r.name] = r; return m }, {} as Record<string, RouteRecord>)

// ─── ② App 端投影（App：createAppStack({ screens }) / createAppNavigation）───
//     与 ① 同源；平台门控已应用（webOnly / platforms 不含 native 的页面已剔除）
export const screens: Record<string, AppScreenSpec> = {
  "border": {
    "name": "border",
    "path": "pages/border"
  },
  "text": {
    "name": "text",
    "path": "pages/text"
  }
}

/** 路由名数组（App 深栈/压测按它循环取屏——顺序与 routes 一致） */
export const screenNames: string[] = ["border","text"]

/** tab 根屏（meta.isTab）—— App 端 tab 语义（switchTab/reset）的合法目标 */
export const tabNames: string[] = []

// ─── ③ 类型提示：按路由名索引的参数类型表（来源：<route> 块 params 声明）───
declare module '@proteus-vue/router/types' {
  interface RouteParamsByName {
    'border': {  },
    'text': {  },
  }
}