// router/auto-routes.ts —— 全端统一导航产物（AUTO-GENERATED by scripts/gen-routes.ts，勿手动编辑）
// ★三份投影同源（同一棵路由树）：routes（Web/MP）· screens（App）· RouteParamsByName（类型提示）
// 来源：pages/**/*.vue（约定式页面发现）+ proteus.config.ts 的 router.pages（每页配置）
import type { RouteRecord } from '@proteus-vue/router/types'
import type { AppScreenSpec } from '@proteus-vue/router/app-stack'

// ─── ① 全端页面清单（Web/MP：createRouter(routes)）───
export const routes: RouteRecord[] = [
  { name: "builtin-components-demo", path: "pages/builtin-components-demo", component: "../pages/builtin-components-demo.vue", parent: "index", meta: {"title":"内置组件"} },
  { name: "components-demo", path: "pages/components-demo", component: "../pages/components-demo.vue", parent: "index", meta: {"title":"组件演示"} },
  { name: "config-demo", path: "pages/config-demo", component: "../pages/config-demo.vue", parent: "index", meta: {"title":"配置演示"} },
  { name: "consistency-stress", path: "pages/consistency-stress", component: "../pages/consistency-stress.vue", parent: "index" },
  { name: "dev-host-demo", path: "pages/dev-host-demo", component: "../pages/dev-host-demo.vue", parent: "index" },
  { name: "devtools-open-api-demo", path: "pages/devtools-open-api-demo", component: "../pages/devtools-open-api-demo.vue", parent: "index", meta: {"title":"开放 API 演示"} },
  { name: "docs-engine-demo", path: "pages/docs-engine-demo", component: "../pages/docs-engine-demo.vue", parent: "index" },
  { name: "fluid-layout-demo", path: "pages/fluid-layout-demo", component: "../pages/fluid-layout-demo.vue", parent: "index", meta: {"title":"柔性布局"} },
  { name: "fluid-system-demo", path: "pages/fluid-system-demo", component: "../pages/fluid-system-demo.vue", parent: "index", meta: {"title":"Fluid System"} },
  { name: "forms", path: "pages/forms", component: "../pages/forms.vue", parent: "index", meta: {"title":"表单与指令"} },
  { name: "glass-demo", path: "pages/glass-demo", component: "../pages/glass-demo.vue", parent: "index", meta: {"title":"液态玻璃（G-07）"} },
  { name: "gp0-root-portal", path: "pages/gp0-root-portal", component: "../pages/gp0-root-portal.vue", parent: "index" },
  { name: "gp3-global-layer-demo", path: "pages/gp3-global-layer-demo", component: "../pages/gp3-global-layer-demo.vue", parent: "index" },
  { name: "i18n-demo", path: "pages/i18n-demo", component: "../pages/i18n-demo.vue", parent: "index", meta: {"title":"国际化"} },
  { name: "index", path: "pages/index", component: "../pages/index.vue", meta: {"title":"首页","isTab":true} },
  { name: "mine", path: "pages/mine", component: "../pages/mine.vue", parent: "index", meta: {"title":"我的","isTab":true,"branch":{"keepAlive":"none"}} },
  { name: "mp-semantics-demo", path: "pages/mp-semantics-demo", component: "../pages/mp-semantics-demo.vue", parent: "index" },
  { name: "native-components-demo", path: "pages/native-components-demo", component: "../pages/native-components-demo.vue", parent: "index", meta: {"title":"原生能力组件"} },
  { name: "pinia-demo", path: "pages/pinia-demo", component: "../pages/pinia-demo.vue", parent: "index", meta: {"title":"状态管理"} },
  { name: "platform-api-demo", path: "pages/platform-api-demo", component: "../pages/platform-api-demo.vue", parent: "index", meta: {"title":"PlatformAPI 收口"} },
  { name: "provide-inject-demo", path: "pages/provide-inject-demo", component: "../pages/provide-inject-demo.vue", parent: "index", meta: {"title":"注入演示"} },
  { name: "render-backend-demo", path: "pages/render-backend-demo", component: "../pages/render-backend-demo.vue", parent: "index" },
  { name: "semantic-primitives-demo", path: "pages/semantic-primitives-demo", component: "../pages/semantic-primitives-demo.vue", parent: "index" },
  { name: "showcase", path: "pages/showcase", component: "../pages/showcase.vue", parent: "index", meta: {"title":"转场演示"} },
  { name: "svg-showcase-demo", path: "pages/svg-showcase-demo", component: "../pages/svg-showcase-demo.vue", parent: "index" },
  { name: "svg-skeleton-demo", path: "pages/svg-skeleton-demo", component: "../pages/svg-skeleton-demo.vue", parent: "index" },
  { name: "user", path: "pages/user/index", component: "../pages/user/index.vue", parent: "index", meta: {"requiresAuth":true,"transition":"slideUp","title":"用户中心"} },
  { name: "user-profile", path: "pages/user/profile", component: "../pages/user/profile.vue", parent: "user", meta: {"requiresAuth":true,"transition":"slideUp","title":"个人资料"} },
  { name: "virtual-list-demo", path: "pages/virtual-list-demo", component: "../pages/virtual-list-demo.vue", parent: "index", meta: {"title":"虚拟列表"} },
  { name: "vmodel-mp-test", path: "pages/vmodel-mp-test", component: "../pages/vmodel-mp-test.vue", parent: "index" },
  { name: "vue-compat-demo", path: "pages/vue-compat-demo", component: "../pages/vue-compat-demo.vue", parent: "index" },
  { name: "order-pages-list", path: "subpackages/order/pages/list", component: "../subpackages/order/pages/list.vue", subPackage: "order", meta: {"title":"订单列表"} },
  { name: "svg-lab-pages-gp4-loading-demo", path: "subpackages/svg-lab/pages/gp4-loading-demo", component: "../subpackages/svg-lab/pages/gp4-loading-demo.vue", subPackage: "svg-lab" },
  { name: "svg-lab-pages-gp4-toast-queue-demo", path: "subpackages/svg-lab/pages/gp4-toast-queue-demo", component: "../subpackages/svg-lab/pages/gp4-toast-queue-demo.vue", subPackage: "svg-lab" },
  { name: "svg-lab-pages-image-spike", path: "subpackages/svg-lab/pages/image-spike", component: "../subpackages/svg-lab/pages/image-spike.vue", subPackage: "svg-lab" },
  { name: "svg-lab-pages-svg-anim-probe", path: "subpackages/svg-lab/pages/svg-anim-probe", component: "../subpackages/svg-lab/pages/svg-anim-probe.vue", subPackage: "svg-lab" },
  { name: "svg-lab-pages-svg-canvas-probe", path: "subpackages/svg-lab/pages/svg-canvas-probe", component: "../subpackages/svg-lab/pages/svg-canvas-probe.vue", subPackage: "svg-lab" },
  { name: "svg-lab-pages-svg-canvas-test", path: "subpackages/svg-lab/pages/svg-canvas-test", component: "../subpackages/svg-lab/pages/svg-canvas-test.vue", subPackage: "svg-lab" },
  { name: "svg-lab-pages-svg-hit-test", path: "subpackages/svg-lab/pages/svg-hit-test", component: "../subpackages/svg-lab/pages/svg-hit-test.vue", subPackage: "svg-lab" },
  { name: "svg-lab-pages-svg-p2-spike", path: "subpackages/svg-lab/pages/svg-p2-spike", component: "../subpackages/svg-lab/pages/svg-p2-spike.vue", subPackage: "svg-lab" },
  { name: "svg-lab-pages-svg-spike", path: "subpackages/svg-lab/pages/svg-spike", component: "../subpackages/svg-lab/pages/svg-spike.vue", subPackage: "svg-lab" },
]

export const tabRoutes: RouteRecord[] = routes.filter(r => r.meta?.isTab)
export const routeMap: Record<string, RouteRecord> = routes.reduce((m, r) => { m[r.name] = r; return m }, {} as Record<string, RouteRecord>)

// ─── ② App 端投影（App：createAppStack({ screens }) / createAppNavigation）───
//     与 ① 同源；平台门控已应用（webOnly / platforms 不含 native 的页面已剔除）
export const screens: Record<string, AppScreenSpec> = {
  "builtin-components-demo": {
    "name": "builtin-components-demo",
    "path": "pages/builtin-components-demo"
  },
  "components-demo": {
    "name": "components-demo",
    "path": "pages/components-demo"
  },
  "config-demo": {
    "name": "config-demo",
    "path": "pages/config-demo"
  },
  "consistency-stress": {
    "name": "consistency-stress",
    "path": "pages/consistency-stress"
  },
  "dev-host-demo": {
    "name": "dev-host-demo",
    "path": "pages/dev-host-demo"
  },
  "devtools-open-api-demo": {
    "name": "devtools-open-api-demo",
    "path": "pages/devtools-open-api-demo"
  },
  "docs-engine-demo": {
    "name": "docs-engine-demo",
    "path": "pages/docs-engine-demo"
  },
  "fluid-layout-demo": {
    "name": "fluid-layout-demo",
    "path": "pages/fluid-layout-demo"
  },
  "fluid-system-demo": {
    "name": "fluid-system-demo",
    "path": "pages/fluid-system-demo"
  },
  "forms": {
    "name": "forms",
    "path": "pages/forms"
  },
  "glass-demo": {
    "name": "glass-demo",
    "path": "pages/glass-demo"
  },
  "gp0-root-portal": {
    "name": "gp0-root-portal",
    "path": "pages/gp0-root-portal"
  },
  "gp3-global-layer-demo": {
    "name": "gp3-global-layer-demo",
    "path": "pages/gp3-global-layer-demo"
  },
  "i18n-demo": {
    "name": "i18n-demo",
    "path": "pages/i18n-demo"
  },
  "index": {
    "name": "index",
    "path": "pages/index"
  },
  "mine": {
    "name": "mine",
    "path": "pages/mine",
    "keepAlive": "none"
  },
  "mp-semantics-demo": {
    "name": "mp-semantics-demo",
    "path": "pages/mp-semantics-demo"
  },
  "native-components-demo": {
    "name": "native-components-demo",
    "path": "pages/native-components-demo"
  },
  "pinia-demo": {
    "name": "pinia-demo",
    "path": "pages/pinia-demo"
  },
  "platform-api-demo": {
    "name": "platform-api-demo",
    "path": "pages/platform-api-demo"
  },
  "provide-inject-demo": {
    "name": "provide-inject-demo",
    "path": "pages/provide-inject-demo"
  },
  "render-backend-demo": {
    "name": "render-backend-demo",
    "path": "pages/render-backend-demo"
  },
  "semantic-primitives-demo": {
    "name": "semantic-primitives-demo",
    "path": "pages/semantic-primitives-demo"
  },
  "showcase": {
    "name": "showcase",
    "path": "pages/showcase"
  },
  "svg-showcase-demo": {
    "name": "svg-showcase-demo",
    "path": "pages/svg-showcase-demo"
  },
  "svg-skeleton-demo": {
    "name": "svg-skeleton-demo",
    "path": "pages/svg-skeleton-demo"
  },
  "user": {
    "name": "user",
    "path": "pages/user/index",
    "transition": "slideUp"
  },
  "user-profile": {
    "name": "user-profile",
    "path": "pages/user/profile",
    "transition": "slideUp"
  },
  "virtual-list-demo": {
    "name": "virtual-list-demo",
    "path": "pages/virtual-list-demo"
  },
  "vmodel-mp-test": {
    "name": "vmodel-mp-test",
    "path": "pages/vmodel-mp-test"
  },
  "vue-compat-demo": {
    "name": "vue-compat-demo",
    "path": "pages/vue-compat-demo"
  },
  "order-pages-list": {
    "name": "order-pages-list",
    "path": "subpackages/order/pages/list"
  },
  "svg-lab-pages-gp4-loading-demo": {
    "name": "svg-lab-pages-gp4-loading-demo",
    "path": "subpackages/svg-lab/pages/gp4-loading-demo"
  },
  "svg-lab-pages-gp4-toast-queue-demo": {
    "name": "svg-lab-pages-gp4-toast-queue-demo",
    "path": "subpackages/svg-lab/pages/gp4-toast-queue-demo"
  },
  "svg-lab-pages-image-spike": {
    "name": "svg-lab-pages-image-spike",
    "path": "subpackages/svg-lab/pages/image-spike"
  },
  "svg-lab-pages-svg-anim-probe": {
    "name": "svg-lab-pages-svg-anim-probe",
    "path": "subpackages/svg-lab/pages/svg-anim-probe"
  },
  "svg-lab-pages-svg-canvas-probe": {
    "name": "svg-lab-pages-svg-canvas-probe",
    "path": "subpackages/svg-lab/pages/svg-canvas-probe"
  },
  "svg-lab-pages-svg-canvas-test": {
    "name": "svg-lab-pages-svg-canvas-test",
    "path": "subpackages/svg-lab/pages/svg-canvas-test"
  },
  "svg-lab-pages-svg-hit-test": {
    "name": "svg-lab-pages-svg-hit-test",
    "path": "subpackages/svg-lab/pages/svg-hit-test"
  },
  "svg-lab-pages-svg-p2-spike": {
    "name": "svg-lab-pages-svg-p2-spike",
    "path": "subpackages/svg-lab/pages/svg-p2-spike"
  },
  "svg-lab-pages-svg-spike": {
    "name": "svg-lab-pages-svg-spike",
    "path": "subpackages/svg-lab/pages/svg-spike"
  }
}

/** 路由名数组（App 深栈/压测按它循环取屏——顺序与 routes 一致） */
export const screenNames: string[] = ["builtin-components-demo","components-demo","config-demo","consistency-stress","dev-host-demo","devtools-open-api-demo","docs-engine-demo","fluid-layout-demo","fluid-system-demo","forms","glass-demo","gp0-root-portal","gp3-global-layer-demo","i18n-demo","index","mine","mp-semantics-demo","native-components-demo","pinia-demo","platform-api-demo","provide-inject-demo","render-backend-demo","semantic-primitives-demo","showcase","svg-showcase-demo","svg-skeleton-demo","user","user-profile","virtual-list-demo","vmodel-mp-test","vue-compat-demo","order-pages-list","svg-lab-pages-gp4-loading-demo","svg-lab-pages-gp4-toast-queue-demo","svg-lab-pages-image-spike","svg-lab-pages-svg-anim-probe","svg-lab-pages-svg-canvas-probe","svg-lab-pages-svg-canvas-test","svg-lab-pages-svg-hit-test","svg-lab-pages-svg-p2-spike","svg-lab-pages-svg-spike"]

/** tab 根屏（meta.isTab）—— App 端 tab 语义（switchTab/reset）的合法目标 */
export const tabNames: string[] = ["index","mine"]

// ─── ③ 类型提示：按路由名索引的参数类型表（来源：<route> 块 params 声明）───
declare module '@proteus-vue/router/types' {
  interface RouteParamsByName {
    'builtin-components-demo': {  },
    'components-demo': {  },
    'config-demo': {  },
    'consistency-stress': {  },
    'dev-host-demo': {  },
    'devtools-open-api-demo': {  },
    'docs-engine-demo': {  },
    'fluid-layout-demo': {  },
    'fluid-system-demo': {  },
    'forms': {  },
    'glass-demo': {  },
    'gp0-root-portal': {  },
    'gp3-global-layer-demo': {  },
    'i18n-demo': {  },
    'index': {  },
    'mine': {  },
    'mp-semantics-demo': {  },
    'native-components-demo': {  },
    'pinia-demo': {  },
    'platform-api-demo': {  },
    'provide-inject-demo': {  },
    'render-backend-demo': {  },
    'semantic-primitives-demo': {  },
    'showcase': {  },
    'svg-showcase-demo': {  },
    'svg-skeleton-demo': {  },
    'user': {  },
    'user-profile': { id?: string; from?: string; kw?: string },
    'virtual-list-demo': {  },
    'vmodel-mp-test': {  },
    'vue-compat-demo': {  },
    'order-pages-list': {  },
    'svg-lab-pages-gp4-loading-demo': {  },
    'svg-lab-pages-gp4-toast-queue-demo': {  },
    'svg-lab-pages-image-spike': {  },
    'svg-lab-pages-svg-anim-probe': {  },
    'svg-lab-pages-svg-canvas-probe': {  },
    'svg-lab-pages-svg-canvas-test': {  },
    'svg-lab-pages-svg-hit-test': {  },
    'svg-lab-pages-svg-p2-spike': {  },
    'svg-lab-pages-svg-spike': {  },
  }
}