// router/auto-routes.ts —— 应用侧路由表（AUTO-GENERATED by scripts/gen-routes.ts，勿手动编辑）
// ★拆包步骤 4：auto-routes 随应用存放（工厂化后路由表由应用注入 createRouter），不再属于 @proteus/router 包
import type { RouteRecord } from '@proteus/router/types'

export const routes: RouteRecord[] = [
  { name: "builtin-components-demo", path: "pages/builtin-components-demo", component: "../pages/builtin-components-demo.vue", parent: "index", meta: {"title":"内置组件"} },
  { name: "components-demo", path: "pages/components-demo", component: "../pages/components-demo.vue", parent: "index", meta: {"title":"组件演示"} },
  { name: "config-demo", path: "pages/config-demo", component: "../pages/config-demo.vue", parent: "index", meta: {"title":"配置演示"} },
  { name: "forms", path: "pages/forms", component: "../pages/forms.vue", parent: "index", meta: {"title":"表单与指令"} },
  { name: "index", path: "pages/index", component: "../pages/index.vue", meta: {"title":"首页","isTab":true} },
  { name: "mine", path: "pages/mine", component: "../pages/mine.vue", parent: "index", meta: {"title":"我的","isTab":true} },
  { name: "pinia-demo", path: "pages/pinia-demo", component: "../pages/pinia-demo.vue", parent: "index", meta: {"title":"状态管理"} },
  { name: "provide-inject-demo", path: "pages/provide-inject-demo", component: "../pages/provide-inject-demo.vue", parent: "index", meta: {"title":"注入演示"} },
  { name: "showcase", path: "pages/showcase", component: "../pages/showcase.vue", parent: "index", meta: {"title":"转场演示"} },
  { name: "user", path: "pages/user/index", component: "../pages/user/index.vue", parent: "index", meta: {"requiresAuth":true,"transition":"slideUp","title":"用户中心"} },
  { name: "user-profile", path: "pages/user/profile", component: "../pages/user/profile.vue", parent: "user", meta: {"requiresAuth":true,"transition":"slideUp","title":"个人资料"} },
  { name: "virtual-list-demo", path: "pages/virtual-list-demo", component: "../pages/virtual-list-demo.vue", parent: "index", meta: {"title":"虚拟列表"} },
  { name: "order-pages-list", path: "subpackages/order/pages/list", component: "../subpackages/order/pages/list.vue", subPackage: "order", meta: {"title":"订单列表"} },
]

export const tabRoutes: RouteRecord[] = routes.filter(r => r.meta?.isTab)
export const routeMap: Record<string, RouteRecord> = routes.reduce((m, r) => { m[r.name] = r; return m }, {} as Record<string, RouteRecord>)

// ★ 类型提示：按路由名索引的参数类型表（来源：<route> 块 params 声明）
declare module '@proteus/router/types' {
  interface RouteParamsByName {
    'builtin-components-demo': {  },
    'components-demo': {  },
    'config-demo': {  },
    'forms': {  },
    'index': {  },
    'mine': {  },
    'pinia-demo': {  },
    'provide-inject-demo': {  },
    'showcase': {  },
    'user': {  },
    'user-profile': { id?: string; from?: string; kw?: string },
    'virtual-list-demo': {  },
    'order-pages-list': {  },
  }
}