// router/navigation.generated.ts —— App 端导航注册表（AUTO-GENERATED by scripts/gen-routes.ts，勿手动编辑）
// ★项目驱动：来源 = pages/**/*.vue + proteus.config.ts 的 router.meta（与 auto-routes 同一棵树）
// 消费：createAppStack({ screens }) / createAppNavigation({ invoke, screens })
import type { AppScreenSpec } from '@proteus-vue/router/app-stack'

export const screens: Record<string, AppScreenSpec> = {
  "builtin-components-demo": {
    "name": "builtin-components-demo",
    "path": "pages/builtin-components-demo"
  },
  "components-demo": {
    "name": "components-demo",
    "path": "pages/components-demo"
  },
  "config-demo": {
    "name": "config-demo",
    "path": "pages/config-demo"
  },
  "consistency-stress": {
    "name": "consistency-stress",
    "path": "pages/consistency-stress"
  },
  "dev-host-demo": {
    "name": "dev-host-demo",
    "path": "pages/dev-host-demo"
  },
  "devtools-open-api-demo": {
    "name": "devtools-open-api-demo",
    "path": "pages/devtools-open-api-demo"
  },
  "docs-engine-demo": {
    "name": "docs-engine-demo",
    "path": "pages/docs-engine-demo"
  },
  "fluid-layout-demo": {
    "name": "fluid-layout-demo",
    "path": "pages/fluid-layout-demo"
  },
  "fluid-system-demo": {
    "name": "fluid-system-demo",
    "path": "pages/fluid-system-demo"
  },
  "forms": {
    "name": "forms",
    "path": "pages/forms"
  },
  "glass-demo": {
    "name": "glass-demo",
    "path": "pages/glass-demo"
  },
  "i18n-demo": {
    "name": "i18n-demo",
    "path": "pages/i18n-demo"
  },
  "index": {
    "name": "index",
    "path": "pages/index"
  },
  "mine": {
    "name": "mine",
    "path": "pages/mine"
  },
  "mp-semantics-demo": {
    "name": "mp-semantics-demo",
    "path": "pages/mp-semantics-demo"
  },
  "native-components-demo": {
    "name": "native-components-demo",
    "path": "pages/native-components-demo"
  },
  "pinia-demo": {
    "name": "pinia-demo",
    "path": "pages/pinia-demo"
  },
  "platform-api-demo": {
    "name": "platform-api-demo",
    "path": "pages/platform-api-demo"
  },
  "provide-inject-demo": {
    "name": "provide-inject-demo",
    "path": "pages/provide-inject-demo"
  },
  "render-backend-demo": {
    "name": "render-backend-demo",
    "path": "pages/render-backend-demo"
  },
  "semantic-primitives-demo": {
    "name": "semantic-primitives-demo",
    "path": "pages/semantic-primitives-demo"
  },
  "showcase": {
    "name": "showcase",
    "path": "pages/showcase"
  },
  "svg-showcase-demo": {
    "name": "svg-showcase-demo",
    "path": "pages/svg-showcase-demo"
  },
  "svg-skeleton-demo": {
    "name": "svg-skeleton-demo",
    "path": "pages/svg-skeleton-demo"
  },
  "user": {
    "name": "user",
    "path": "pages/user/index",
    "transition": "slideUp"
  },
  "user-profile": {
    "name": "user-profile",
    "path": "pages/user/profile",
    "transition": "slideUp"
  },
  "virtual-list-demo": {
    "name": "virtual-list-demo",
    "path": "pages/virtual-list-demo"
  },
  "vmodel-mp-test": {
    "name": "vmodel-mp-test",
    "path": "pages/vmodel-mp-test"
  },
  "vue-compat-demo": {
    "name": "vue-compat-demo",
    "path": "pages/vue-compat-demo"
  },
  "order-pages-list": {
    "name": "order-pages-list",
    "path": "subpackages/order/pages/list"
  },
  "svg-lab-pages-image-spike": {
    "name": "svg-lab-pages-image-spike",
    "path": "subpackages/svg-lab/pages/image-spike"
  },
  "svg-lab-pages-svg-anim-probe": {
    "name": "svg-lab-pages-svg-anim-probe",
    "path": "subpackages/svg-lab/pages/svg-anim-probe"
  },
  "svg-lab-pages-svg-canvas-probe": {
    "name": "svg-lab-pages-svg-canvas-probe",
    "path": "subpackages/svg-lab/pages/svg-canvas-probe"
  },
  "svg-lab-pages-svg-canvas-test": {
    "name": "svg-lab-pages-svg-canvas-test",
    "path": "subpackages/svg-lab/pages/svg-canvas-test"
  },
  "svg-lab-pages-svg-hit-test": {
    "name": "svg-lab-pages-svg-hit-test",
    "path": "subpackages/svg-lab/pages/svg-hit-test"
  },
  "svg-lab-pages-svg-p2-spike": {
    "name": "svg-lab-pages-svg-p2-spike",
    "path": "subpackages/svg-lab/pages/svg-p2-spike"
  },
  "svg-lab-pages-svg-spike": {
    "name": "svg-lab-pages-svg-spike",
    "path": "subpackages/svg-lab/pages/svg-spike"
  }
}

/** 路由名数组（顺序与 auto-routes 一致——深栈/压测按它循环取屏） */
export const screenNames: string[] = ["builtin-components-demo","components-demo","config-demo","consistency-stress","dev-host-demo","devtools-open-api-demo","docs-engine-demo","fluid-layout-demo","fluid-system-demo","forms","glass-demo","i18n-demo","index","mine","mp-semantics-demo","native-components-demo","pinia-demo","platform-api-demo","provide-inject-demo","render-backend-demo","semantic-primitives-demo","showcase","svg-showcase-demo","svg-skeleton-demo","user","user-profile","virtual-list-demo","vmodel-mp-test","vue-compat-demo","order-pages-list","svg-lab-pages-image-spike","svg-lab-pages-svg-anim-probe","svg-lab-pages-svg-canvas-probe","svg-lab-pages-svg-canvas-test","svg-lab-pages-svg-hit-test","svg-lab-pages-svg-p2-spike","svg-lab-pages-svg-spike"]

/** tab 根屏（meta.isTab）—— App 端 tab 语义（switchTab/reset）的合法目标 */
export const tabNames: string[] = ["index","mine"]
