// ⚠️ AUTO-GENERATED by website/scripts/gen-consistency-data.mjs — DO NOT EDIT.
// SSOT：docs/generated/consistency-metrics.json · docs/generated/consistency-pixel-report.json · docs/allow-differences.json
// 重新生成：pnpm gen:consistency-data · 防漂移门禁：pnpm check:consistency-data
export const CONSISTENCY_PAGE = {
  "generatedFrom": [
    "docs/generated/consistency-metrics.json",
    "docs/generated/consistency-pixel-report.json",
    "docs/allow-differences.json"
  ],
  "m1": {
    "value": 0.6786,
    "union": {
      "covered": 28,
      "total": 28,
      "value": 1
    },
    "covered": 28,
    "total": 28,
    "byLayer": {
      "L1": {
        "covered": 28,
        "total": 28
      },
      "L2": {
        "covered": 2,
        "total": 28
      },
      "L3": {
        "covered": 27,
        "total": 28
      },
      "L2_5": {
        "covered": 1,
        "total": 1
      },
      "L2_6": {
        "covered": 6,
        "total": 6
      }
    }
  },
  "m2": {
    "value": 6,
    "items": [
      {
        "id": "A-1",
        "category": "text-metrics",
        "title": "同一文本三端宽度差异",
        "reason": "文本度量引擎不同（StaticLayout / CoreText / 浏览器各自实现），不可消除——唯一需容差带的结构性差异（标准 §2 ③）"
      },
      {
        "id": "A-2",
        "category": "runtime-behavior",
        "title": "滚动惯性衰减",
        "reason": "各端滚动实现不同，属设计使然——若强行对齐会破坏原生手感（标准 §9.3 陷阱注记）"
      },
      {
        "id": "A-3",
        "category": "runtime-behavior",
        "title": "滚动边界反馈（回弹 / 硬停）",
        "reason": "平台规范不同（iOS 回弹、Android 拉伸/硬停），属设计使然"
      },
      {
        "id": "A-4",
        "category": "animation",
        "title": "转场插值中间态",
        "reason": "中间帧由平台算（RenderThread / CoreAnimation 自主插值），跨端曲线不同——终态一致、过程不同。★标准 §14#5 要求「现在就登记」，否则会在一致性校验里变成难以归因的偶发失败"
      },
      {
        "id": "A-5",
        "category": "rasterization",
        "title": "圆角抗锯齿 / 阴影模糊",
        "reason": "系统光栅化实现不同（RenderThread / CoreAnimation / RS / 浏览器）"
      },
      {
        "id": "A-6",
        "category": "text-metrics",
        "title": "字族解析结果不同（system-ui → 平台具体字族）",
        "reason": "Web 浏览器把 `system-ui` 作为**字族标识**返回（getComputedStyle 原样回显），而微信容器（WebView/Skyline）**解析为具体平台字族**（如 `PingFang SC`）——同一份声明的不同解析深度，属平台字体栈实现差异，不可消除。"
      }
    ]
  },
  "m3": {
    "gates": [
      "check:end-support",
      "check:profile-baseline",
      "test",
      "check:consistency-metrics"
    ],
    "enforcedBy": "CI (.github/workflows/ci.yml) + pnpm verify"
  },
  "m4": {
    "value": 1,
    "injected": 17,
    "captured": 17,
    "pendingCount": 0,
    "layers": [
      {
        "layer": "L1",
        "injected": 3,
        "captured": 3,
        "operators": [
          {
            "id": "L1-overflow-scroll",
            "caught": true,
            "expected": true,
            "note": "官方只认 hidden/visible"
          },
          {
            "id": "L1-display-grid",
            "caught": true,
            "expected": true,
            "note": "官方只认 none/flex/block"
          },
          {
            "id": "L1-position-sticky",
            "caught": true,
            "expected": true,
            "note": "官方只认 relative/absolute/fixed"
          },
          {
            "id": "L1-ctrl-legal",
            "caught": false,
            "expected": false,
            "note": "对照组：合法值不应误报"
          },
          {
            "id": "L1-ctrl-escaped",
            "caught": false,
            "expected": false,
            "note": "对照组：escape hatch 应放行"
          }
        ]
      },
      {
        "layer": "L2",
        "injected": 4,
        "captured": 4,
        "operators": [
          {
            "id": "L2-margin-shift",
            "caught": true,
            "expected": true,
            "note": "间距偏移 3px（超 1px 容差）必须检出"
          },
          {
            "id": "L2-width-shift",
            "caught": true,
            "expected": true,
            "note": "尺寸偏移 2px 必须检出"
          },
          {
            "id": "L2-node-missing",
            "caught": true,
            "expected": true,
            "note": "节点缺失必须检出（结构级）"
          },
          {
            "id": "L2-depth-mismatch",
            "caught": true,
            "expected": true,
            "note": "层级错位必须检出"
          },
          {
            "id": "L2-ctrl-within-tol",
            "caught": false,
            "expected": false,
            "note": "对照组：0.5px 在容差内不应报"
          }
        ]
      },
      {
        "layer": "L3",
        "injected": 4,
        "captured": 4,
        "operators": [
          {
            "id": "L3-color-shift-1of255",
            "caught": true,
            "expected": true,
            "note": "★§7.4 反例：颜色偏移 1/255 必须检出"
          },
          {
            "id": "L3-font-fallback",
            "caught": true,
            "expected": true,
            "note": "字族回退（PingFang SC → system-ui）必须检出"
          },
          {
            "id": "L3-enum-overflow",
            "caught": true,
            "expected": true,
            "note": "枚举值差异（overflow）必须检出"
          },
          {
            "id": "L3-scalar-flexgrow",
            "caught": true,
            "expected": true,
            "note": "无单位标量（flexGrow 1→2）必须检出——不能用 px 容差吞掉"
          },
          {
            "id": "L3-ctrl-allowed-diff",
            "caught": false,
            "expected": false,
            "note": "对照组：A-6 豁免（字族解析差异）不应判失败"
          },
          {
            "id": "L3-ctrl-within-tol",
            "caught": false,
            "expected": false,
            "note": "对照组：宽度 0.5px 在容差内不应报"
          }
        ]
      },
      {
        "layer": "L2.5",
        "injected": 2,
        "captured": 2,
        "operators": [
          {
            "id": "L2.5-result-state-mismatch",
            "caught": true,
            "expected": true,
            "note": "交互结果态不一致必须检出"
          },
          {
            "id": "L2.5-dead-interaction",
            "caught": true,
            "expected": true,
            "note": "★任一端\"点了没反应\"（几何无变化）必须检出"
          },
          {
            "id": "L2.5-ctrl-consistent",
            "caught": false,
            "expected": false,
            "note": "对照组：两端交互结果一致不应报"
          }
        ]
      },
      {
        "layer": "L2.6",
        "injected": 3,
        "captured": 3,
        "operators": [
          {
            "id": "L2.6-gap-broken",
            "caught": true,
            "expected": true,
            "note": "相对间距被破坏（单节点偏移）必须检出"
          },
          {
            "id": "L2.6-structure-lost",
            "caught": true,
            "expected": true,
            "note": "结构不变量（节点缺失）必须检出"
          },
          {
            "id": "L2.6-size-changed",
            "caught": true,
            "expected": true,
            "note": "尺寸不变量必须检出"
          },
          {
            "id": "L2.6-ctrl-pure-scroll",
            "caught": false,
            "expected": false,
            "note": "★对照组：**纯滚动（整体平移）不应报**——\"禁止比绝对坐标\"的机器证明"
          }
        ]
      },
      {
        "layer": "L4",
        "injected": 1,
        "captured": 1,
        "operators": [
          {
            "id": "L4-radius-missing",
            "caught": true,
            "expected": true,
            "note": "圆角缺失（注入真实截图：四角填直角 ⇒ 430px 差异）⇒ 观测报告定位到注入区域（region 落在块边界±24px 内）；对照组自身比对 = identical。★诚实边界：verdict=noise-level（0.05% < 0.5% 全局噪声带——L4 形态是\"定位\"，判定由 L3 borderRadius 数值承担）"
          }
        ]
      }
    ]
  },
  "pixel": {
    "gate": false,
    "changedSamples": 1,
    "cleanSamples": 6,
    "knownNoiseSamples": 0,
    "pairs": [
      {
        "id": "l4:skyline-vs-web",
        "mode": "cross-runtime",
        "a": "l4.skyline.png",
        "b": "l4.web.png",
        "verdict": "noise-level",
        "diffPixels": 2643,
        "sampleCount": 679496,
        "diffRatio": 0.00389,
        "hashDistance": 0,
        "translation": {
          "dx": -1,
          "dy": 1,
          "diffPixels": 2643,
          "diffPixelsRaw": 3675,
          "max": 4
        }
      },
      {
        "id": "l4:skyline-vs-webview",
        "mode": "same-runtime",
        "a": "l4.skyline.png",
        "b": "l4.webview.png",
        "verdict": "noise-level",
        "diffPixels": 2161,
        "sampleCount": 693240,
        "diffRatio": 0.00312,
        "hashDistance": 0,
        "translation": null
      },
      {
        "id": "l4:web-vs-webview",
        "mode": "cross-runtime",
        "a": "l4.web.png",
        "b": "l4.webview.png",
        "verdict": "noise-level",
        "diffPixels": 3045,
        "sampleCount": 679496,
        "diffRatio": 0.00448,
        "hashDistance": 0,
        "translation": {
          "dx": 0,
          "dy": -2,
          "diffPixels": 3045,
          "diffPixelsRaw": 5738,
          "max": 4
        }
      }
    ]
  },
  "shots": [
    {
      "end": "skyline",
      "file": "l4.skyline.png",
      "pub": "l4-skyline.png",
      "label": "微信 Skyline"
    },
    {
      "end": "webview",
      "file": "l4.webview.png",
      "pub": "l4-webview.png",
      "label": "微信 WebView"
    },
    {
      "end": "web",
      "file": "l4.web.png",
      "pub": "l4-web.png",
      "label": "浏览器 Web"
    }
  ],
  "debt": [
    {
      "file": "examples/profile-boundary-baseline.json",
      "count": 36
    },
    {
      "file": "showcase/profile-boundary-baseline.json",
      "count": 32
    }
  ]
} as const
