// ⚠️ AUTO-GENERATED by website/scripts/gen-consistency-data.mjs — DO NOT EDIT.
// SSOT：docs/generated/consistency-metrics.json · docs/generated/consistency-pixel-report.json · docs/generated/consistency-sfc-report.json · docs/allow-differences.json
// 重新生成：pnpm gen:consistency-data · 防漂移门禁：pnpm check:consistency-data
export const CONSISTENCY_PAGE = {
  "generatedFrom": [
    "docs/generated/consistency-metrics.json",
    "docs/generated/consistency-pixel-report.json",
    "docs/generated/consistency-sfc-report.json",
    "docs/allow-differences.json"
  ],
  "m1": {
    "value": 0.6786,
    "union": {
      "covered": 28,
      "total": 28,
      "value": 1
    },
    "covered": 28,
    "total": 28,
    "byLayer": {
      "L1": {
        "covered": 28,
        "total": 28
      },
      "L2": {
        "covered": 2,
        "total": 28
      },
      "L3": {
        "covered": 27,
        "total": 28
      },
      "L2_5": {
        "covered": 1,
        "total": 1
      },
      "L2_6": {
        "covered": 6,
        "total": 6
      }
    }
  },
  "m2": {
    "value": 6,
    "items": [
      {
        "id": "A-1",
        "category": "text-metrics",
        "title": "同一文本三端宽度差异",
        "reason": "文本度量引擎不同（StaticLayout / CoreText / 浏览器各自实现），不可消除——唯一需容差带的结构性差异（标准 §2 ③）"
      },
      {
        "id": "A-2",
        "category": "runtime-behavior",
        "title": "滚动惯性衰减",
        "reason": "各端滚动实现不同，属设计使然——若强行对齐会破坏原生手感（标准 §9.3 陷阱注记）"
      },
      {
        "id": "A-3",
        "category": "runtime-behavior",
        "title": "滚动边界反馈（回弹 / 硬停）",
        "reason": "平台规范不同（iOS 回弹、Android 拉伸/硬停），属设计使然"
      },
      {
        "id": "A-4",
        "category": "animation",
        "title": "转场插值中间态",
        "reason": "中间帧由平台算（RenderThread / CoreAnimation 自主插值），跨端曲线不同——终态一致、过程不同。★标准 §14#5 要求「现在就登记」，否则会在一致性校验里变成难以归因的偶发失败"
      },
      {
        "id": "A-5",
        "category": "rasterization",
        "title": "圆角抗锯齿 / 阴影模糊",
        "reason": "系统光栅化实现不同（RenderThread / CoreAnimation / RS / 浏览器）"
      },
      {
        "id": "A-6",
        "category": "text-metrics",
        "title": "字族解析结果不同（system-ui → 平台具体字族）",
        "reason": "Web 浏览器把 `system-ui` 作为**字族标识**返回（getComputedStyle 原样回显），而微信容器（WebView/Skyline）**解析为具体平台字族**（如 `PingFang SC`）——同一份声明的不同解析深度，属平台字体栈实现差异，不可消除。"
      }
    ]
  },
  "m3": {
    "gates": [
      "check:end-support",
      "check:profile-baseline",
      "test",
      "check:consistency-metrics"
    ],
    "enforcedBy": "CI (.github/workflows/ci.yml) + pnpm verify"
  },
  "m4": {
    "value": 1,
    "injected": 17,
    "captured": 17,
    "pendingCount": 0,
    "layers": [
      {
        "layer": "L1",
        "injected": 3,
        "captured": 3,
        "operators": [
          {
            "id": "L1-overflow-scroll",
            "caught": true,
            "expected": true,
            "note": "官方只认 hidden/visible"
          },
          {
            "id": "L1-display-grid",
            "caught": true,
            "expected": true,
            "note": "官方只认 none/flex/block"
          },
          {
            "id": "L1-position-sticky",
            "caught": true,
            "expected": true,
            "note": "官方只认 relative/absolute/fixed"
          },
          {
            "id": "L1-ctrl-legal",
            "caught": false,
            "expected": false,
            "note": "对照组：合法值不应误报"
          },
          {
            "id": "L1-ctrl-escaped",
            "caught": false,
            "expected": false,
            "note": "对照组：escape hatch 应放行"
          }
        ]
      },
      {
        "layer": "L2",
        "injected": 4,
        "captured": 4,
        "operators": [
          {
            "id": "L2-margin-shift",
            "caught": true,
            "expected": true,
            "note": "间距偏移 3px（超 1px 容差）必须检出"
          },
          {
            "id": "L2-width-shift",
            "caught": true,
            "expected": true,
            "note": "尺寸偏移 2px 必须检出"
          },
          {
            "id": "L2-node-missing",
            "caught": true,
            "expected": true,
            "note": "节点缺失必须检出（结构级）"
          },
          {
            "id": "L2-depth-mismatch",
            "caught": true,
            "expected": true,
            "note": "层级错位必须检出"
          },
          {
            "id": "L2-ctrl-within-tol",
            "caught": false,
            "expected": false,
            "note": "对照组：0.5px 在容差内不应报"
          }
        ]
      },
      {
        "layer": "L3",
        "injected": 4,
        "captured": 4,
        "operators": [
          {
            "id": "L3-color-shift-1of255",
            "caught": true,
            "expected": true,
            "note": "★§7.4 反例：颜色偏移 1/255 必须检出"
          },
          {
            "id": "L3-font-fallback",
            "caught": true,
            "expected": true,
            "note": "字族回退（PingFang SC → system-ui）必须检出"
          },
          {
            "id": "L3-enum-overflow",
            "caught": true,
            "expected": true,
            "note": "枚举值差异（overflow）必须检出"
          },
          {
            "id": "L3-scalar-flexgrow",
            "caught": true,
            "expected": true,
            "note": "无单位标量（flexGrow 1→2）必须检出——不能用 px 容差吞掉"
          },
          {
            "id": "L3-ctrl-allowed-diff",
            "caught": false,
            "expected": false,
            "note": "对照组：A-6 豁免（字族解析差异）不应判失败"
          },
          {
            "id": "L3-ctrl-within-tol",
            "caught": false,
            "expected": false,
            "note": "对照组：宽度 0.5px 在容差内不应报"
          }
        ]
      },
      {
        "layer": "L2.5",
        "injected": 2,
        "captured": 2,
        "operators": [
          {
            "id": "L2.5-result-state-mismatch",
            "caught": true,
            "expected": true,
            "note": "交互结果态不一致必须检出"
          },
          {
            "id": "L2.5-dead-interaction",
            "caught": true,
            "expected": true,
            "note": "★任一端\"点了没反应\"（几何无变化）必须检出"
          },
          {
            "id": "L2.5-ctrl-consistent",
            "caught": false,
            "expected": false,
            "note": "对照组：两端交互结果一致不应报"
          }
        ]
      },
      {
        "layer": "L2.6",
        "injected": 3,
        "captured": 3,
        "operators": [
          {
            "id": "L2.6-gap-broken",
            "caught": true,
            "expected": true,
            "note": "相对间距被破坏（单节点偏移）必须检出"
          },
          {
            "id": "L2.6-structure-lost",
            "caught": true,
            "expected": true,
            "note": "结构不变量（节点缺失）必须检出"
          },
          {
            "id": "L2.6-size-changed",
            "caught": true,
            "expected": true,
            "note": "尺寸不变量必须检出"
          },
          {
            "id": "L2.6-ctrl-pure-scroll",
            "caught": false,
            "expected": false,
            "note": "★对照组：**纯滚动（整体平移）不应报**——\"禁止比绝对坐标\"的机器证明"
          }
        ]
      },
      {
        "layer": "L4",
        "injected": 1,
        "captured": 1,
        "operators": [
          {
            "id": "L4-radius-missing",
            "caught": true,
            "expected": true,
            "note": "圆角缺失（注入真实截图：四角填直角 ⇒ 537px 差异）⇒ 观测报告定位到注入区域（region 落在块边界±24px 内）；对照组自身比对 = identical。★诚实边界：verdict=noise-level（0.05% < 0.5% 全局噪声带——L4 形态是\"定位\"，判定由 L3 borderRadius 数值承担）"
          }
        ]
      }
    ]
  },
  "pixel": {
    "gate": false,
    "changedSamples": 15,
    "cleanSamples": 4,
    "knownNoiseSamples": 15,
    "pairs": [
      {
        "id": "l4:android-vs-ios-device",
        "mode": "cross-runtime",
        "a": "l4.android.png",
        "b": "l4.ios-device.png",
        "verdict": "changed",
        "diffPixels": 3768,
        "sampleCount": 337080,
        "diffRatio": 0.01118,
        "hashDistance": 0,
        "translation": null,
        "knownNoise": "N-L4-five-end-rasterization",
        "norm": {
          "outSize": {
            "w": 640,
            "h": 560
          },
          "a": {
            "srcSize": {
              "width": 1200,
              "height": 2608
            },
            "colorSpace": "display-p3",
            "block": {
              "x": 48,
              "y": 360,
              "w": 240,
              "h": 144
            },
            "scale": 0.667
          },
          "b": {
            "srcSize": {
              "width": 1170,
              "height": 2532
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 48,
              "y": 361,
              "w": 240,
              "h": 142
            },
            "scale": 0.667
          }
        }
      },
      {
        "id": "l4:android-vs-ios",
        "mode": "cross-runtime",
        "a": "l4.android.png",
        "b": "l4.ios.png",
        "verdict": "changed",
        "diffPixels": 3870,
        "sampleCount": 337080,
        "diffRatio": 0.01148,
        "hashDistance": 0,
        "translation": null,
        "knownNoise": "N-L4-five-end-rasterization",
        "norm": {
          "outSize": {
            "w": 640,
            "h": 560
          },
          "a": {
            "srcSize": {
              "width": 1200,
              "height": 2608
            },
            "colorSpace": "display-p3",
            "block": {
              "x": 48,
              "y": 360,
              "w": 240,
              "h": 144
            },
            "scale": 0.667
          },
          "b": {
            "srcSize": {
              "width": 1206,
              "height": 2622
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 48,
              "y": 361,
              "w": 240,
              "h": 142
            },
            "scale": 0.667
          }
        }
      },
      {
        "id": "l4:android-vs-skyline",
        "mode": "cross-runtime",
        "a": "l4.android.png",
        "b": "l4.skyline.png",
        "verdict": "changed",
        "diffPixels": 6509,
        "sampleCount": 337080,
        "diffRatio": 0.01931,
        "hashDistance": 0,
        "translation": null,
        "knownNoise": "N-L4-five-end-rasterization",
        "norm": {
          "outSize": {
            "w": 640,
            "h": 560
          },
          "a": {
            "srcSize": {
              "width": 1200,
              "height": 2608
            },
            "colorSpace": "display-p3",
            "block": {
              "x": 48,
              "y": 360,
              "w": 240,
              "h": 144
            },
            "scale": 0.667
          },
          "b": {
            "srcSize": {
              "width": 702,
              "height": 1520
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 29,
              "y": 217,
              "w": 143,
              "h": 86
            },
            "scale": 1.111
          }
        }
      },
      {
        "id": "l4:android-vs-web",
        "mode": "cross-runtime",
        "a": "l4.android.png",
        "b": "l4.web.png",
        "verdict": "changed",
        "diffPixels": 4840,
        "sampleCount": 337080,
        "diffRatio": 0.01436,
        "hashDistance": 0,
        "translation": null,
        "knownNoise": "N-L4-five-end-rasterization",
        "norm": {
          "outSize": {
            "w": 640,
            "h": 560
          },
          "a": {
            "srcSize": {
              "width": 1200,
              "height": 2608
            },
            "colorSpace": "display-p3",
            "block": {
              "x": 48,
              "y": 360,
              "w": 240,
              "h": 144
            },
            "scale": 0.667
          },
          "b": {
            "srcSize": {
              "width": 780,
              "height": 1688
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 32,
              "y": 240,
              "w": 160,
              "h": 96
            },
            "scale": 1
          }
        }
      },
      {
        "id": "l4:android-vs-webview",
        "mode": "cross-runtime",
        "a": "l4.android.png",
        "b": "l4.webview.png",
        "verdict": "changed",
        "diffPixels": 6191,
        "sampleCount": 337080,
        "diffRatio": 0.01837,
        "hashDistance": 0,
        "translation": null,
        "knownNoise": "N-L4-five-end-rasterization",
        "norm": {
          "outSize": {
            "w": 640,
            "h": 560
          },
          "a": {
            "srcSize": {
              "width": 1200,
              "height": 2608
            },
            "colorSpace": "display-p3",
            "block": {
              "x": 48,
              "y": 360,
              "w": 240,
              "h": 144
            },
            "scale": 0.667
          },
          "b": {
            "srcSize": {
              "width": 702,
              "height": 1520
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 29,
              "y": 217,
              "w": 143,
              "h": 86
            },
            "scale": 1.111
          }
        }
      },
      {
        "id": "l4:ios-device-vs-ios",
        "mode": "same-platform",
        "a": "l4.ios-device.png",
        "b": "l4.ios.png",
        "verdict": "noise-level",
        "diffPixels": 974,
        "sampleCount": 337080,
        "diffRatio": 0.00289,
        "hashDistance": 0,
        "translation": null,
        "knownNoise": "N-L4-five-end-rasterization",
        "norm": {
          "outSize": {
            "w": 640,
            "h": 560
          },
          "a": {
            "srcSize": {
              "width": 1170,
              "height": 2532
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 48,
              "y": 361,
              "w": 240,
              "h": 142
            },
            "scale": 0.667
          },
          "b": {
            "srcSize": {
              "width": 1206,
              "height": 2622
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 48,
              "y": 361,
              "w": 240,
              "h": 142
            },
            "scale": 0.667
          }
        }
      },
      {
        "id": "l4:ios-device-vs-skyline",
        "mode": "cross-runtime",
        "a": "l4.ios-device.png",
        "b": "l4.skyline.png",
        "verdict": "changed",
        "diffPixels": 5539,
        "sampleCount": 337080,
        "diffRatio": 0.01643,
        "hashDistance": 0,
        "translation": null,
        "knownNoise": "N-L4-five-end-rasterization",
        "norm": {
          "outSize": {
            "w": 640,
            "h": 560
          },
          "a": {
            "srcSize": {
              "width": 1170,
              "height": 2532
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 48,
              "y": 361,
              "w": 240,
              "h": 142
            },
            "scale": 0.667
          },
          "b": {
            "srcSize": {
              "width": 702,
              "height": 1520
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 29,
              "y": 217,
              "w": 143,
              "h": 86
            },
            "scale": 1.111
          }
        }
      },
      {
        "id": "l4:ios-device-vs-web",
        "mode": "cross-runtime",
        "a": "l4.ios-device.png",
        "b": "l4.web.png",
        "verdict": "changed",
        "diffPixels": 4167,
        "sampleCount": 337080,
        "diffRatio": 0.01236,
        "hashDistance": 0,
        "translation": null,
        "knownNoise": "N-L4-five-end-rasterization",
        "norm": {
          "outSize": {
            "w": 640,
            "h": 560
          },
          "a": {
            "srcSize": {
              "width": 1170,
              "height": 2532
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 48,
              "y": 361,
              "w": 240,
              "h": 142
            },
            "scale": 0.667
          },
          "b": {
            "srcSize": {
              "width": 780,
              "height": 1688
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 32,
              "y": 240,
              "w": 160,
              "h": 96
            },
            "scale": 1
          }
        }
      },
      {
        "id": "l4:ios-device-vs-webview",
        "mode": "cross-runtime",
        "a": "l4.ios-device.png",
        "b": "l4.webview.png",
        "verdict": "changed",
        "diffPixels": 5520,
        "sampleCount": 337080,
        "diffRatio": 0.01638,
        "hashDistance": 0,
        "translation": null,
        "knownNoise": "N-L4-five-end-rasterization",
        "norm": {
          "outSize": {
            "w": 640,
            "h": 560
          },
          "a": {
            "srcSize": {
              "width": 1170,
              "height": 2532
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 48,
              "y": 361,
              "w": 240,
              "h": 142
            },
            "scale": 0.667
          },
          "b": {
            "srcSize": {
              "width": 702,
              "height": 1520
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 29,
              "y": 217,
              "w": 143,
              "h": 86
            },
            "scale": 1.111
          }
        }
      },
      {
        "id": "l4:ios-vs-skyline",
        "mode": "cross-runtime",
        "a": "l4.ios.png",
        "b": "l4.skyline.png",
        "verdict": "changed",
        "diffPixels": 5649,
        "sampleCount": 337080,
        "diffRatio": 0.01676,
        "hashDistance": 0,
        "translation": null,
        "knownNoise": "N-L4-five-end-rasterization",
        "norm": {
          "outSize": {
            "w": 640,
            "h": 560
          },
          "a": {
            "srcSize": {
              "width": 1206,
              "height": 2622
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 48,
              "y": 361,
              "w": 240,
              "h": 142
            },
            "scale": 0.667
          },
          "b": {
            "srcSize": {
              "width": 702,
              "height": 1520
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 29,
              "y": 217,
              "w": 143,
              "h": 86
            },
            "scale": 1.111
          }
        }
      },
      {
        "id": "l4:ios-vs-web",
        "mode": "cross-runtime",
        "a": "l4.ios.png",
        "b": "l4.web.png",
        "verdict": "changed",
        "diffPixels": 4314,
        "sampleCount": 337080,
        "diffRatio": 0.0128,
        "hashDistance": 0,
        "translation": null,
        "knownNoise": "N-L4-five-end-rasterization",
        "norm": {
          "outSize": {
            "w": 640,
            "h": 560
          },
          "a": {
            "srcSize": {
              "width": 1206,
              "height": 2622
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 48,
              "y": 361,
              "w": 240,
              "h": 142
            },
            "scale": 0.667
          },
          "b": {
            "srcSize": {
              "width": 780,
              "height": 1688
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 32,
              "y": 240,
              "w": 160,
              "h": 96
            },
            "scale": 1
          }
        }
      },
      {
        "id": "l4:ios-vs-webview",
        "mode": "cross-runtime",
        "a": "l4.ios.png",
        "b": "l4.webview.png",
        "verdict": "changed",
        "diffPixels": 5660,
        "sampleCount": 337080,
        "diffRatio": 0.01679,
        "hashDistance": 0,
        "translation": null,
        "knownNoise": "N-L4-five-end-rasterization",
        "norm": {
          "outSize": {
            "w": 640,
            "h": 560
          },
          "a": {
            "srcSize": {
              "width": 1206,
              "height": 2622
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 48,
              "y": 361,
              "w": 240,
              "h": 142
            },
            "scale": 0.667
          },
          "b": {
            "srcSize": {
              "width": 702,
              "height": 1520
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 29,
              "y": 217,
              "w": 143,
              "h": 86
            },
            "scale": 1.111
          }
        }
      },
      {
        "id": "l4:skyline-vs-web",
        "mode": "cross-runtime",
        "a": "l4.skyline.png",
        "b": "l4.web.png",
        "verdict": "changed",
        "diffPixels": 3905,
        "sampleCount": 337080,
        "diffRatio": 0.01158,
        "hashDistance": 0,
        "translation": null,
        "knownNoise": "N-L4-five-end-rasterization",
        "norm": {
          "outSize": {
            "w": 640,
            "h": 560
          },
          "a": {
            "srcSize": {
              "width": 702,
              "height": 1520
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 29,
              "y": 217,
              "w": 143,
              "h": 86
            },
            "scale": 1.111
          },
          "b": {
            "srcSize": {
              "width": 780,
              "height": 1688
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 32,
              "y": 240,
              "w": 160,
              "h": 96
            },
            "scale": 1
          }
        }
      },
      {
        "id": "l4:skyline-vs-webview",
        "mode": "same-runtime",
        "a": "l4.skyline.png",
        "b": "l4.webview.png",
        "verdict": "changed",
        "diffPixels": 2673,
        "sampleCount": 337080,
        "diffRatio": 0.00793,
        "hashDistance": 0,
        "translation": null,
        "knownNoise": "N-L4-five-end-rasterization",
        "norm": {
          "outSize": {
            "w": 640,
            "h": 560
          },
          "a": {
            "srcSize": {
              "width": 702,
              "height": 1520
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 29,
              "y": 217,
              "w": 143,
              "h": 86
            },
            "scale": 1.111
          },
          "b": {
            "srcSize": {
              "width": 702,
              "height": 1520
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 29,
              "y": 217,
              "w": 143,
              "h": 86
            },
            "scale": 1.111
          }
        }
      },
      {
        "id": "l4:web-vs-webview",
        "mode": "cross-runtime",
        "a": "l4.web.png",
        "b": "l4.webview.png",
        "verdict": "changed",
        "diffPixels": 2793,
        "sampleCount": 337080,
        "diffRatio": 0.00829,
        "hashDistance": 0,
        "translation": null,
        "knownNoise": "N-L4-five-end-rasterization",
        "norm": {
          "outSize": {
            "w": 640,
            "h": 560
          },
          "a": {
            "srcSize": {
              "width": 780,
              "height": 1688
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 32,
              "y": 240,
              "w": 160,
              "h": 96
            },
            "scale": 1
          },
          "b": {
            "srcSize": {
              "width": 702,
              "height": 1520
            },
            "colorSpace": "undeclared",
            "block": {
              "x": 29,
              "y": 217,
              "w": 143,
              "h": 86
            },
            "scale": 1.111
          }
        }
      }
    ],
    "endNorm": {
      "android": {
        "srcSize": {
          "width": 1200,
          "height": 2608
        },
        "colorSpace": "display-p3",
        "block": {
          "x": 48,
          "y": 360,
          "w": 240,
          "h": 144
        },
        "scale": 0.667
      },
      "ios-device": {
        "srcSize": {
          "width": 1170,
          "height": 2532
        },
        "colorSpace": "undeclared",
        "block": {
          "x": 48,
          "y": 361,
          "w": 240,
          "h": 142
        },
        "scale": 0.667
      },
      "ios": {
        "srcSize": {
          "width": 1206,
          "height": 2622
        },
        "colorSpace": "undeclared",
        "block": {
          "x": 48,
          "y": 361,
          "w": 240,
          "h": 142
        },
        "scale": 0.667
      },
      "skyline": {
        "srcSize": {
          "width": 702,
          "height": 1520
        },
        "colorSpace": "undeclared",
        "block": {
          "x": 29,
          "y": 217,
          "w": 143,
          "h": 86
        },
        "scale": 1.111
      },
      "web": {
        "srcSize": {
          "width": 780,
          "height": 1688
        },
        "colorSpace": "undeclared",
        "block": {
          "x": 32,
          "y": 240,
          "w": 160,
          "h": 96
        },
        "scale": 1
      },
      "webview": {
        "srcSize": {
          "width": 702,
          "height": 1520
        },
        "colorSpace": "undeclared",
        "block": {
          "x": 29,
          "y": 217,
          "w": 143,
          "h": 86
        },
        "scale": 1.111
      }
    }
  },
  "shots": [
    {
      "end": "skyline",
      "file": "l4.skyline.png",
      "pub": "l4-skyline.png",
      "label": "微信 Skyline"
    },
    {
      "end": "webview",
      "file": "l4.webview.png",
      "pub": "l4-webview.png",
      "label": "微信 WebView"
    },
    {
      "end": "web",
      "file": "l4.web.png",
      "pub": "l4-web.png",
      "label": "浏览器 Web"
    },
    {
      "end": "android",
      "file": "l4.android.png",
      "pub": "l4-android.png",
      "label": "Android（真机）"
    },
    {
      "end": "ios",
      "file": "l4.ios.png",
      "pub": "l4-ios.png",
      "label": "iOS（模拟器）"
    },
    {
      "end": "ios-device",
      "file": "l4.ios-device.png",
      "pub": "l4-ios-device.png",
      "label": "iOS（真机）"
    }
  ],
  "sfc": {
    "source": "examples/pages/consistency-stress.vue（真 SFC：44 节点 · 10 行 v-for · 行内动态绑定）",
    "gate": false,
    "endCount": 5,
    "pairs": [
      {
        "id": "sfc:android-vs-ios-device",
        "mode": "cross-runtime",
        "verdict": "changed",
        "diffPixels": 5610,
        "sampleCount": 245520,
        "diffRatio": 0.02285,
        "hashDistance": 0
      },
      {
        "id": "sfc:android-vs-ios",
        "mode": "cross-runtime",
        "verdict": "changed",
        "diffPixels": 4491,
        "sampleCount": 245520,
        "diffRatio": 0.01829,
        "hashDistance": 0
      },
      {
        "id": "sfc:android-vs-mp.skyline",
        "mode": "cross-runtime",
        "verdict": "changed",
        "diffPixels": 6834,
        "sampleCount": 245520,
        "diffRatio": 0.02783,
        "hashDistance": 0
      },
      {
        "id": "sfc:android-vs-web",
        "mode": "cross-runtime",
        "verdict": "changed",
        "diffPixels": 4673,
        "sampleCount": 245520,
        "diffRatio": 0.01903,
        "hashDistance": 0
      },
      {
        "id": "sfc:ios-device-vs-ios",
        "mode": "same-platform",
        "verdict": "changed",
        "diffPixels": 1266,
        "sampleCount": 245520,
        "diffRatio": 0.00516,
        "hashDistance": 0
      },
      {
        "id": "sfc:ios-device-vs-mp.skyline",
        "mode": "cross-runtime",
        "verdict": "changed",
        "diffPixels": 7157,
        "sampleCount": 245520,
        "diffRatio": 0.02915,
        "hashDistance": 0
      },
      {
        "id": "sfc:ios-device-vs-web",
        "mode": "cross-runtime",
        "verdict": "changed",
        "diffPixels": 4590,
        "sampleCount": 245520,
        "diffRatio": 0.0187,
        "hashDistance": 0
      },
      {
        "id": "sfc:ios-vs-mp.skyline",
        "mode": "cross-runtime",
        "verdict": "changed",
        "diffPixels": 7125,
        "sampleCount": 245520,
        "diffRatio": 0.02902,
        "hashDistance": 0
      },
      {
        "id": "sfc:ios-vs-web",
        "mode": "cross-runtime",
        "verdict": "changed",
        "diffPixels": 4261,
        "sampleCount": 245520,
        "diffRatio": 0.01736,
        "hashDistance": 0
      },
      {
        "id": "sfc:mp.skyline-vs-web",
        "mode": "cross-runtime",
        "verdict": "changed",
        "diffPixels": 6852,
        "sampleCount": 245520,
        "diffRatio": 0.02791,
        "hashDistance": 0
      }
    ],
    "ends": [
      {
        "end": "android",
        "label": "Android 真机（Vapor）",
        "file": "sfc.android.png",
        "scale": 0.333334,
        "srcSize": {
          "width": 1200,
          "height": 2608
        }
      },
      {
        "end": "ios-device",
        "label": "iOS 真机（Vapor）",
        "file": "sfc.ios-device.png",
        "scale": 0.333333,
        "srcSize": {
          "width": 1170,
          "height": 2532
        }
      },
      {
        "end": "ios",
        "label": "iOS 模拟器（Vapor）",
        "file": "sfc.ios.png",
        "scale": 0.333333,
        "srcSize": {
          "width": 1206,
          "height": 2622
        }
      },
      {
        "end": "mp.skyline",
        "label": "微信 Skyline（编译产物）",
        "file": "sfc.mp.skyline.png",
        "scale": 0.609477,
        "srcSize": {
          "width": 640,
          "height": 1386
        }
      },
      {
        "end": "web",
        "label": "浏览器 Web（编译产物）",
        "file": "sfc.web.png",
        "scale": 0.5,
        "srcSize": {
          "width": 780,
          "height": 1688
        }
      }
    ],
    "shots": [
      {
        "end": "web",
        "file": "sfc.web.png",
        "pub": "sfc-web.png",
        "label": "浏览器 Web（SFC 编译产物）"
      },
      {
        "end": "mp.skyline",
        "file": "sfc.mp.skyline.png",
        "pub": "sfc-mp-skyline.png",
        "label": "微信 Skyline（SFC 编译产物）"
      },
      {
        "end": "android",
        "file": "sfc.android.png",
        "pub": "sfc-android.png",
        "label": "Android 真机（Vapor 实例化）"
      },
      {
        "end": "ios",
        "file": "sfc.ios.png",
        "pub": "sfc-ios.png",
        "label": "iOS 模拟器（Vapor 实例化）"
      },
      {
        "end": "ios-device",
        "file": "sfc.ios-device.png",
        "pub": "sfc-ios-device.png",
        "label": "iOS 真机（Vapor 实例化）"
      }
    ]
  },
  "debt": [
    {
      "file": "examples/profile-boundary-baseline.json",
      "count": 36
    },
    {
      "file": "showcase/profile-boundary-baseline.json",
      "count": 32
    }
  ]
} as const
