#!/usr/bin/env bash
# verify.sh - G-32 严格校验（可独立复现：从包目录读取 MANIFEST + CHECKSUM）
#
# 用法：
#   ./verify.sh                    # 校验当前目录的 zip
#   （解压 zip 后进入目录运行，无需工作区 CHECKSUM）
#
# 检查项：
#   1) unzip -t 完整性
#   2) MANIFEST 双向比对（缺失/多余）
#   3) SHA256 自证（重算 vs 包内 CHECKSUM.md）
#   4) 术语在位
#   5) 既有 plan 引用计数
#   6) 规则编号冲突（WARN）
set -uo pipefail
shopt -s nullglob   # 无匹配时返回空而非字面量

HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"

ZIP="proteus-semantic-primitives.zip"
PASS=1; WARN=0
die() { echo "[FAIL] $*" >&2; PASS=0; exit 1; }

# 自动定位 DIR（包目录），支持三种场景：
#   a) 当前目录是包目录本身（含 MANIFEST + G-32 主文档）  ← 下载者 cd 进去
#   b) 当前目录含已解压的 proteus-semantic-primitives/ 子目录
#   c) 当前目录含 zip（临时解压到 TMP）
if [[ -f MANIFEST && -f G-32-complete-semantic-architecture.md ]]; then
  DIR="$HERE"
elif [[ -d proteus-semantic-primitives ]]; then
  DIR="$HERE/proteus-semantic-primitives"
elif [[ -f "$ZIP" ]]; then
  TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
  unzip -q "$ZIP" -d "$TMP"
  DIR="$TMP/proteus-semantic-primitives"
else
  die "无法定位包目录：当前目录应含 MANIFEST + G-32 主文档，或含 $ZIP"
fi

MANIFEST_FILE="$DIR/MANIFEST"
CHECKSUM_FILE="$DIR/CHECKSUM.md"
[[ -f "$MANIFEST_FILE" ]] || die "包内缺少 MANIFEST"
[[ -f "$CHECKSUM_FILE" ]] || die "包内缺少 CHECKSUM.md（请重新 pack）"

# ---------- 1) 完整性 ----------
if [[ -f "$HERE/$ZIP" ]]; then
  if ! unzip -t "$HERE/$ZIP" >/dev/null 2>&1; then die "unzip -t 失败"; fi
  echo "[ok] 1. unzip -t 完整性 ($(basename "$ZIP"))"
else
  echo "[ok] 1. 跳过 unzip -t（直接校验解压目录）"
fi
echo "     DIR=$DIR"

# ---------- 2) MANIFEST 双向比对 ----------
# 实际文件（排除 CHECKSUM.md）
ACTUAL=()
for f in "$DIR"/*.md; do
  base=$(basename "$f")
  [[ "$base" == "CHECKSUM.md" ]] && continue
  ACTUAL+=("$base")
done

# 期望文件（排除 CHECKSUM.md / 注释 / 空白）
EXPECTED=()
while IFS= read -r raw; do
  entry=$(echo "$raw" | tr -d '[:space:]')
  [[ -z "$entry" || "$entry" == \#* ]] && continue
  [[ "$entry" == "CHECKSUM.md" ]] && continue
  EXPECTED+=("$entry")
done < "$MANIFEST_FILE"

miss=0
for e in "${EXPECTED[@]}"; do
  hit=0
  for a in "${ACTUAL[@]}"; do [[ "$a" == "$e" ]] && hit=1 && break; done
  [[ $hit -eq 0 ]] && { echo "[FAIL] MANIFEST 文件缺失: $e"; miss=$((miss+1)); PASS=0; }
done
extra=0
for a in "${ACTUAL[@]}"; do
  hit=0
  for e in "${EXPECTED[@]}"; do [[ "$e" == "$a" ]] && hit=1 && break; done
  [[ $hit -eq 0 ]] && { echo "[FAIL] 多余文件: $a"; extra=$((extra+1)); PASS=0; }
done
echo "[ok] 2. MANIFEST 双向比对 (缺失:$miss 多余:$extra)"

# ---------- 3) SHA256 自证 ----------
REBUILT=$(mktemp)
{
  echo "# SHA256 Checksums (generated by pack.sh)"
  echo
  for f in "$DIR"/*.md; do
    base=$(basename "$f")
    [[ "$base" == "CHECKSUM.md" ]] && continue
    printf '%s  %s\n' "$(sha256sum "$f" | cut -d' ' -f1)" "$base"
  done | sort -k2
} > "$REBUILT"

if ! diff -q "$CHECKSUM_FILE" "$REBUILT" >/dev/null 2>&1; then
  echo "[FAIL] SHA256 不一致 (CHECKSUM.md vs 实际重算)"
  diff "$CHECKSUM_FILE" "$REBUILT" | head -40
  PASS=0
else
  echo "[ok] 3. SHA256 逐条一致"
fi
rm -f "$REBUILT"

# ---------- 4) 术语在位 ----------
TERMS=(ProteusRenderBackend useNative "Component IR" G-32 CMP009 miniprogram "@conditional" "128")
term_miss=0
for t in "${TERMS[@]}"; do
  c=$(grep -rch "$t" --include="*.md" "$DIR" 2>/dev/null | awk '{s+=$1} END{print s+0}')
  [[ "$c" -eq 0 ]] && { echo "[FAIL] 术语缺失: $t"; term_miss=$((term_miss+1)); PASS=0; }
done
echo "[ok] 4. 术语在位检查 (${#TERMS[@]} 项, 缺失:$term_miss)"

# ---------- 5) 既有引用计数 ----------
REFS=(G-27 G-28 G-29 G-30 G-31 PROTEUS-METHODOLOGY "原则#0")
total=0
for r in "${REFS[@]}"; do
  total=$((total + $(grep -rch "$r" --include="*.md" "$DIR" 2>/dev/null | awk '{s+=$1} END{print s+0}')))
done
echo "[ok] 5. 既有引用共 $total 处"
[[ $total -lt 20 ]] && { echo "[FAIL] 既有引用过少: $total < 20"; PASS=0; }

# ---------- 6) 规则编号冲突（WARN 不阻断）----------
CONFLICT=$(grep -rhoE "G-30\.[0-9]+|NAT00[0-9]|CMP00[0-8]" "$DIR" --include="*.md" 2>/dev/null | sort -u | head)
if [[ -n "$CONFLICT" ]]; then
  echo "[WARN] 检测到可能与 G-30/早期规则重叠的编号，请人工复核:"
  echo "$CONFLICT" | sed 's/^/       /'
  WARN=1
else
  echo "[ok] 6. 规则编号无冲突"
fi

# ---------- 收尾 ----------
echo
if [[ "$PASS" == "1" ]]; then
  echo "VERIFY: PASS"
  [[ "$WARN" == "1" ]] && echo "(含 WARN，不阻断)"
  exit 0
else
  echo "VERIFY: FAIL"
  exit 1
fi
