// src/router/auto-routes.ts —— 路由表（AUTO-GENERATED by gen-routes.ts，勿手动编辑）
// 模板初始占位：仅首页。运行 npm run build:mp / dev:mp 后由 gen-routes 重新生成。
import type { RouteRecord } from './types'

export const routes: RouteRecord[] = [
  { name: 'index', path: 'pages/index', component: '../pages/index.vue', meta: { title: '首页', isTab: true } },
]

export const tabRoutes: RouteRecord[] = routes.filter((r) => r.meta?.isTab)
export const routeMap: Record<string, RouteRecord> = routes.reduce((m, r) => {
  m[r.name] = r
  return m
}, {} as Record<string, RouteRecord>)
