// src/router/auto-routes.ts —— 应用侧路由表（AUTO-GENERATED by scripts/gen-routes.ts，勿手动编辑）
// ★拆包步骤 4：auto-routes 随应用存放（工厂化后路由表由应用注入 createRouter），不再属于 @proteus/router 包
import type { RouteRecord } from '@proteus/router/types'

export const routes: RouteRecord[] = [
  { name: "index", path: "pages/index", component: "../pages/index.vue", meta: {"title":"首页","isTab":true} },
]

export const tabRoutes: RouteRecord[] = routes.filter(r => r.meta?.isTab)
export const routeMap: Record<string, RouteRecord> = routes.reduce((m, r) => { m[r.name] = r; return m }, {} as Record<string, RouteRecord>)

// ★ 类型提示：按路由名索引的参数类型表（来源：<route> 块 params 声明）
declare module '@proteus/router/types' {
  interface RouteParamsByName {
    'index': {  },
  }
}