// packages/cli/src/ci.ts
// ★cli-plus G-33 M4：proteus ci:init —— CI/CD 模板生成（02-build-pipeline.md §3）
// 生成 .github/workflows/proteus.yml（GitHub Actions）/ .gitlab-ci.yml / .circleci/config.yml
// 流水线：proteus check（四域门禁）→ proteus build --target <各端> → 产物归档
// 纯函数模板生成（YAML 字符串可单测断言；写入由 planCiInit 落盘）
import fs from 'node:fs'
import path from 'node:path'

export type CiPlatform = 'github' | 'gitlab' | 'circleci'

export interface CiInitOptions {
  platform: CiPlatform
  /** build 目标端（web/skyline；02 §3 build --targets all 的逐端步骤） */
  targets: string[]
}

/** 平台 → 配置文件相对路径 */
export const CI_FILE_PATHS: Record<CiPlatform, string> = {
  github: '.github/workflows/proteus.yml',
  gitlab: '.gitlab-ci.yml',
  circleci: '.circleci/config.yml',
}

const CI_PLATFORMS: CiPlatform[] = ['github', 'gitlab', 'circleci']

/** 解析 ci:init 参数：--platform <github|gitlab|circleci>（默认 github）+ --targets a,b（默认 web,skyline）+ 位置参数目录 */
export function parseCiArgs(args: string[]): { options: CiInitOptions; dir: string } {
  let platform: CiPlatform = 'github'
  let targets = ['web', 'skyline']
  const positional: string[] = []
  for (let i = 0; i < args.length; i++) {
    const a = args[i]
    if (a === '--platform') {
      const v = args[++i]
      if (!v || !(CI_PLATFORMS as string[]).includes(v)) throw new Error(`ci:init --platform 非法：${v}（支持 ${CI_PLATFORMS.join('/')}）`)
      platform = v as CiPlatform
    } else if (a === '--targets') {
      const v = args[++i]
      if (!v) throw new Error('ci:init --targets 缺少值（如 --targets web,skyline）')
      targets = v.split(',').map((t) => t.trim()).filter(Boolean)
      if (targets.length === 0) throw new Error('ci:init --targets 为空')
    } else if (a.startsWith('--')) {
      throw new Error(`ci:init 未知参数：${a}`)
    } else {
      positional.push(a)
    }
  }
  if (positional.length > 1) throw new Error(`ci:init 多余位置参数：${positional.slice(1).join(' ')}`)
  return { options: { platform, targets }, dir: positional[0] ?? '.' }
}

function buildSteps(targets: string[]): string {
  return targets.map((t) => `      - run: npx proteus build --target ${t}`).join('\n')
}

/** GitHub Actions：check 门禁 + 逐端构建 + 测试（L1-L3 + Web E2E，§08 约束）+ 产物归档 */
function githubWorkflow(opts: CiInitOptions): string {
  return `# AUTO-GENERATED by proteus ci:init（cli-plus G-33 M4）。DO NOT EDIT.
# 流水线：proteus check（CSS/Style/Router/CLI 四域门禁）→ 逐端构建 → 测试（§08：L1-L3 + Web E2E；
#   automator MP E2E 需 GUI，仅 Mac runner / 云测节点条件执行，此处不启用）
name: Proteus CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - run: npm ci
      - name: proteus check（四域门禁）
        run: npx proteus check
  build:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - run: npm ci
${buildSteps(opts.targets)}
      - uses: actions/upload-artifact@v4
        with:
          name: proteus-dist
          path: |
            dist/
            dist/mp-weixin/
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - run: npm ci
      - name: 单测 + 编译快照（L1-L3，§08 所有节点可跑）
        run: npx proteus test
      - name: Web E2E（Playwright headless，依赖 build:web 产物）
        run: npx proteus build --target web && npx proteus test e2e:web
`
}

/** GitLab CI：stages（check → build → test）+ 逐端构建 + 测试 + artifacts */
function gitlabWorkflow(opts: CiInitOptions): string {
  const steps = opts.targets.map((t) => `    - npx proteus build --target ${t}`).join('\n')
  return `# AUTO-GENERATED by proteus ci:init（cli-plus G-33 M4）。DO NOT EDIT.
stages:
  - check
  - build
  - test

check:
  stage: check
  image: node:22
  script:
    - npm ci
    - npx proteus check

build:
  stage: build
  image: node:22
  needs: [check]
  script:
    - npm ci
${steps}
  artifacts:
    paths:
      - dist/
      - dist/mp-weixin/

test:
  stage: test
  image: node:22
  needs: [build]
  script:
    - npm ci
    - npx proteus test
    - npx proteus build --target web
    - npx proteus test e2e:web
`
}

/** CircleCI：jobs + workflows（check → build → test，requires 依赖顺序） */
function circleciWorkflow(opts: CiInitOptions): string {
  const steps = opts.targets.map((t) => `      - run: npx proteus build --target ${t}`).join('\n')
  return `# AUTO-GENERATED by proteus ci:init（cli-plus G-33 M4）。DO NOT EDIT.
version: 2.1

jobs:
  check:
    docker:
      - image: cimg/node:22
    steps:
      - checkout
      - run: npm ci
      - run: npx proteus check
  build:
    docker:
      - image: cimg/node:22
    steps:
      - checkout
      - run: npm ci
${steps}
      - store_artifacts:
          path: dist
  test:
    docker:
      - image: cimg/node:22
    steps:
      - checkout
      - run: npm ci
      - run: npx proteus test
      - run: npx proteus build --target web
      - run: npx proteus test e2e:web

workflows:
  version: 2
  ci:
    jobs:
      - check
      - build:
          requires: [check]
      - test:
          requires: [build]
`
}

/** 生成 CI workflow 内容（纯函数） */
export function generateCiWorkflow(opts: CiInitOptions): string {
  switch (opts.platform) {
    case 'github':
      return githubWorkflow(opts)
    case 'gitlab':
      return gitlabWorkflow(opts)
    case 'circleci':
      return circleciWorkflow(opts)
  }
}

export interface CiInitResult {
  file: string
  content: string
}

/** 规划落盘：生成 workflow 并写入项目目录（返回文件相对路径 + 内容） */
export function planCiInit(dir: string, opts: CiInitOptions): CiInitResult {
  const file = CI_FILE_PATHS[opts.platform]
  const content = generateCiWorkflow(opts)
  const full = path.join(dir, file)
  fs.mkdirSync(path.dirname(full), { recursive: true })
  fs.writeFileSync(full, content)
  return { file, content }
}
