// packages/cli/src/strict-cli.ts
// ★cli-plus G-33 M1：--strict-cli 严格规则（01-cli.md §6 + 03-strict-cli.md §1 CLI001-004）
// CLI001 config 校验失败（error，config:check 已有）
// CLI002 缺失必要 target 配置（error）
// CLI003 能力开关冲突（warn）：feature 开启但 targets 含不支持端
// CLI004 .proteus/ 生成文件一致性（warn）：自动生成文件被手动修改（头部标记检测）
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'

/** 能力开关 → 支持平台矩阵（基于 G 表批次认知；平台声明在 defineProteus targets） */
export const FEATURE_PLATFORM_MATRIX: Record<string, string[]> = {
  glass: ['web', 'skyline', 'ios', 'android', 'harmony'], // G-29 五端
  safeArea: ['web', 'skyline', 'ios', 'android', 'harmony'], // G-23 五端 insets
  memorial: ['web', 'skyline'], // G-25 灰度滤镜 Web/Skyline 先行
  skeleton: ['web', 'skyline', 'ios', 'android', 'harmony'], // G-26
  styleSafety: ['web', 'skyline', 'ios', 'android', 'harmony'], // G-31 五端闸门
  strictRouter: ['web', 'skyline', 'ios', 'android', 'harmony'], // G-32
}

/** 生成文件标记（非 JSON 原生文件头部注释用；JSON 生成文件走 .generated.json 指纹） */
export const AUTO_GENERATED_MARK = 'AUTO-GENERATED BY PROTEUS'

/** 生成文件指纹登记文件（CLI004 基线：路径 → sha256） */
export const GENERATED_MANIFEST_FILE = '.proteus/.generated.json'

function fileHash(file: string): string {
  return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')
}

/** 生成器写文件后登记指纹（CLI004 基线；capability-manifest/module-audit 调用） */
export function registerGeneratedFile(file: string): void {
  const abs = path.resolve(file)
  const manifestPath = path.join(path.dirname(abs), '.generated.json')
  let entries: Record<string, string> = {}
  if (fs.existsSync(manifestPath)) {
    try {
      entries = JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
    } catch {
      entries = {}
    }
  }
  entries[path.basename(abs)] = fileHash(abs)
  fs.writeFileSync(manifestPath, JSON.stringify(entries, null, 2) + '\n')
}

export interface StrictCliViolation {
  code: string // CLI001-004
  severity: 'error' | 'warn'
  message: string
}

/** CLI002：缺失必要 target 配置（defineProteus 形态 targets 为空/缺 entry）
 * ★形态识别：旧 ProteusConfig（platform 单端编译管线）不适用 CLI002（无 targets 语义） */
export function checkRequiredTargets(config: unknown): StrictCliViolation[] {
  const out: StrictCliViolation[] = []
  const c = (config ?? {}) as { entry?: unknown; targets?: unknown; platform?: unknown }
  // 旧形态（platform 驱动单端管线）→ 跳过（CLI002 仅针对 defineProteus 多端 targets 形态）
  if (typeof c.platform === 'string' && !('targets' in c)) return out
  if (typeof c.entry !== 'string' || !c.entry) {
    out.push({ code: 'CLI002', severity: 'error', message: '缺失必要配置 entry（五端统一入口）' })
  }
  if (!c.targets || typeof c.targets !== 'object' || Object.keys(c.targets as object).length === 0) {
    out.push({ code: 'CLI002', severity: 'error', message: '缺失必要 target 配置（targets 至少声明一个端）' })
  }
  return out
}

/** CLI003：能力开关冲突——feature 开启但 targets 含不支持端（warn） */
export function checkFeatureConflicts(config: unknown): StrictCliViolation[] {
  const out: StrictCliViolation[] = []
  const c = (config ?? {}) as { features?: Record<string, boolean>; targets?: Record<string, unknown> }
  const features = c.features ?? {}
  const targets = c.targets ?? {}
  const declaredTargets = Object.keys(targets)
  for (const [feature, enabled] of Object.entries(features)) {
    if (enabled !== true) continue
    const supported = FEATURE_PLATFORM_MATRIX[feature]
    if (!supported) {
      out.push({ code: 'CLI003', severity: 'warn', message: `未知能力开关 ${feature}（注册表见 FEATURE_PLATFORM_MATRIX）` })
      continue
    }
    const unsupported = declaredTargets.filter((t) => supported.indexOf(t) < 0)
    if (unsupported.length) {
      out.push({ code: 'CLI003', severity: 'warn', message: `能力 ${feature} 已开启但 target ${unsupported.join('/')} 不支持（支持端：${supported.join('/')}）` })
    }
  }
  return out
}

/** CLI004：.proteus/ 生成文件一致性——指纹对比（.generated.json 基线，检测手动修改） */
export function checkProteusDirConsistency(proteusDir: string): StrictCliViolation[] {
  const out: StrictCliViolation[] = []
  const manifestPath = path.join(proteusDir, '.generated.json')
  if (!fs.existsSync(manifestPath)) return out // 未生成/无基线 → 跳过
  let baseline: Record<string, string>
  try {
    baseline = JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
  } catch {
    out.push({ code: 'CLI004', severity: 'warn', message: '.proteus/.generated.json 基线损坏（重新生成即可）' })
    return out
  }
  const modified: string[] = []
  for (const [name, expectedHash] of Object.entries(baseline)) {
    const file = path.join(proteusDir, name)
    if (!fs.existsSync(file)) {
      out.push({ code: 'CLI004', severity: 'warn', message: `生成文件缺失：${name}（重新生成即可）` })
      continue
    }
    if (fileHash(file) !== expectedHash) {
      modified.push(name)
    }
  }
  for (const name of modified.slice(0, 10)) {
    out.push({ code: 'CLI004', severity: 'warn', message: `${name} 与生成基线不一致——疑似手动修改（.proteus/ 可删可重建）` })
  }
  if (modified.length > 10) {
    out.push({ code: 'CLI004', severity: 'warn', message: `另有 ${modified.length - 10} 个生成文件疑似被手动修改` })
  }
  return out
}
