// packages/devtools/src/index.ts —— @proteus-vue/devtools 公共入口（devtools-plan UI 层）
// 浏览器端开发工具面板：五视图渲染（时间轴/状态/路由回溯/火焰图/根因）+ 面板装配 + WS/CDP 数据源
export { createDevtoolsPanel } from './panel'
export type { DevtoolsPanel, DevtoolsPanelOptions } from './panel'
export { createDevtoolsWsSource } from './source'
export type { DevtoolsSource } from './source'
export { createTraceBusSource } from './source'
export { createTraceBusWsBridge } from './ws-bridge'
export type { TraceBusWsBridge, TraceBusWsBridgeOptions } from './ws-bridge'
export { installProteusTimeline, installProteusInspectors, PROTEUS_DEVTOOLS_PLUGIN_DESCRIPTOR } from './vue-devtools'
export type { VueDevtoolsApiLike, VueDevtoolsTimelineOptions, VueDevtoolsTimeline, VueDevtoolsInspectorApiLike, ProteusInspectorsOptions, ProteusInspectors } from './vue-devtools'
export { renderTimeline } from './views/timeline'
export type { TimelineViewData, TimelineWindow } from './views/timeline'
export { createTimelineZoom } from './views/timeline-interaction'
export type { TimelineZoom, TimelineZoomOptions } from './views/timeline-interaction'
export { renderFlamegraph } from './views/flamegraph'
export type { FlamegraphViewData } from './views/flamegraph'
export { renderState } from './views/state'
export type { StateViewData, StateViewHooks } from './views/state'
export { renderRoute } from './views/route'
export type { RouteViewData } from './views/route'
export { renderErrors } from './views/errors'
export type { ErrorsViewData } from './views/errors'
export { renderComponents } from './views/components'
export type { ComponentsViewData, ComponentNodeData, ComponentsViewHooks } from './views/components'
export { renderPages } from './views/pages'
export type { PagesViewData, PageRouteData } from './views/pages'
export { renderGraph } from './views/graph'
export type { GraphViewData } from './views/graph'
export { renderDevice } from './views/device'
export type { DeviceInfo, DeviceViewData, DeviceMemorySample, DeviceCapabilityInfo, DeviceMemoryInfo, DeviceScreenInfo } from './views/device'
export { serializeStoreSnapshot, parseStoreSnapshot } from './snapshot-io'
export type { StoreSnapshotIO, StoreRestoreEntry, StoreStepIO, ParsedStoreSnapshot } from './snapshot-io'
export { installComponentTrace } from './component-trace'
export type { ComponentTraceBus, ComponentSnapshot, ComponentTraceHandle, DomTreeNode } from './component-trace'
export { buildDomTree } from './component-trace'
export { installProteusDevtools } from './install'
export type { InstallDevtoolsOptions, InstalledDevtools, StyleGuardLike } from './install'
export { createTooltipLayer, bindTooltip, attachTip, resolveTipData } from './tooltip'
export type { TooltipData, TooltipLayer } from './tooltip'
export { createPluginRegistry, createMemoryStorage, createCommandRegistry, resolveActivationOrder } from './plugins'
export type { DevToolsPlugin, PluginContext, PluginBus, PanelAPI, CommandRegistry, KVStorage, PluginEntry } from './plugins'
export { createNetworkPlugin } from './plugins/network'
