// packages/router/src/codegen/app.ts
// M5 — App 端 codegen（docs/proteus-router-plan 05）：RouteNode[] → 屏注册表代码（navigation.generated.ts 形态）
//
// 【与 M3/M4 并列的第三条 codegen 腿】输入同一份 scan/tree 管线产物（RouteNode[]，含 loc 可反查源码）；
//   输出 `generateAppScreens` 的源码形态，供 `createAppStack({ screens })` 消费。
//
// 【★转场列（meta.transition）在 App 端不是"报名字给平台"】Web 端映射到 Vue <Transition> name、
//   MP 端映射到 `routeType`，而 App 端**自己驱动动画**（Morpheus/内核曲线那套）：
//   这里只把枚举**原样**带进注册表（单一来源），由运行时经 `appTransition`（packages/animation）
//   换成转场规格。⇒ codegen 不引 animation 包（router 包保持零动画依赖——方向纪律）。
//
// 【★嵌套 children】App 端 children **有意义**（不同于小程序平铺降级）：编译为嵌套栈结构
//   （tab 里每个 tab 各有一个栈，§3.3）——`children` 字段 + `tabStacks` 聚合产物。
import type { RouteNode } from '../types'
import type { RouteTransition } from '../transforms/transform-transition'

/** 屏注册表条目（codegen 产物；`screens` 记录的值形态） */
export interface AppScreenEntry {
  /** 命名路由（kebab-case；= 注册表 key） */
  name: string
  /** 路由 path（屏 id 语义，栈内匹配/popTo 用） */
  path: string
  /** 组件路径（lazy 时生成 `() => import(...)` 工厂） */
  componentPath: string
  /** 转场枚举（undefined = 用引擎默认；来源 `<route>.meta.transition`）——与 AppScreenSpec 同型（两半咬合） */
  transition?: RouteTransition
  /** 嵌套子屏（App 嵌套栈：children 有意义） */
  children: string[]
  /** 是否 tab 根（meta.isTab；嵌套栈聚合用） */
  isTab: boolean
  /** ★M5 内存治理：该屏的节点预算估算（可选；`budgetNodes` 未声明时用栈级 defaultScreenNodes） */
  budgetNodes?: number
}

/** RouteNode → 屏条目（去除 loc 等编译期字段，只留运行时需要的） */
export function toScreenEntry(node: RouteNode): AppScreenEntry {
  const name = node.name ?? node.path.replace(/^\//, '').replace(/\//g, '-')
  const entry: AppScreenEntry = {
    name,
    path: node.path,
    componentPath: node.componentPath,
    children: node.children.map((c) => c.name ?? c.path.replace(/^\//, '').replace(/\//g, '-')),
    isTab: node.meta.isTab === true,
  }
  if (node.meta.transition) entry.transition = node.meta.transition
  const budget = node.meta.budgetNodes
  if (typeof budget === 'number' && budget > 0) entry.budgetNodes = budget
  return entry
}

/** 嵌套树 → 平铺条目（App 端保留 children 名单——与 MP 的「降级平铺」不同，这里只是便于查表） */
export function flattenScreenEntries(nodes: RouteNode[]): AppScreenEntry[] {
  const out: AppScreenEntry[] = []
  for (const n of nodes) {
    out.push(toScreenEntry(n))
    out.push(...flattenScreenEntries(n.children))
  }
  return out
}

/**
 * 嵌套栈聚合（§3.3）：tab 根屏（meta.isTab）→ 子屏名单（该 tab 的栈）
 *
 * 产物形态：`{ home: ['home', 'home-profile'] }`——tab 根自己 + 其 children 链。
 * 非 tab 根不产条目（普通 push 栈由运行时按 navigate 驱动，无需预声明）。
 */
export function tabStacks(nodes: RouteNode[]): Record<string, string[]> {
  const out: Record<string, string[]> = {}
  const collect = (n: RouteNode): string[] => {
    const name = n.name ?? n.path.replace(/^\//, '').replace(/\//g, '-')
    return [name, ...n.children.flatMap(collect)]
  }
  for (const n of nodes) {
    const name = n.name ?? n.path.replace(/^\//, '').replace(/\//g, '-')
    if (n.meta.isTab === true) out[name] = collect(n)
  }
  return out
}

/**
 * 生成屏注册表源码（navigation.generated.ts 形态）
 *
 * 产物头标注来源（决策链反查入口）；`screens` 直接可传 `createAppStack({ screens })`。
 * lazy 节点生成 `() => import()` 工厂（App 端代码分割等价物）；组件字段与路径同为单一来源。
 */
export function generateAppScreens(nodes: RouteNode[]): string {
  const entries = flattenScreenEntries(nodes)
  const body = entries
    .map((e) => {
      const lines = [
        `  ${JSON.stringify(e.name)}: {`,
        `    name: ${JSON.stringify(e.name)},`,
        `    path: ${JSON.stringify(e.path)},`,
        `    component: () => import(${JSON.stringify(e.componentPath)}),`,
        e.transition ? `    transition: ${JSON.stringify(e.transition)},` : '',
        `    children: ${JSON.stringify(e.children)},`,
        e.isTab ? `    isTab: true,` : '',
        e.budgetNodes ? `    budgetNodes: ${e.budgetNodes},` : '',
        `  },`,
      ]
      return lines.filter(Boolean).join('\n')
    })
    .join('\n')

  const stacks = tabStacks(nodes)
  const stacksCode =
    Object.keys(stacks).length > 0
      ? [
          '',
          '/** tab 嵌套栈聚合（§3.3：tab 里每个 tab 各有一个栈） */',
          `export const tabStacks = ${JSON.stringify(stacks, null, 2)}`,
          '',
        ].join('\n')
      : ''

  return [
    '// AUTO-GENERATED by @proteus-vue/router codegen/app（docs/proteus-router-plan M5）。DO NOT EDIT.',
    '// 来源：<route> 块（scan/tree 管线，含 loc 可反查源码）',
    '// ★屏注册表：屏 = 树内子树（虚拟栈；无系统导航栈）——createAppStack({ screens }) 消费；',
    '//   转场枚举原样携带，由运行时经 Morpheus（appTransition）换成转场规格。',
    '',
    'export const screens = {',
    body,
    '}',
    stacksCode,
  ].join('\n')
}
