// packages/router/src/codegen/web.ts
// M3 — Web 端 codegen（docs/proteus-router-plan 03）：RouteNode[] → vue-router 4 RouteRecordRaw 代码
// 输出 routes.generated.ts 形态：lazy → () => import() 代码分割；children 递归（vue-router 原生嵌套）
// ★透明化：输入为 scan/tree 的 RouteNode（含 loc/决策链），产物可反查源码
// ★逗号约定：record 每行自带尾逗号 + join('\n')；数组元素间用 join(',\n')——避免双逗号
import type { RouteNode } from '../types'
import { webTransitionName } from '../transforms/transform-transition'

/** 单节点 → vue-router record 代码（递归 children） */
function nodeToRecord(node: RouteNode, indent: string): string {
  const pad = (s: string): string => s.split('\n').join(`\n${indent}`)
  const comp = node.lazy
    ? `() => import(${JSON.stringify(node.componentPath)})`
    : `defineAsyncComponent(() => import(${JSON.stringify(node.componentPath)}))`
  // meta.transition 交给 <RouterTransition> 包裹组件消费（不直接映射进 vue-router meta）
  const meta = { ...node.meta }
  delete meta.transition
  const childrenBody = node.children.length > 0
    ? `\n${node.children.map((c) => nodeToRecord(c, `${indent}    `)).join(',\n')}\n${indent}  `
    : ''
  const lines = [
    `${indent}{`,
    `${indent}  path: ${JSON.stringify(node.path)},`,
    node.name ? `${indent}  name: ${JSON.stringify(node.name)},` : '',
    node.redirect ? `${indent}  redirect: ${JSON.stringify(node.redirect)},` : '',
    `${indent}  component: ${pad(comp)},`,
    Object.keys(meta).length > 0 ? `${indent}  meta: ${pad(JSON.stringify(meta))},` : '',
    node.children.length > 0 ? `${indent}  children: [${childrenBody}],` : '',
    `${indent}}`,
  ]
  return lines.filter(Boolean).join('\n')
}

/**
 * 生成 vue-router 路由表代码（routes.generated.ts 形态）
 * 产物头标注来源（决策链反查入口），transition 映射注释说明 Web 端消费方式
 */
export function generateWebRoutes(nodes: RouteNode[]): string {
  const records = nodes.map((n) => nodeToRecord(n, '  ')).join(',\n')
  return [
    '// AUTO-GENERATED by @proteus-vue/router codegen/web（docs/proteus-router-plan M3）。DO NOT EDIT.',
    '// 来源：<route> 块（scan/tree 管线，含 loc 可反查源码）；meta.transition 由 <RouterTransition> 消费',
    "import { defineAsyncComponent } from 'vue'",
    '',
    'export const routes = [',
    records,
    ']',
    '',
  ].join('\n')
}

/** Web 转场名（RouterView/应用壳消费；对齐共享映射表） */
export { webTransitionName }
