// src/compiler/transforms/script.ts
// script 阶段编译规则注册表 —— 每条规则一份 AI 说明书
import type { TransformRule } from './types'

export const SCRIPT_RULES: TransformRule[] = [
  {
    id: 'script/const-to-data',
    phase: 'script',
    status: 'implemented',
    title: '顶层 const（ref/reactive/字面量）→ data',
    titleEn: 'Top-level const (ref/reactive/literal) → data',
    description: '零缩进顶层 const → data 字段；ref(0)/reactive({...})/字面量在构建期静态求值，多行数组/对象字面量完整提取',
    descriptionEn: 'Zero-indent top-level const → data field; ref(0)/reactive({...})/literals are statically evaluated at build time, and multiline array/object literals are fully extracted',
    why: '小程序页面状态在 data 中，响应式声明（ref/reactive）编译期为初始值求值（决策 #60：括号平衡扫描支持多行字面量；只提取零缩进顶层 const，不误取函数体内局部 const）',
    whyEn: 'Mini program page state lives in data; reactive declarations (ref/reactive) are evaluated to their initial values at compile time (decision #60: parenthesis-balanced scanning supports multiline literals; only zero-indent top-level const is extracted, so local consts inside function bodies are not picked up)',
    when: 'script 顶层出现 const 声明且初始值为字面量/ref/reactive/shallowRef/readonly 时',
    example: {
      before: 'const count = ref(0)\nconst cards = ref([{ title: "a" }])',
      after: 'data: {\n  count: 0,\n  cards: [{ "title": "a" }],\n}',
    },
    verify: 'tests/mp-transform.test.ts data 提取用例；golden fixture showcase.js（多行数组）',
    source: 'packages/compiler/src/script.ts → extractData + extractInitializer',
    decision: '#60 / #22',
  },
  {
    id: 'script/computed-to-data',
    phase: 'script',
    status: 'implemented',
    title: 'computed 读路径 → data 派生字段（v0.3）',
    titleEn: 'computed read path → derived data field (v0.3)',
    description: '顶层 const x = computed(() => expr) → data 不存；onLoad 初始化 + 依赖 ref 写入 setData 时同步重算（expr 中 x.value → this.data.x）',
    descriptionEn: 'Top-level const x = computed(() => expr) → not stored in data: initialized in onLoad and recomputed synchronously when a dependency ref is written to setData (x.value within expr → this.data.x)',
    why: '小程序无 computed 概念，编译期把 getter 转 data 派生：静态提取 getter 中的 ref 依赖 → 依赖写入时把重算表达式合并进同一 setData（v0.3 先做读路径，watch/写路径后续）',
    whyEn: 'Mini programs have no computed concept, so the compiler turns the getter into a data derivation: the ref dependencies in the getter are statically extracted, and when a dependency is written the recompute expression is merged into the same setData (v0.3 implements the read path first; watch/write paths come later)',
    when: 'script 顶层出现 computed(() => 表达式)（仅支持箭头简写 + 表达式体；块体/function 形式编译期警告）',
    example: {
      before: 'const double = computed(() => count.value * 2)',
      after: 'data 不含 double；this.setData({ count: ..., double: this.data.count * 2 })（count 写入时合并，onLoad 初始化一次）',
    },
    verify: 'tests/mp-transform.test.ts computed 用例',
    source: 'packages/compiler/src/script.ts → extractComputedFromInit + computedPatch + computedInitLine',
    decision: '#76（v0.3）',
  },
  {
    id: 'script/watch-to-methods',
    phase: 'script',
    status: 'implemented',
    title: 'watch → proteusWatchX 方法（v0.3）',
    titleEn: 'watch → proteusWatchX method (v0.3)',
    description: 'watch(ref, (newVal, oldVal) => { body }) → methods 生成 proteusWatchX；依赖 ref 写入 setData 后自动调用（旧值在写入前保存）；immediate: true → onLoad 初始化调用一次',
    descriptionEn: 'watch(ref, (newVal, oldVal) => { body }) → generates proteusWatchX in methods; automatically invoked after the dependency ref is written to setData (the old value is saved before the write); immediate: true → invoked once during onLoad initialization',
    why: '小程序无 watch 概念，编译期模拟：依赖静态提取（单 ref）+ 写入点联动（setData 后调用回调，newVal/oldVal 由编译期保存）；MVP：仅单 ref 直接引用 + 箭头函数回调（数组源/函数源/function 回调警告）',
    whyEn: 'Mini programs have no watch concept, so the compiler simulates it: static dependency extraction (single ref) + write-point linkage (the callback runs after setData, with newVal/oldVal saved by the compiler); MVP: direct single-ref references + arrow-function callbacks only (array sources/function sources/function callbacks warn)',
    when: 'script 顶层出现 watch(refName, callback) 时',
    example: {
      before: 'watch(count, (n, o) => {\n  log(n, o)\n})',
      after: 'proteusWatchCount(n, o) {\n  log(n, o)\n},\n// count 写入：const oldCount = this.data.count; ...setData(...); this.proteusWatchCount(this.data.count, oldCount)',
    },
    verify: 'tests/mp-transform.test.ts watch 用例',
    source: 'packages/compiler/src/script.ts → extractWatch + watchTail + immediateWatchLine',
    decision: '#78（v0.3）',
  },
  {
    id: 'script/watch-props',
    phase: 'script',
    status: 'implemented',
    title: 'watch props 源 → WeChat observers（组件属性监听）',
    titleEn: 'watch props source → WeChat observers (component property listening)',
    description: 'watch(props.x, (n, o) => { body }) 或 watch(() => props.x, ...) → Component observers: { x(n, o) { body } }（属性变化触发回调；Web 端即标准 Vue watch，全响应式）；immediate: true → 另生成 proteusWatchPropX 方法 + attached 初始化调用一次',
    descriptionEn: 'watch(props.x, (n, o) => { body }) or watch(() => props.x, ...) → Component observers: { x(n, o) { body } } (a property change triggers the callback; on the Web it is a standard Vue watch, fully reactive); immediate: true → additionally generates a proteusWatchPropX method invoked once during attached initialization',
    why: '组件需要响应自身属性变化（列表 items 分页/加载更多、弹层 visible v-model、表单 value 同步等）；小程序无响应式系统，属性变化唯一通道是 observers',
    whyEn: 'Components must react to their own property changes (list items pagination/load-more, overlay visible v-model, form value sync, etc.); mini programs have no reactive system, so observers are the only channel for property changes',
    when: '组件 script 顶层出现 watch(props.x, callback) / watch(() => props.x, callback) 时（MVP：单属性源）',
    example: {
      before: 'watch(() => props.items, () => {\n  calc()\n})',
      after: 'observers: {\n  items(n, o) {\n    calc()\n  },\n}',
    },
    verify: 'tests/mp-transform.test.ts props 源 watch 用例',
    source: 'packages/compiler/src/script.ts → extractWatch（propField 分支）+ observers 发射',
    decision: '组件库 B3（p-list-view items 响应式）',
  },
  {
    id: 'script/module-import',
    phase: 'script',
    status: 'implemented',
    title: '跨模块引用：import → require 转换（module-plan B0）/ 剥离警告',
    titleEn: 'Cross-module reference: import → require conversion (module-plan B0) / stripping warning',
    description: 'setup 顶层 import：相对路径共享模块（moduleImports 命中）→ 产物顶部 const { x } = require("<相对产物路径>.js")（named/default/namespace/side 四形态）；vue/@proteus-vue/*/type/.vue 跳过（编译器静态/usingComponents/纯类型）；无法解析的路径 → 剥离 + 警告',
    descriptionEn: 'Top-level setup imports: relative-path shared modules (matched by moduleImports) are hoisted to the top of the output as `const { x } = require(...)` with the compiled relative module path appended (named/default/namespace/side, four forms); vue/@proteus-vue/*/type/.vue are skipped (compiler-static/usingComponents/pure types); unresolvable paths are stripped with a warning',
    why: '反黑盒（vue-compat Batch A，决策 #116）：import 剥离不再静默，产物未定义引用显式提示；★module-plan B0：相对路径共享模块编译为独立产物 + require 转换，跨模块引用真正可用（后续 Pinia/API/Component 基建的地基）',
    whyEn: 'Anti-black-box (vue-compat Batch A, decision #116): import stripping is no longer silent, and undefined references in the output are explicitly flagged; ★module-plan B0: relative-path shared modules are compiled into standalone outputs with require conversion, making cross-module references actually usable (the foundation for the later Pinia/API/Component infrastructure)',
    when: '<script setup> 顶层出现 import 语句',
    example: { before: 'import { formatTime } from "../utils/format"', after: 'const { formatTime } = require("../utils/format.js")（moduleImports 命中）；未收录路径 → 警告 + 剥离' },
    verify: 'tests/module-import.test.ts B0 用例 + tests/vue-compat.test.ts import 用例',
    source: 'packages/compiler/src/script.ts → extractImports + transformScriptToPage（require 生成）',
    decision: '#116',
  },
  {
    id: 'script/runtime-init',
    phase: 'script',
    status: 'implemented',
    title: '函数调用初始化 → 运行时初始化实例属性（module-plan B0）',
    titleEn: 'Function-call initialization → runtime-initialized instance property (module-plan B0)',
    description: '顶层 const x = fn()（静态求值失败）→ data 不含该字段；onLoad/attached 注入 this.x = fn()（实例属性，ES5 安全）；模板绑定不支持（读 this.data.x undefined）——共享逻辑请用模块 import',
    descriptionEn: 'Top-level const x = fn() (static evaluation failed) → data does not contain the field; onLoad/attached injects this.x = fn() (instance property, ES5-safe); template binding is unsupported (reading this.data.x is undefined) — use module import for shared logic',
    why: '旧行为：函数调用初始化静态求值失败 → data.x = undefined 且调用丢失（静默坏）；B0 配合跨模块 require 让 useStore()/createX() 真实执行',
    whyEn: 'Old behavior: when static evaluation of a function-call initializer failed, data.x became undefined and the call was silently dropped; with cross-module require, B0 makes useStore()/createX() actually execute',
    when: '顶层 const 初始值为函数调用且无法静态求值（非 inject/ref/computed）',
    example: { before: 'const store = usePlayerStore()', after: 'onLoad: this.store = usePlayerStore()（data 不含 store）' },
    verify: 'tests/module-import.test.ts + tests/vue-compat.test.ts 运行时初始化用例',
    source: 'packages/compiler/src/script.ts → extractData（runtimeInits）+ runtimeInitLine',
    decision: '#116',
  },
  {
    id: 'script/store-binding',
    phase: 'script',
    status: 'implemented',
    title: 'Pinia store 模板绑定（pinia-plan 12 P1：$subscribe → setData 同步）',
    titleEn: 'Pinia store template binding (pinia-plan 12 P1: $subscribe → setData sync)',
    description: '模板 {{ store.<field> }} 引用（template 收集 storeBindings）→ onLoad 注入：初始 setData({ field: this.store.field }) + store.$subscribe 订阅（变更 → setData，模板字段实时同步）；store 变量 = useXxxStore() 的 runtimeInit 实例属性；嵌套 store.current.title → current.title（store 前缀剥离）',
    descriptionEn: 'Template {{ store.<field> }} references (storeBindings collected in template) → onLoad injection: initial setData({ field: this.store.field }) + store.$subscribe subscription (changes → setData, template fields sync in real time); the store variable is the runtimeInit instance property of useXxxStore(); nested store.current.title → current.title (store prefix stripped)',
    why: 'MP 模板绑定读 this.data——store 是实例属性读不到；Pinia $subscribe 订阅 + setData 同步（对齐 store 桥 connectPageStore 模式），让 pinia-demo MP 端状态显示可用（pinia-plan 12）',
    whyEn: 'MP template bindings read this.data, and a store instance property is unreachable from there; Pinia $subscribe subscription + setData sync (aligned with the connectPageStore store-bridge pattern) makes state display work on the pinia-demo MP side (pinia-plan 12)',
    when: '模板出现 store.<field> 引用且 script 有 const store = useXxxStore()',
    example: { before: '{{ store.current.title }}', after: '{{ current.title }} + onLoad: this.store.$subscribe(() => this.setData({ current: this.store.current }))' },
    verify: 'tests/pinia-mp-compile.test.ts（P1 用例）',
    source: 'packages/compiler/src/template.ts（rewriteStoreRefs）+ script.ts（storeBindingLine）',
    decision: '#116',
  },
  {
    id: 'script/define-props',
    phase: 'script',
    status: 'implemented',
    title: 'defineProps → Component properties（v0.3 组件系统 + v0.3 尾泛型）',
    titleEn: 'defineProps → Component properties (v0.3 component system + v0.3 trailing generics)',
    description: '组件模式：defineProps({ label: String, initial: { type: Number, default: 0 } }) 或 TS 泛型 defineProps<{ label: string; count?: number }>() → properties（type + 默认值 value）；props.xxx 访问重写为 this.data.xxx',
    descriptionEn: 'Component mode: defineProps({ label: String, initial: { type: Number, default: 0 } }) or TS-generic defineProps<{ label: string; count?: number }>() → properties (type + default value); props.xxx accesses are rewritten to this.data.xxx',
    why: '小程序组件用 Component({ properties }) 声明外部属性；Vue 组件 props 编译期映射（v0.3，决策 #79）；对象形式（type/default）+ TS 泛型形式（string/number/boolean/object/Array/联合映射）',
    whyEn: 'Mini program components declare external properties with Component({ properties }); Vue component props are mapped at compile time (v0.3, decision #79); object form (type/default) + TS generic form (string/number/boolean/object/Array/union mapping)',
    when: '组件文件（isComponent）含 defineProps 时',
    example: { before: 'const props = defineProps<{ initial: number; label: string }>()', after: 'properties: {\n  initial: { type: Number, value: 0 },\n  label: { type: String, value: "" },\n}' },
    verify: 'tests/mp-transform.test.ts 组件系统用例',
    source: 'packages/compiler/src/script.ts → extractProps + mapTsType',
    decision: '#79 / #91（v0.3 尾泛型）',
  },
  {
    id: 'script/define-emits',
    phase: 'script',
    status: 'implemented',
    title: 'defineEmits + emit() → triggerEvent（v0.3 组件系统）',
    titleEn: 'defineEmits + emit() → triggerEvent (v0.3 component system)',
    description: '组件模式：emit("xxx", payload) → this.triggerEvent("xxx", payload)；父组件 @xxx（非 EVENT_MAP）→ bind:xxx',
    descriptionEn: 'Component mode: emit("xxx", payload) → this.triggerEvent("xxx", payload); parent @xxx (not in EVENT_MAP) → bind:xxx',
    why: '小程序组件向父组件通信用 triggerEvent；Vue emit 编译期映射（v0.3，决策 #79）；MVP：约定 emit 变量名',
    whyEn: 'Mini program components use triggerEvent to communicate with the parent; Vue emit is mapped at compile time (v0.3, decision #79); MVP: the emit variable name follows a convention',
    when: '组件文件含 defineEmits 声明且方法体调用 emit(...) 时',
    example: { before: 'emit(\'change\', count.value)', after: 'this.triggerEvent(\'change\', this.data.count)' },
    verify: 'tests/mp-transform.test.ts 组件系统用例',
    source: 'packages/compiler/src/script.ts → rewriteRefAccess（emit 重写）+ template.ts（bind: 冒号形式）',
    decision: '#79（v0.3 组件系统）',
  },
  {
    id: 'script/define-expose',
    phase: 'script',
    status: 'implemented',
    title: 'defineExpose → no-op + 校验（v0.3 尾）',
    titleEn: 'defineExpose → no-op + validation (v0.3 wrap-up)',
    description: '组件模式：defineExpose({ ... }) 编译期 no-op——小程序组件 methods 天然可被 selectComponent 访问；校验声明成员：ref 值暴露无对等机制 → 警告',
    descriptionEn: 'Component mode: defineExpose({ ... }) is a compile-time no-op — mini program component methods are natively accessible via selectComponent; declared members are validated: exposing a ref value has no equivalent mechanism → warning',
    why: '小程序组件外部访问（selectComponent + 方法调用）天然覆盖 Vue 的 defineExpose 方法暴露语义；ref 值暴露需方法包装（v0.3 尾，决策 #91）',
    whyEn: 'External access to mini program components (selectComponent + method calls) natively covers the method-exposure semantics of Vue defineExpose; exposing a ref value would require method wrapping (v0.3 wrap-up, decision #91)',
    when: '组件文件含 defineExpose 时',
    example: { before: 'defineExpose({ reset })', after: 'no-op（reset 已在 methods，外部 selectComponent 可调）' },
    verify: 'tests/mp-transform.test.ts defineExpose 用例',
    source: 'packages/compiler/src/script.ts → checkDefineExpose',
    decision: '#91（v0.3 尾组件收尾）',
  },
  {
    id: 'script/function-to-methods',
    phase: 'script',
    status: 'implemented',
    title: '顶层 function 声明 → methods',
    titleEn: 'Top-level function declarations → methods',
    description: '顶层 function handleTap() {...} → methods 中的对象简写 handleTap() {...}',
    descriptionEn: 'Top-level function handleTap() {...} → object shorthand handleTap() {...} in methods',
    why: '小程序页面逻辑在 methods 中；对象字面量内不能输出裸 function 声明（决策 #14：产物方法用对象简写）',
    whyEn: 'Mini program page logic lives in methods; bare function declarations cannot be emitted inside an object literal (decision #14: output methods use object shorthand)',
    when: 'script 顶层出现 function 声明时',
    example: {
      before: 'function handleTap() {\n  count.value++\n}',
      after: 'handleTap() {\n  this.setData({ count: (this.data.count === undefined || this.data.count === null ? 0 : this.data.count) + 1 })\n},',
    },
    verify: 'tests/mp-transform.test.ts methods 提取用例',
    source: 'src/compiler/script.ts → extractMethods',
    decision: '#14',
  },
  {
    id: 'script/arrow-to-methods',
    phase: 'script',
    status: 'implemented',
    title: 'const 箭头函数 → methods',
    titleEn: 'Const arrow functions → methods',
    description: 'const fn = (params) => {...} → methods 中的 fn(params) {...}（支持 async）',
    descriptionEn: 'const fn = (params) => {...} → fn(params) {...} in methods (async supported)',
    why: '小程序页面逻辑在 methods 中；const 箭头函数同样提取为方法',
    whyEn: 'Mini program page logic lives in methods; const arrow functions are extracted as methods the same way',
    when: 'script 顶层出现 const 箭头函数（含 async）时',
    example: {
      before: 'const load = async () => {\n  const r = await fetchData()\n}',
      after: 'load() {\n  const r = await fetchData()\n},',
    },
    verify: 'tests/mp-transform.test.ts methods 提取用例',
    source: 'src/compiler/script.ts → extractMethods（arrowRe 分支）',
  },
  {
    id: 'script/lifecycle-map',
    phase: 'script',
    status: 'implemented',
    title: '生命周期映射 onMounted → onReady / onUnmounted → onUnload',
    titleEn: 'Lifecycle mapping: onMounted → onReady / onUnmounted → onUnload',
    description: 'onMounted(() => {...}) → onReady() {...}；onUnmounted → onUnload；onLoad 透传',
    descriptionEn: 'onMounted(() => {...}) → onReady() {...}; onUnmounted → onUnload; onLoad is passed through',
    why: 'Vue 组件生命周期与小程序页面生命周期不同名，编译期映射到小程序钩子',
    whyEn: 'Vue component lifecycles and mini program page lifecycles have different names, so the compiler maps them onto mini program hooks',
    when: 'script 出现 onMounted / onUnmounted / onLoad 调用时',
    example: { before: 'onMounted(() => { doInit() })', after: 'onReady() {\n  doInit()\n},' },
    verify: 'tests/runtime.test.ts + mp-transform.test.ts 生命周期用例',
    source: 'src/compiler/script.ts → extractLifecycles',
  },
  {
    id: 'script/ref-read',
    phase: 'script',
    status: 'implemented',
    title: '方法内 ref 读取 → this.data.name',
    titleEn: 'In-method ref reads → this.data.name',
    description: '方法/生命周期体内的 name.value 读取 → this.data.name',
    descriptionEn: 'name.value reads in method/lifecycle hook bodies → this.data.name',
    why: '小程序运行期状态在 this.data 中，编译期把 setup ref 访问重写为 data 访问（决策 #22）',
    whyEn: 'Mini program runtime state lives in this.data, so the compiler rewrites setup ref accesses into data accesses (decision #22)',
    when: '方法或生命周期体内出现 ref.value 读取时',
    example: { before: 'const v = count.value', after: 'const v = this.data.count' },
    verify: 'tests/mp-transform.test.ts ref 重写用例',
    source: 'src/compiler/script.ts → rewriteRefAccess',
    decision: '#22',
  },
  {
    id: 'script/ref-write',
    phase: 'script',
    status: 'implemented',
    title: '方法内 ref 赋值 → this.setData',
    titleEn: 'In-method ref assignment → this.setData',
    description: '方法/生命周期体内的 name.value = expr → this.setData({ name: expr })',
    descriptionEn: 'name.value = expr in method/lifecycle hook bodies → this.setData({ name: expr })',
    why: '小程序更新视图的唯一通道是 setData，编译期把赋值重写为 setData 调用（决策 #22；排除 ==/===/复合赋值）',
    whyEn: 'setData is the only channel for updating the view in mini programs, so the compiler rewrites assignments into setData calls (decision #22; ==/===/compound assignments are excluded)',
    when: '方法或生命周期体内出现 name.value = expr 时',
    example: { before: 'count.value = count.value + 1', after: 'this.setData({ count: this.data.count + 1 })' },
    verify: 'tests/mp-transform.test.ts ref 重写用例',
    source: 'src/compiler/script.ts → rewriteRefAccess',
    decision: '#22',
  },
  {
    id: 'script/ref-incdec',
    phase: 'script',
    status: 'implemented',
    title: '方法内 ref 自增/自减 → this.setData',
    titleEn: 'In-method ref increment/decrement → this.setData',
    description: 'name.value++ / -- / ++name.value → this.setData({ name: (null 检查 ? 0 : this.data.name) + 1 })',
    descriptionEn: 'name.value++ / -- / ++name.value → this.setData({ name: (null check ? 0 : this.data.name) + 1 })',
    why: '自增/自减无表达式可提取，编译期为显式 setData 并做 null 兜底（决策 #22；不用 ?? 运算符——真机预览报 SyntaxError，决策 #36）',
    whyEn: 'Increment/decrement leaves no expression to extract, so the compiler emits an explicit setData with a null fallback (decision #22; the ?? operator is avoided — real-device preview throws SyntaxError, decision #36)',
    when: '方法或生命周期体内出现 name.value 的自增/自减时',
    example: {
      before: 'count.value++',
      after: 'this.setData({ count: (this.data.count === undefined || this.data.count === null ? 0 : this.data.count) + 1 })',
    },
    verify: 'tests/mp-transform.test.ts ref 重写用例；Web E2E tap 计数用例',
    source: 'src/compiler/script.ts → rewriteRefAccess + numOrZero',
    decision: '#22 / #36',
  },
  {
    id: 'script/vmodel-handler',
    phase: 'script',
    status: 'implemented',
    title: 'v-model 自动 handler 注入',
    titleEn: 'Automatic v-model handler injection',
    description: '模板出现 v-model="x" 时注入 proteusOnXInput(e) { this.setData({ x: e.detail.value }) }',
    descriptionEn: 'When v-model="x" appears in the template, inject proteusOnXInput(e) { this.setData({ x: e.detail.value }) }',
    why: '小程序无 v-model，回写方向由自动 handler 承担（决策 #29：方法名避免 __ 前缀，微信保留 _ 前缀可能导致绑定失效）',
    whyEn: 'Mini programs have no v-model; the auto-generated handler covers the write-back direction (decision #29: method names avoid the __ prefix, since WeChat reserves the _ prefix and bindings may break)',
    when: 'template 转换返回的 vModelBindings 非空时',
    example: {
      before: '（模板）<input v-model="name" />',
      after: 'proteusOnNameInput(e) { this.setData({ name: e.detail.value }) },',
    },
    verify: 'tests/mp-transform.test.ts v-model 用例',
    source: 'src/compiler/script.ts → transformScriptToPage（vModelBindings 循环）',
    decision: '#29',
  },
  {
    id: 'script/nav-handler',
    phase: 'script',
    status: 'implemented',
    title: '导航链接自动 handler 注入（proteusNavigateTo）',
    titleEn: 'Navigation-link auto handler injection (proteusNavigateTo)',
    description: '模板出现导航链接时注入 proteusNavigateTo(e)：读 data-url → wx.navigateTo（routeType 透传，fail 降级普通跳转）',
    descriptionEn: 'When a navigation link appears in the template, inject proteusNavigateTo(e): read data-url → wx.navigateTo (routeType is passed through; fail falls back to a normal navigation)',
    why: '小程序导航统一走 wx.navigateTo；保留前导 / 为绝对路径（决策 #30 真机根因）；fail 降级保证自定义路由失败仍可跳转（#28）；方法名避开 __ 前缀（#29）',
    whyEn: 'Mini program navigation uniformly goes through wx.navigateTo; a leading / is kept as an absolute path (decision #30, real-device root cause); the fail fallback keeps navigation working when a custom route fails (#28); method names avoid the __ prefix (#29)',
    when: 'template 转换返回 usesNavigate=true 时',
    example: {
      before: '（模板）<a href="/pages/user/index">用户</a>',
      after: 'proteusNavigateTo(e) {\n  const ds = e.currentTarget.dataset\n  const url = String(ds.url || "")\n  if (!url) return\n  const nav = { url: url, fail: ... }\n  if (ds.routeType) nav.routeType = ds.routeType\n  wx.navigateTo(nav)\n},',
    },
    verify: 'tests/mp-transform.test.ts 导航链接用例；真机验证归档 #30',
    source: 'src/compiler/script.ts → transformScriptToPage（usesNavigate 分支）',
    decision: '#24 / #28 / #29 / #30',
  },
  {
    id: 'page/scroll-bridge',
    phase: 'script',
    status: 'implemented',
    title: '页面滚动 API 桥接（15-page-scroll-container：Skyline 页面不滚动，页面钩子靠 scroll-view 事件触发）',
    titleEn: 'Page scroll API bridging (15-page-scroll-container: Skyline pages do not scroll; page hooks fire through scroll-view events)',
    description: '页面声明 onPageScroll/onReachBottom/onPullDownRefresh 时：自动包装 scroll-view 绑定对应事件（template 侧）+ 生成桥接方法（载荷归一：scroll-view e.detail.scrollTop → onPageScroll { scrollTop }）；手动 scroll-view 场景编译期歧义警告',
    descriptionEn: 'When the page declares onPageScroll/onReachBottom/onPullDownRefresh: automatically wrap scroll-view to bind the corresponding events (template side) and generate a bridge method (payload normalization: scroll-view e.detail.scrollTop → onPageScroll { scrollTop }); manual scroll-view scenarios raise a compile-time ambiguity warning',
    why: 'Skyline 页面本身不滚动（滚动必须 scroll-view）——页面级滚动钩子不会被触发；桥接后 onPageScroll/onReachBottom/onPullDownRefresh 语义保留（与 Web 端一致）',
    whyEn: 'Skyline pages themselves do not scroll (scrolling requires scroll-view), so page-level scroll hooks would never fire; after bridging, the semantics of onPageScroll/onReachBottom/onPullDownRefresh are preserved (consistent with the Web side)',
    when: '页面（非组件）模式 + 声明滚动生命周期 + 自动包滚动容器（rules.disabled 可关）',
    example: { before: 'function onPageScroll(e) { … }', after: '自动包装 scroll-view bindscroll="proteusPageScroll" + proteusPageScroll(e) 载荷归一调用 onPageScroll' },
    verify: 'tests/mp-transform.test.ts 页面滚动桥接用例',
    source: 'packages/compiler/src/{template,script}.ts（pageScrollHooks + proteusPageScroll 等）',
    decision: '2026-08 真机实测（15-page-scroll-container）',
  },
  {
    id: 'script/onload-params',
    phase: 'script',
    status: 'implemented',
    title: '默认 onLoad 参数自动 decode',
    titleEn: 'Automatic decoding of default onLoad parameters',
    description: '无显式 onLoad 时注入默认实现：遍历 options → decodeURIComponent → 结构化值（{/[ 开头）JSON.parse → setData',
    descriptionEn: 'With no explicit onLoad, inject the default implementation: iterate options → decodeURIComponent → JSON.parse structured values (starting with {/[) → setData',
    why: '路由参数经 query 传递，页面需还原为原始类型（决策 #19：仅对结构化值 JSON.parse，普通标量保持字符串——对齐 P3 契约 options.id === "1"）',
    whyEn: 'Route params are passed through the query string, so the page must restore their original types (decision #19: JSON.parse only for structured values; plain scalars stay strings — aligned with the P3 contract options.id === "1")',
    when: 'script 无显式 onLoad 时（有显式 onLoad 则透传）',
    example: {
      before: '（无 onLoad）',
      after: 'onLoad(options) {\n  const params = {}\n  const keys = Object.keys(options || {})\n  for (let i = 0; i < keys.length; i++) {\n    ...\n  }\n  this.setData(params)\n},',
    },
    verify: 'tests/runtime.test.ts 参数 decode 用例',
    source: 'src/compiler/script.ts → transformScriptToPage（onLoad 分支）',
    decision: '#19 / #32（ES5 安全：索引循环 Object.keys）',
  },
  {
    id: 'script/component-mode',
    phase: 'script',
    status: 'implemented',
    title: '组件模式 → Component() 构造器',
    titleEn: 'Component mode → Component() constructor',
    description: 'isComponent=true（components 目录下）→ Component({ data, methods, ... })，页面 → Page({ ... })',
    descriptionEn: 'isComponent=true (under the components/ directory) → Component({ data, methods, ... }); a page → Page({ ... })',
    why: '小程序页面用 Page()，组件用 Component()（不同构造器形态，isComponent 分支已在 compiler/index.ts 透传）',
    whyEn: 'Mini program pages use Page() and components use Component() (different constructor shapes; the isComponent branch is already passed through in compiler/index.ts)',
    when: '文件路径包含 components/ 目录时',
    example: { before: '（组件 SFC）', after: 'Component({ data: {...}, ... })' },
    verify: 'tests/mp-transform.test.ts 组件形态用例',
    source: 'src/compiler/script.ts → transformScriptToPage（isComponent 分支）',
  },
  {
    id: 'script/es5-safe',
    phase: 'script',
    status: 'implemented',
    title: '生成代码 ES5 安全',
    titleEn: 'Generated code is ES5-safe',
    description: '产物规避 ?? / ?. / 数组解构 / 对象展开（显式 null 检查三元、索引循环 Object.keys、直接属性赋值）',
    descriptionEn: 'Generated output avoids ?? / ?. / array destructuring / object spread (explicit null-check ternaries, index loops over Object.keys, direct property assignment)',
    why: '微信开发者工具将页面 JS 转 ES5 时依赖 babel helper 模块，helper 不在包内会报错（#32：arrayWithHoles 未定义）；真机预览直接报 ?? 语法错误（#36）',
    whyEn: 'When WeChat DevTools transpiles page JS to ES5 it depends on babel helper modules, and a helper missing from the package causes an error (#32: arrayWithHoles is undefined); real-device preview reports a direct ?? syntax error (#36)',
    when: '所有生成的 JS 产物（方法体 / onLoad / 自动 handler）',
    example: {
      before: '// 禁止出现在产物中\nconst [a, b] = arr\nconst v = x ?? 0',
      after: '// 产物实际形态\nconst a = arr[0], b = arr[1]\nconst v = (x === undefined || x === null ? 0 : x)',
    },
    verify: 'grep 扫描产物零残留（决策 #36 验证方式）',
    source: 'src/compiler/script.ts 各处（numOrZero / onLoad 实现 / nav handler）',
    decision: '#32 / #36',
  },
  {
    id: 'script/provide-inject',
    phase: 'script',
    status: 'implemented',
    title: 'provide/inject → getApp().__proteusProvides 全局注册表桥（vue-compat-advance Batch 3/4）',
    titleEn: 'provide/inject → getApp().__proteusProvides global registry bridge (vue-compat-advance Batch 3/4)',
    description: '顶层 provide("key", expr) / const x = inject("key"[, default]) 编译为注册表读写：页面 onLoad 单函数合并块（pageId 命名空间解析一次 + provide 注册 + inject setData）；组件 provide 放 created（先于子组件 attached 注入）、inject 放 attached；provide 值表达式重写裸 ref 名 / ref.value → this.data.<name>；inject 支持默认值（undefined 时取默认）；★Batch 4 响应式联动：裸 ref 提供（provide("key", refName)）→ ref 写入点注入 proteusSyncProvide（同步注册表值 + 通知订阅者），inject 侧订阅 __subs[key]（值变化 setData 刷新）+ detached/onUnload 取消；★Batch 6 页面级隔离：注册表按 pageId 命名空间（页面 onLoad __seq 生成 + 组件 getCurrentPages 栈顶解析，onUnload 删除命名空间防泄漏）；.value/字面量提供保持静态快照（对齐 Vue 语义：传 ref 联动、传值快照）',
    descriptionEn: 'Top-level provide("key", expr) / const x = inject("key"[, default]) compile to registry reads and writes: pages use a single merged onLoad block (pageId namespace resolved once + provide registration + inject setData); component provide goes into created (before child components attach-inject), inject into attached; provide value expressions rewrite bare ref names / ref.value → this.data.<name>; inject supports default values (the default applies when undefined); ★Batch 4 reactive linkage: providing a bare ref (provide("key", refName)) → proteusSyncProvide is injected at ref write points (syncs the registry value + notifies subscribers), and the inject side subscribes to __subs[key] (setData refresh on value change) with cancellation on detached/onUnload; ★Batch 6 page-level isolation: the registry is namespaced per pageId (pages generate __seq in onLoad + components resolve via the top of the getCurrentPages stack; onUnload deletes the namespace to prevent leaks); providing .value/literals keeps a static snapshot (aligned with Vue semantics: passing a ref links it, passing a value snapshots it)',
    why: '小程序组件树无 provide/inject 机制（决策 #117）：全局注册表桥让页面向组件传值（含深层嵌套组件）；MVP 值快照（非响应式联动）+ 全局注册表（重名 key 后写覆盖），页面级隔离/响应式为后续',
    whyEn: 'The mini program component tree has no provide/inject mechanism (decision #117): the global registry bridge lets a page pass values down to components (including deeply nested ones); MVP is value snapshots (no reactive linkage) + a global registry (duplicate keys are overwritten by the later write); page-level isolation/reactive linkage come later',
    when: 'script 顶层出现 provide("key", value) 调用或 const x = inject("key")（仅零缩进单行；provide 值支持字面量/裸 ref/ref.value）',
    example: {
      before: 'provide("user", userInfo)\nconst theme = inject("theme", "light")',
      after: 'onLoad: const provides = (getApp().__proteusProvides || (getApp().__proteusProvides = {})); provides["user"] = this.data.userInfo; if (!provides.__subs) provides.__subs = {}; ...; this.setData({ theme: (provides["theme"] === undefined ? "light" : provides["theme"]) })；userInfo 写入点追加 this.proteusSyncProvide("user", "userInfo")（通知订阅者 setData 刷新）',
    },
    verify: 'tests/vue-compat-advance.test.ts Batch 3/4 用例',
    source: 'packages/compiler/src/script.ts → extractProvideInject + buildProvideInject + rewriteRefAccess（写入点注入）+ transformScriptToPage（created/attached/onLoad 注入点 + proteusSyncProvide/proteusUnsubscribeProvide 生成）',
    decision: '#117',
  },
]
