// src/compiler/transforms/script.ts
// script 阶段编译规则注册表 —— 每条规则一份 AI 说明书
import type { TransformRule } from './types'

export const SCRIPT_RULES: TransformRule[] = [
  {
    id: 'script/const-to-data',
    phase: 'script',
    status: 'implemented',
    title: '顶层 const（ref/reactive/字面量）→ data',
    titleEn: 'Top-level const (ref/reactive/literal) → data',
    description: '零缩进顶层 const → data 字段；ref(0)/reactive({...})/字面量在构建期静态求值，多行数组/对象字面量完整提取',
    descriptionEn: 'Zero-indent top-level const → data field; ref(0)/reactive({...})/literals are statically evaluated at build time, and multiline array/object literals are fully extracted',
    why: '小程序页面状态在 data 中，响应式声明（ref/reactive）编译期为初始值求值（决策 #60：括号平衡扫描支持多行字面量；只提取零缩进顶层 const，不误取函数体内局部 const）',
    whyEn: 'Mini program page state lives in data; reactive declarations (ref/reactive) are evaluated to their initial values at compile time (decision #60: parenthesis-balanced scanning supports multiline literals; only zero-indent top-level const is extracted, so local consts inside function bodies are not picked up)',
    when: 'script 顶层出现 const 声明且初始值为字面量/ref/reactive/shallowRef/readonly 时',
    example: {
      before: 'const count = ref(0)\nconst cards = ref([{ title: "a" }])',
      after: 'data: {\n  count: 0,\n  cards: [{ "title": "a" }],\n}',
    },
    verify: 'tests/mp-transform.test.ts data 提取用例；golden fixture showcase.js（多行数组）',
    source: 'packages/compiler/src/script.ts → extractData + extractInitializer',
    decision: '#60 / #22',
  },
  {
    id: 'script/computed-to-data',
    phase: 'script',
    status: 'implemented',
    title: 'computed 读路径 → data 派生字段（v0.3；★#499 支持块体整段求值）',
    titleEn: 'computed read path → derived data field (v0.3; ★#499 adds whole-block evaluation)',
    description: '顶层 const x = computed(() => expr) → data 不存；组件 onReady / 页面 onLoad 初始化 + 依赖 ref 写入 setData 时同步重算（expr 中 x.value → this.data.x、props.x → this.data.x）；★#499 块体 computed（() => { 语句; return expr }）编译为 proteusCalcX() 整段求值方法（派生 expr = this.proteusCalcX()）——此前块体被忽略，依赖方引用悬空 ReferenceError；末语句非 return → 警告忽略',
    descriptionEn: 'Top-level const x = computed(() => expr) → not stored in data: initialized in component onReady / page onLoad and recomputed synchronously when a dependency ref is written to setData (x.value within expr → this.data.x, props.x → this.data.x); ★#499 block-bodied computed (() => { statements; return expr }) compiles to a whole-block evaluation method proteusCalcX() (derived expr = this.proteusCalcX()) — previously block bodies were ignored, leaving dangling references (ReferenceError); if the final statement is not a return, it warns and is ignored',
    why: '小程序无 computed 概念，编译期把 getter 转 data 派生：静态提取 getter 中的 ref 依赖 → 依赖写入时把重算表达式合并进同一 setData（v0.3 先做读路径；★#499 块体以整段方法求值对齐 Vue 响应语义——多语句局部变量/分支/模块函数均可）',
    whyEn: 'Mini programs have no computed concept, so the compiler turns the getter into a data derivation: the ref dependencies in the getter are statically extracted, and when a dependency is written the recompute expression is merged into the same setData (v0.3 implements the read path first; ★#499 block bodies are evaluated as whole methods to match Vue reactivity semantics — multi-statement locals/branches/module functions all work)',
    when: 'script 顶层出现 computed(() => 表达式)（箭头简写表达式体，或块体且末语句 return 表达式；块体无 return 编译期警告）',
    example: {
      before: 'const double = computed(() => count.value * 2)',
      after: 'data 不含 double；this.setData({ count: ..., double: this.data.count * 2 })（count 写入时合并，onLoad 初始化一次）',
    },
    verify: 'tests/mp-transform.test.ts computed 用例',
    source: 'packages/compiler/src/script.ts → extractComputedFromInit + computedPatch + computedInitLine',
    decision: '#76（v0.3）',
  },
  {
    id: 'script/watch-to-methods',
    phase: 'script',
    status: 'implemented',
    title: 'watch → proteusWatchX 方法（v0.3）',
    titleEn: 'watch → proteusWatchX method (v0.3)',
    description: 'watch(ref, (newVal, oldVal) => { body }) → methods 生成 proteusWatchX；依赖 ref 写入 setData 后自动调用（旧值在写入前保存）；immediate: true → onLoad 初始化调用一次',
    descriptionEn: 'watch(ref, (newVal, oldVal) => { body }) → generates proteusWatchX in methods; automatically invoked after the dependency ref is written to setData (the old value is saved before the write); immediate: true → invoked once during onLoad initialization',
    why: '小程序无 watch 概念，编译期模拟：依赖静态提取（单 ref）+ 写入点联动（setData 后调用回调，newVal/oldVal 由编译期保存）；MVP：仅单 ref 直接引用 + 箭头函数回调（数组源/函数源/function 回调警告）',
    whyEn: 'Mini programs have no watch concept, so the compiler simulates it: static dependency extraction (single ref) + write-point linkage (the callback runs after setData, with newVal/oldVal saved by the compiler); MVP: direct single-ref references + arrow-function callbacks only (array sources/function sources/function callbacks warn)',
    when: 'script 顶层出现 watch(refName, callback) 时',
    example: {
      before: 'watch(count, (n, o) => {\n  log(n, o)\n})',
      after: 'proteusWatchCount(n, o) {\n  log(n, o)\n},\n// count 写入：const oldCount = this.data.count; ...setData(...); this.proteusWatchCount(this.data.count, oldCount)',
    },
    verify: 'tests/mp-transform.test.ts watch 用例',
    source: 'packages/compiler/src/script.ts → extractWatch + watchTail + immediateWatchLine',
    decision: '#78（v0.3）',
  },
  {
    id: 'script/watch-props',
    phase: 'script',
    status: 'implemented',
    title: 'watch props 源 → WeChat observers（组件属性监听）',
    titleEn: 'watch props source → WeChat observers (component property listening)',
    description: 'watch(props.x, (n, o) => { body }) 或 watch(() => props.x, ...) → Component observers: { x(n, o) { body } }（属性变化触发回调；Web 端即标准 Vue watch，全响应式）；immediate: true → 另生成 proteusWatchPropX 方法 + attached 初始化调用一次',
    descriptionEn: 'watch(props.x, (n, o) => { body }) or watch(() => props.x, ...) → Component observers: { x(n, o) { body } } (a property change triggers the callback; on the Web it is a standard Vue watch, fully reactive); immediate: true → additionally generates a proteusWatchPropX method invoked once during attached initialization',
    why: '组件需要响应自身属性变化（列表 items 分页/加载更多、弹层 visible v-model、表单 value 同步等）；小程序无响应式系统，属性变化唯一通道是 observers',
    whyEn: 'Components must react to their own property changes (list items pagination/load-more, overlay visible v-model, form value sync, etc.); mini programs have no reactive system, so observers are the only channel for property changes',
    when: '组件 script 顶层出现 watch(props.x, callback) / watch(() => props.x, callback) 时（MVP：单属性源）',
    example: {
      before: 'watch(() => props.items, () => {\n  calc()\n})',
      after: 'observers: {\n  items(n, o) {\n    calc()\n  },\n}',
    },
    verify: 'tests/mp-transform.test.ts props 源 watch 用例',
    source: 'packages/compiler/src/script.ts → extractWatch（propField 分支）+ observers 发射',
    decision: '组件库 B3（p-list-view items 响应式）',
  },
  {
    id: 'script/module-import',
    phase: 'script',
    status: 'implemented',
    title: '跨模块引用：import → require 转换（module-plan B0）/ 剥离警告',
    titleEn: 'Cross-module reference: import → require conversion (module-plan B0) / stripping warning',
    description: 'setup 顶层 import：相对路径共享模块（moduleImports 命中）→ 产物顶部 const { x } = require("<相对产物路径>.js")（named/default/namespace/side 四形态）；vue/@proteus-vue/*/type/.vue 跳过（编译器静态/usingComponents/纯类型）；无法解析的路径 → 剥离 + 警告',
    descriptionEn: 'Top-level setup imports: relative-path shared modules (matched by moduleImports) are hoisted to the top of the output as `const { x } = require(...)` with the compiled relative module path appended (named/default/namespace/side, four forms); vue/@proteus-vue/*/type/.vue are skipped (compiler-static/usingComponents/pure types); unresolvable paths are stripped with a warning',
    why: '反黑盒（vue-compat Batch A，决策 #116）：import 剥离不再静默，产物未定义引用显式提示；★module-plan B0：相对路径共享模块编译为独立产物 + require 转换，跨模块引用真正可用（后续 Pinia/API/Component 基建的地基）',
    whyEn: 'Anti-black-box (vue-compat Batch A, decision #116): import stripping is no longer silent, and undefined references in the output are explicitly flagged; ★module-plan B0: relative-path shared modules are compiled into standalone outputs with require conversion, making cross-module references actually usable (the foundation for the later Pinia/API/Component infrastructure)',
    when: '<script setup> 顶层出现 import 语句',
    example: { before: 'import { formatTime } from "../utils/format"', after: 'const { formatTime } = require("../utils/format.js")（moduleImports 命中）；未收录路径 → 警告 + 剥离' },
    verify: 'tests/module-import.test.ts B0 用例 + tests/vue-compat.test.ts import 用例',
    source: 'packages/compiler/src/script.ts → extractImports + transformScriptToPage（require 生成）',
    decision: '#116',
  },
  {
    id: 'script/runtime-init',
    phase: 'script',
    status: 'implemented',
    title: '函数调用初始化 → 运行时初始化实例属性（module-plan B0）',
    titleEn: 'Function-call initialization → runtime-initialized instance property (module-plan B0)',
    description: '顶层 const x = fn()（静态求值失败）→ data 不含该字段；onLoad/attached 注入 this.x = fn()（实例属性，ES5 安全）；模板绑定不支持（读 this.data.x undefined）——共享逻辑请用模块 import',
    descriptionEn: 'Top-level const x = fn() (static evaluation failed) → data does not contain the field; onLoad/attached injects this.x = fn() (instance property, ES5-safe); template binding is unsupported (reading this.data.x is undefined) — use module import for shared logic',
    why: '旧行为：函数调用初始化静态求值失败 → data.x = undefined 且调用丢失（静默坏）；B0 配合跨模块 require 让 useStore()/createX() 真实执行',
    whyEn: 'Old behavior: when static evaluation of a function-call initializer failed, data.x became undefined and the call was silently dropped; with cross-module require, B0 makes useStore()/createX() actually execute',
    when: '顶层 const 初始值为函数调用且无法静态求值（非 inject/ref/computed）',
    example: { before: 'const store = usePlayerStore()', after: 'onLoad: this.store = usePlayerStore()（data 不含 store）' },
    verify: 'tests/module-import.test.ts + tests/vue-compat.test.ts 运行时初始化用例',
    source: 'packages/compiler/src/script.ts → extractData（runtimeInits）+ runtimeInitLine',
    decision: '#116',
  },
  {
    id: 'script/top-level-calls',
    phase: 'script',
    status: 'implemented',
    title: '顶层副作用语句保留（★#494/#G12：零缩进调用注入 onLoad 初始化序，实例依赖后置 this 化）',
    titleEn: 'Top-level side-effect statements preserved (#494/G12: zero-indent calls injected into the onLoad init sequence; instance-dependent calls moved after runtimeInits and this-ified)',
    description: '零缩进顶层表达式语句（initAppConfig(x) / registerCapability(x) 等调用形态）注入 onLoad 初始化序：外部/import 初始化调用（无实例依赖）置最前（先于 runtimeInits——初始化先于读取，#494 config-demo 白屏根因之二）；callee 依赖实例的调用（方法名册成员 this.x() / runtimeInit 链式 this.host.y()）后置 runtimeInit 之后并 this 化（★G12 复测真机 bug：semantic-primitives-demo 顶层 refreshSplit() 裸名注入 onLoad → ReferenceError）；此前这类语句被静默丢弃',
    descriptionEn: 'Zero-indent top-level expression statements (initAppConfig(x) / registerCapability(x) and other call forms) are injected into the onLoad init sequence: external/import initialization calls with no instance dependency go first (before runtimeInits — initialization before reads, #494 root cause of the config-demo white screen); calls whose callee depends on the instance (method-registry members this.x() / runtimeInit chained calls this.host.y()) move after runtimeInits and get this-ified (G12 on-device regression: semantic-primitives-demo top-level refreshSplit() was injected into onLoad as a bare name → ReferenceError); previously these statements were silently dropped',
    why: 'MP 页面无模块级作用域，<script setup> 顶层副作用必须显式注入生命周期才有执行时机——静默丢弃违背反黑盒红线',
    whyEn: 'MP pages have no module-level scope, so top-level side effects in <script setup> must be explicitly injected into a lifecycle to ever run — silently dropping them violates the anti-black-box red line',
    when: '零缩进单行调用语句（非 provide/inject/watch/computed/生命周期宏）',
    example: { before: 'initAppConfig(appConfig) / refreshSplit() / host.registerFallback(x)', after: 'onLoad 初始化序：外部 init 前置原样；refreshSplit() → this.refreshSplit()（runtimeInit 后）；host 链式 → this.host.registerFallback(x)（runtimeInit 后）' },
    verify: 'tests/app-config-mp.test.ts（#494 用例）+ tests/compiler-script-topcall.test.ts（G12 this 化/pre·post 分序）',
    source: 'packages/compiler/src/script.ts → extractTopLevelCalls + initLineSeq（rewriteBareMethodCalls 分序）',
    decision: '#494 / G12',
  },
  {
    id: 'script/app-config-binding',
    phase: 'script',
    status: 'implemented',
    title: 'app-config 模板绑定桥（★#494：快照 setData + onAppConfigChange 订阅）',
    titleEn: 'app-config template binding bridge (#494: snapshot setData + onAppConfigChange subscription)',
    description: 'const x = useAppConfig() / useFeatureFlag(k) 编译为命令式等价（getConfig() / getFeatureFlag(getConfig(), k)——无 Vue 实例要求）+ onLoad 快照 setData + onAppConfigChange 订阅刷新 + onUnload 退订；原样发射会在 onLoad 撞 useAppConfig 的 getCurrentInstance() 守卫（config-demo 白屏根因之一），且实例属性进不了 data、模板 {{ appConf.x }} 落空',
    descriptionEn: 'const x = useAppConfig() / useFeatureFlag(k) compile to imperative equivalents (getConfig() / getFeatureFlag(getConfig(), k) — no Vue instance required) + onLoad snapshot setData + onAppConfigChange subscription refresh + onUnload unsubscribe; emitting them verbatim hit the getCurrentInstance() guard of useAppConfig inside onLoad (first root cause of the config-demo white screen), and instance properties never reach data so template {{ appConf.x }} rendered empty',
    why: 'Pinia store 桥（$subscribe → setData）的对位物——app-config 无 $subscribe，新增 onAppConfigChange 订阅 API 作为桥的数据源；web 端 useAppConfig 响应式语义不变（守卫保留）',
    whyEn: 'The counterpart of the Pinia store bridge ($subscribe → setData) — app-config has no $subscribe, so the new onAppConfigChange subscription API serves as the bridge data source; web useAppConfig reactive semantics unchanged (guard retained)',
    when: '顶层 const 初始值为 useAppConfig() 或 useFeatureFlag(...)',
    example: { before: 'const appConf = useAppConfig()', after: 'onLoad: this.setData({ appConf: getConfig() }) + onAppConfigChange(() => setData 刷新)' },
    verify: 'tests/app-config-mp.test.ts（#494 用例）',
    source: 'packages/app-config/src/store.ts（onAppConfigChange）+ packages/compiler/src/script.ts（rewriteAppConfigCall/appConfigBindingLine）',
    decision: '#494',
  },
  {
    id: 'script/runtime-init-snapshot',
    phase: 'script',
    status: 'implemented',
    title: '模板引用的 runtimeInit 快照进 data（★#494）',
    titleEn: 'Snapshot of template-referenced runtimeInits into data (#494)',
    description: '模板表达式引用了 runtimeInit 变量名（templateRefs ∩ runtimeInits）→ onLoad 在赋值后 setData({ name: this.name }) 快照进 data；app-config 桥覆盖的不重复。实例属性模板读不到——不快照则 {{ x }}/:style="x" 落空（config-demo 的 :style="guardStyle"）',
    descriptionEn: 'When a template expression references a runtimeInit variable name (templateRefs ∩ runtimeInits), onLoad issues setData({ name: this.name }) after assignment; names already covered by the app-config bridge are skipped. Instance properties are unreachable from templates — without the snapshot {{ x }} / :style="x" renders empty (config-demo :style="guardStyle")',
    why: 'runtimeInit 通道的既定限制是「实例属性：模板绑定不支持」——快照把一次性初始化值（guard.patch 产物等）带进 data，模板绑定可用；响应式场景仍应用 Pinia store 桥/app-config 桥',
    whyEn: 'The established runtimeInit limitation is "instance property: template binding unsupported" — the snapshot brings one-shot initialized values (e.g. guard.patch results) into data so template bindings work; reactive scenarios should still use the Pinia store bridge / app-config bridge',
    when: '模板引用 runtimeInit 变量名且非 app-config/store 桥覆盖',
    example: { before: ':style="guardStyle"（guardStyle = makeGuardStyle() runtimeInit）', after: 'onLoad: this.setData({ guardStyle: this.guardStyle })' },
    verify: 'tests/app-config-mp.test.ts（#494 用例）',
    source: 'packages/compiler/src/template.ts（templateRefs 收集）+ script.ts（runtimeInitSnapshotLine）',
    decision: '#494',
  },
  {
    id: 'script/store-binding',
    phase: 'script',
    status: 'implemented',
    title: 'Pinia store 模板绑定（pinia-plan 12 P1：$subscribe → setData 同步）',
    titleEn: 'Pinia store template binding (pinia-plan 12 P1: $subscribe → setData sync)',
    description: '模板 {{ store.<field> }} 引用（template 收集 storeBindings）→ onLoad 注入：初始 setData({ field: this.store.field }) + store.$subscribe 订阅（变更 → setData，模板字段实时同步）；store 变量 = useXxxStore() 的 runtimeInit 实例属性；嵌套 store.current.title → current.title（store 前缀剥离）',
    descriptionEn: 'Template {{ store.<field> }} references (storeBindings collected in template) → onLoad injection: initial setData({ field: this.store.field }) + store.$subscribe subscription (changes → setData, template fields sync in real time); the store variable is the runtimeInit instance property of useXxxStore(); nested store.current.title → current.title (store prefix stripped)',
    why: 'MP 模板绑定读 this.data——store 是实例属性读不到；Pinia $subscribe 订阅 + setData 同步（对齐 store 桥 connectPageStore 模式），让 pinia-demo MP 端状态显示可用（pinia-plan 12）',
    whyEn: 'MP template bindings read this.data, and a store instance property is unreachable from there; Pinia $subscribe subscription + setData sync (aligned with the connectPageStore store-bridge pattern) makes state display work on the pinia-demo MP side (pinia-plan 12)',
    when: '模板出现 store.<field> 引用且 script 有 const store = useXxxStore()',
    example: { before: '{{ store.current.title }}', after: '{{ current.title }} + onLoad: this.store.$subscribe(() => this.setData({ current: this.store.current }))' },
    verify: 'tests/pinia-mp-compile.test.ts（P1 用例）',
    source: 'packages/compiler/src/template.ts（rewriteStoreRefs）+ script.ts（storeBindingLine）',
    decision: '#116',
  },
  {
    id: 'script/define-props',
    phase: 'script',
    status: 'implemented',
    title: 'defineProps → Component properties（v0.3 组件系统 + v0.3 尾泛型）',
    titleEn: 'defineProps → Component properties (v0.3 component system + v0.3 trailing generics)',
    description: '组件模式：defineProps({ label: String, initial: { type: Number, default: 0 } }) 或 TS 泛型 defineProps<{ label: string; count?: number }>() → properties（type + 默认值 value）；props.xxx 访问重写为 this.data.xxx',
    descriptionEn: 'Component mode: defineProps({ label: String, initial: { type: Number, default: 0 } }) or TS-generic defineProps<{ label: string; count?: number }>() → properties (type + default value); props.xxx accesses are rewritten to this.data.xxx',
    why: '小程序组件用 Component({ properties }) 声明外部属性；Vue 组件 props 编译期映射（v0.3，决策 #79）；对象形式（type/default）+ TS 泛型形式（string/number/boolean/object/Array/联合映射）',
    whyEn: 'Mini program components declare external properties with Component({ properties }); Vue component props are mapped at compile time (v0.3, decision #79); object form (type/default) + TS generic form (string/number/boolean/object/Array/union mapping)',
    when: '组件文件（isComponent）含 defineProps 时',
    example: { before: 'const props = defineProps<{ initial: number; label: string }>()', after: 'properties: {\n  initial: { type: Number, value: 0 },\n  label: { type: String, value: "" },\n}' },
    verify: 'tests/mp-transform.test.ts 组件系统用例',
    source: 'packages/compiler/src/script.ts → extractProps + mapTsType',
    decision: '#79 / #91（v0.3 尾泛型）',
  },
  {
    id: 'script/define-emits',
    phase: 'script',
    status: 'implemented',
    title: 'defineEmits + emit() → triggerEvent（v0.3 组件系统）',
    titleEn: 'defineEmits + emit() → triggerEvent (v0.3 component system)',
    description: '组件模式：emit("xxx", payload) → this.triggerEvent("xxx", payload)；父组件 @xxx（非 EVENT_MAP）→ bind:xxx；★G12 候选 B：v-model 契约事件 \'update:xxx\' 首参归一单段 \'update-xxx\'（与父 bind:update-xxx 同口径——双冒号事件名被 Skyline/glass-easel 编译链丢弃）；非 update: 前缀事件名不动',
    descriptionEn: 'Component mode: emit("xxx", payload) → this.triggerEvent("xxx", payload); parent @xxx (not in EVENT_MAP) → bind:xxx; ★G12 candidate B: v-model contract events normalize their first-arg literal \'update:xxx\' to the single segment \'update-xxx\' (matching the parent bind:update-xxx — double-colon event names are dropped by the Skyline/glass-easel compile chain); non-update: event names are left untouched',
    why: '小程序组件向父组件通信用 triggerEvent；Vue emit 编译期映射（v0.3，决策 #79）；MVP：约定 emit 变量名',
    whyEn: 'Mini program components use triggerEvent to communicate with the parent; Vue emit is mapped at compile time (v0.3, decision #79); MVP: the emit variable name follows a convention',
    when: '组件文件含 defineEmits 声明且方法体调用 emit(...) 时',
    example: { before: 'emit(\'change\', count.value)', after: 'this.triggerEvent(\'change\', this.data.count)' },
    verify: 'tests/mp-transform.test.ts 组件系统用例',
    source: 'packages/compiler/src/script.ts → rewriteRefAccess（emit 重写）+ template.ts（bind: 冒号形式）',
    decision: '#79（v0.3 组件系统）',
  },
  {
    id: 'script/define-expose',
    phase: 'script',
    status: 'implemented',
    title: 'defineExpose → no-op + 校验（v0.3 尾）',
    titleEn: 'defineExpose → no-op + validation (v0.3 wrap-up)',
    description: '组件模式：defineExpose({ ... }) 编译期 no-op——小程序组件 methods 天然可被 selectComponent 访问；校验声明成员：ref 值暴露无对等机制 → 警告',
    descriptionEn: 'Component mode: defineExpose({ ... }) is a compile-time no-op — mini program component methods are natively accessible via selectComponent; declared members are validated: exposing a ref value has no equivalent mechanism → warning',
    why: '小程序组件外部访问（selectComponent + 方法调用）天然覆盖 Vue 的 defineExpose 方法暴露语义；ref 值暴露需方法包装（v0.3 尾，决策 #91）',
    whyEn: 'External access to mini program components (selectComponent + method calls) natively covers the method-exposure semantics of Vue defineExpose; exposing a ref value would require method wrapping (v0.3 wrap-up, decision #91)',
    when: '组件文件含 defineExpose 时',
    example: { before: 'defineExpose({ reset })', after: 'no-op（reset 已在 methods，外部 selectComponent 可调）' },
    verify: 'tests/mp-transform.test.ts defineExpose 用例',
    source: 'packages/compiler/src/script.ts → checkDefineExpose',
    decision: '#91（v0.3 尾组件收尾）',
  },
  {
    id: 'script/define-model',
    phase: 'script',
    status: 'implemented',
    title: 'defineModel → v-model 组件契约（compileScript 权威源）',
    titleEn: 'defineModel → v-model component contract (authoritative compileScript source)',
    description: '组件模式：const m = defineModel<T>([name]) 经 @vue/compiler-sfc 权威展开为 _useModel(__props, name)——注册 prop（默认 modelValue）+ m.value 读→this.data.<prop> / 写→triggerEvent("update-<prop>", v)（glass-easel 事件名 update-xxx）；模板 {{ m }} 改名 {{ <prop> }}。不手写抠宏语义（模型修饰符/嵌套未全接 → partial）。',
    descriptionEn: 'Component mode: const m = defineModel<T>([name]) is authoritatively expanded by @vue/compiler-sfc to _useModel(__props, name) — registers prop (default modelValue) + rewrites m.value read→this.data.<prop> / write→triggerEvent("update-<prop>", v) (glass-easel update-xxx); template {{ m }} is renamed to {{ <prop> }}. Macro semantics are not hand-rolled (model modifiers/nesting not fully wired → partial).',
    why: 'Vue 能力对齐地基（不手造宏语义）：defineModel 的标准展开由 @vue/compiler-sfc 给出（bindings 分类 + props/emits 规约），框架只做 MP 适配（对齐 glass-easel 事件/属性规范），避免手写覆盖面不全致地基不牢。',
    whyEn: 'Vue capability alignment foundation (no hand-rolled macro semantics): defineModel standard expansion comes from @vue/compiler-sfc (bindings classification + props/emits contract); the framework only does MP adaptation (aligned with glass-easel event/property spec) to avoid fragile hand-rolled coverage.',
    when: '组件文件含 defineModel(...) 时',
    example: { before: 'const m = defineModel<string>()', after: 'properties.modelValue + m.value 读→this.data.modelValue / 写→this.triggerEvent("update-modelValue", v)' },
    verify: 'tests/vue-compat-compile.test.ts defineModel 用例',
    source: 'packages/compiler/src/script.ts → extractSfcMacros/rewriteRefAccess + sfc-macros.ts',
    decision: '2026-09-08 架构定调（吃 compileScript 权威源 + 对齐 glass-easel）',
  },
  {
    id: 'script/function-to-methods',
    phase: 'script',
    status: 'implemented',
    title: '顶层 function 声明 → methods',
    titleEn: 'Top-level function declarations → methods',
    description: '顶层 function handleTap() {...} → methods 中的对象简写 handleTap() {...}',
    descriptionEn: 'Top-level function handleTap() {...} → object shorthand handleTap() {...} in methods',
    why: '小程序页面逻辑在 methods 中；对象字面量内不能输出裸 function 声明（决策 #14：产物方法用对象简写）',
    whyEn: 'Mini program page logic lives in methods; bare function declarations cannot be emitted inside an object literal (decision #14: output methods use object shorthand)',
    when: 'script 顶层出现 function 声明时',
    example: {
      before: 'function handleTap() {\n  count.value++\n}',
      after: 'handleTap() {\n  this.setData({ count: (this.data.count === undefined || this.data.count === null ? 0 : this.data.count) + 1 })\n},',
    },
    verify: 'tests/mp-transform.test.ts methods 提取用例',
    source: 'src/compiler/script.ts → extractMethods',
    decision: '#14',
  },
  {
    id: 'script/arrow-to-methods',
    phase: 'script',
    status: 'implemented',
    title: 'const 箭头函数 → methods',
    titleEn: 'Const arrow functions → methods',
    description: 'const fn = (params) => {...} → methods 中的 fn(params) {...}（支持 async）',
    descriptionEn: 'const fn = (params) => {...} → fn(params) {...} in methods (async supported)',
    why: '小程序页面逻辑在 methods 中；const 箭头函数同样提取为方法',
    whyEn: 'Mini program page logic lives in methods; const arrow functions are extracted as methods the same way',
    when: 'script 顶层出现 const 箭头函数（含 async）时',
    example: {
      before: 'const load = async () => {\n  const r = await fetchData()\n}',
      after: 'load() {\n  const r = await fetchData()\n},',
    },
    verify: 'tests/mp-transform.test.ts methods 提取用例',
    source: 'src/compiler/script.ts → extractMethods（arrowRe 分支）',
  },
  {
    id: 'script/lifecycle-map',
    phase: 'script',
    status: 'implemented',
    title: '生命周期映射 onMounted → onReady / onUnmounted → onUnload',
    titleEn: 'Lifecycle mapping: onMounted → onReady / onUnmounted → onUnload',
    description: 'onMounted(() => {...}) → onReady() {...}；onUnmounted → onUnload；onLoad 透传',
    descriptionEn: 'onMounted(() => {...}) → onReady() {...}; onUnmounted → onUnload; onLoad is passed through',
    why: 'Vue 组件生命周期与小程序页面生命周期不同名，编译期映射到小程序钩子',
    whyEn: 'Vue component lifecycles and mini program page lifecycles have different names, so the compiler maps them onto mini program hooks',
    when: 'script 出现 onMounted / onUnmounted / onLoad 调用时',
    example: { before: 'onMounted(() => { doInit() })', after: 'onReady() {\n  doInit()\n},' },
    verify: 'tests/runtime.test.ts + mp-transform.test.ts 生命周期用例',
    source: 'src/compiler/script.ts → extractLifecycles',
  },
  {
    id: 'script/ref-read',
    phase: 'script',
    status: 'implemented',
    title: '方法内 ref 读取 → this.data.name',
    titleEn: 'In-method ref reads → this.data.name',
    description: '方法/生命周期体内的 name.value 读取 → this.data.name',
    descriptionEn: 'name.value reads in method/lifecycle hook bodies → this.data.name',
    why: '小程序运行期状态在 this.data 中，编译期把 setup ref 访问重写为 data 访问（决策 #22）',
    whyEn: 'Mini program runtime state lives in this.data, so the compiler rewrites setup ref accesses into data accesses (decision #22)',
    when: '方法或生命周期体内出现 ref.value 读取时',
    example: { before: 'const v = count.value', after: 'const v = this.data.count' },
    verify: 'tests/mp-transform.test.ts ref 重写用例',
    source: 'src/compiler/script.ts → rewriteRefAccess',
    decision: '#22',
  },
  {
    id: 'script/ref-write',
    phase: 'script',
    status: 'implemented',
    title: '方法内 ref 赋值 → this.setData',
    titleEn: 'In-method ref assignment → this.setData',
    description: '方法/生命周期体内的 name.value = expr → this.setData({ name: expr })',
    descriptionEn: 'name.value = expr in method/lifecycle hook bodies → this.setData({ name: expr })',
    why: '小程序更新视图的唯一通道是 setData，编译期把赋值重写为 setData 调用（决策 #22；排除 ==/===/复合赋值）',
    whyEn: 'setData is the only channel for updating the view in mini programs, so the compiler rewrites assignments into setData calls (decision #22; ==/===/compound assignments are excluded)',
    when: '方法或生命周期体内出现 name.value = expr 时',
    example: { before: 'count.value = count.value + 1', after: 'this.setData({ count: this.data.count + 1 })' },
    verify: 'tests/mp-transform.test.ts ref 重写用例',
    source: 'src/compiler/script.ts → rewriteRefAccess',
    decision: '#22',
  },
  {
    id: 'script/ref-incdec',
    phase: 'script',
    status: 'implemented',
    title: '方法内 ref 自增/自减 → this.setData',
    titleEn: 'In-method ref increment/decrement → this.setData',
    description: 'name.value++ / -- / ++name.value → this.setData({ name: (null 检查 ? 0 : this.data.name) + 1 })',
    descriptionEn: 'name.value++ / -- / ++name.value → this.setData({ name: (null check ? 0 : this.data.name) + 1 })',
    why: '自增/自减无表达式可提取，编译期为显式 setData 并做 null 兜底（决策 #22；不用 ?? 运算符——真机预览报 SyntaxError，决策 #36）',
    whyEn: 'Increment/decrement leaves no expression to extract, so the compiler emits an explicit setData with a null fallback (decision #22; the ?? operator is avoided — real-device preview throws SyntaxError, decision #36)',
    when: '方法或生命周期体内出现 name.value 的自增/自减时',
    example: {
      before: 'count.value++',
      after: 'this.setData({ count: (this.data.count === undefined || this.data.count === null ? 0 : this.data.count) + 1 })',
    },
    verify: 'tests/mp-transform.test.ts ref 重写用例；Web E2E tap 计数用例',
    source: 'src/compiler/script.ts → rewriteRefAccess + numOrZero',
    decision: '#22 / #36',
  },
  {
    id: 'script/vmodel-handler',
    phase: 'script',
    status: 'implemented',
    title: 'v-model 自动 handler 注入',
    titleEn: 'Automatic v-model handler injection',
    description: '模板出现 v-model="x" 时注入 proteusOnXInput(e) { this.setData({ x: e.detail.value }) }',
    descriptionEn: 'When v-model="x" appears in the template, inject proteusOnXInput(e) { this.setData({ x: e.detail.value }) }',
    why: '小程序无 v-model，回写方向由自动 handler 承担（决策 #29：方法名避免 __ 前缀，微信保留 _ 前缀可能导致绑定失效）',
    whyEn: 'Mini programs have no v-model; the auto-generated handler covers the write-back direction (decision #29: method names avoid the __ prefix, since WeChat reserves the _ prefix and bindings may break)',
    when: 'template 转换返回的 vModelBindings 非空时',
    example: {
      before: '（模板）<input v-model="name" />',
      after: 'proteusOnNameInput(e) { this.setData({ name: e.detail.value }) },',
    },
    verify: 'tests/mp-transform.test.ts v-model 用例',
    source: 'src/compiler/script.ts → transformScriptToPage（vModelBindings 循环）',
    decision: '#29',
  },
  {
    id: 'script/nav-handler',
    phase: 'script',
    status: 'implemented',
    title: '导航链接自动 handler 注入（proteusNavigateTo）',
    titleEn: 'Navigation-link auto handler injection (proteusNavigateTo)',
    description: '模板出现导航链接时注入 proteusNavigateTo(e)：读 data-url → wx.navigateTo（routeType 透传，fail 降级普通跳转）',
    descriptionEn: 'When a navigation link appears in the template, inject proteusNavigateTo(e): read data-url → wx.navigateTo (routeType is passed through; fail falls back to a normal navigation)',
    why: '小程序导航统一走 wx.navigateTo；保留前导 / 为绝对路径（决策 #30 真机根因）；fail 降级保证自定义路由失败仍可跳转（#28）；方法名避开 __ 前缀（#29）',
    whyEn: 'Mini program navigation uniformly goes through wx.navigateTo; a leading / is kept as an absolute path (decision #30, real-device root cause); the fail fallback keeps navigation working when a custom route fails (#28); method names avoid the __ prefix (#29)',
    when: 'template 转换返回 usesNavigate=true 时',
    example: {
      before: '（模板）<a href="/pages/user/index">用户</a>',
      after: 'proteusNavigateTo(e) {\n  const ds = e.currentTarget.dataset\n  const url = String(ds.url || "")\n  if (!url) return\n  const nav = { url: url, fail: ... }\n  if (ds.routeType) nav.routeType = ds.routeType\n  wx.navigateTo(nav)\n},',
    },
    verify: 'tests/mp-transform.test.ts 导航链接用例；真机验证归档 #30',
    source: 'src/compiler/script.ts → transformScriptToPage（usesNavigate 分支）',
    decision: '#24 / #28 / #29 / #30',
  },
  {
    id: 'page/scroll-bridge',
    phase: 'script',
    status: 'implemented',
    title: '页面滚动 API 桥接（15-page-scroll-container：Skyline 页面不滚动，页面钩子靠 scroll-view 事件触发）',
    titleEn: 'Page scroll API bridging (15-page-scroll-container: Skyline pages do not scroll; page hooks fire through scroll-view events)',
    description: '页面声明 onPageScroll/onReachBottom/onPullDownRefresh 时：自动包装 scroll-view 绑定对应事件（template 侧）+ 生成桥接方法（载荷归一：scroll-view e.detail.scrollTop → onPageScroll { scrollTop }）；手动 scroll-view 场景编译期歧义警告',
    descriptionEn: 'When the page declares onPageScroll/onReachBottom/onPullDownRefresh: automatically wrap scroll-view to bind the corresponding events (template side) and generate a bridge method (payload normalization: scroll-view e.detail.scrollTop → onPageScroll { scrollTop }); manual scroll-view scenarios raise a compile-time ambiguity warning',
    why: 'Skyline 页面本身不滚动（滚动必须 scroll-view）——页面级滚动钩子不会被触发；桥接后 onPageScroll/onReachBottom/onPullDownRefresh 语义保留（与 Web 端一致）',
    whyEn: 'Skyline pages themselves do not scroll (scrolling requires scroll-view), so page-level scroll hooks would never fire; after bridging, the semantics of onPageScroll/onReachBottom/onPullDownRefresh are preserved (consistent with the Web side)',
    when: '页面（非组件）模式 + 声明滚动生命周期 + 自动包滚动容器（rules.disabled 可关）',
    example: { before: 'function onPageScroll(e) { … }', after: '自动包装 scroll-view bindscroll="proteusPageScroll" + proteusPageScroll(e) 载荷归一调用 onPageScroll' },
    verify: 'tests/mp-transform.test.ts 页面滚动桥接用例',
    source: 'packages/compiler/src/{template,script}.ts（pageScrollHooks + proteusPageScroll 等）',
    decision: '2026-08 真机实测（15-page-scroll-container）',
  },
  {
    id: 'script/onload-params',
    phase: 'script',
    status: 'implemented',
    title: '默认 onLoad 参数自动 decode',
    titleEn: 'Automatic decoding of default onLoad parameters',
    description: '无显式 onLoad 时注入默认实现：遍历 options → decodeURIComponent → 结构化值（{/[ 开头）JSON.parse → setData',
    descriptionEn: 'With no explicit onLoad, inject the default implementation: iterate options → decodeURIComponent → JSON.parse structured values (starting with {/[) → setData',
    why: '路由参数经 query 传递，页面需还原为原始类型（决策 #19：仅对结构化值 JSON.parse，普通标量保持字符串——对齐 P3 契约 options.id === "1"）',
    whyEn: 'Route params are passed through the query string, so the page must restore their original types (decision #19: JSON.parse only for structured values; plain scalars stay strings — aligned with the P3 contract options.id === "1")',
    when: 'script 无显式 onLoad 时（有显式 onLoad 则透传）',
    example: {
      before: '（无 onLoad）',
      after: 'onLoad(options) {\n  const params = {}\n  const keys = Object.keys(options || {})\n  for (let i = 0; i < keys.length; i++) {\n    ...\n  }\n  this.setData(params)\n},',
    },
    verify: 'tests/runtime.test.ts 参数 decode 用例',
    source: 'src/compiler/script.ts → transformScriptToPage（onLoad 分支）',
    decision: '#19 / #32（ES5 安全：索引循环 Object.keys）',
  },
  {
    id: 'script/component-mode',
    phase: 'script',
    status: 'implemented',
    title: '组件模式 → Component() 构造器',
    titleEn: 'Component mode → Component() constructor',
    description: 'isComponent=true（components 目录下）→ Component({ data, methods, ... })，页面 → Page({ ... })',
    descriptionEn: 'isComponent=true (under the components/ directory) → Component({ data, methods, ... }); a page → Page({ ... })',
    why: '小程序页面用 Page()，组件用 Component()（不同构造器形态，isComponent 分支已在 compiler/index.ts 透传）',
    whyEn: 'Mini program pages use Page() and components use Component() (different constructor shapes; the isComponent branch is already passed through in compiler/index.ts)',
    when: '文件路径包含 components/ 目录时',
    example: { before: '（组件 SFC）', after: 'Component({ data: {...}, ... })' },
    verify: 'tests/mp-transform.test.ts 组件形态用例',
    source: 'src/compiler/script.ts → transformScriptToPage（isComponent 分支）',
  },
  {
    id: 'script/es5-safe',
    phase: 'script',
    status: 'implemented',
    title: '生成代码 ES5 安全',
    titleEn: 'Generated code is ES5-safe',
    description: '产物规避 ?? / ?. / 数组解构 / 对象展开（显式 null 检查三元、索引循环 Object.keys、直接属性赋值）',
    descriptionEn: 'Generated output avoids ?? / ?. / array destructuring / object spread (explicit null-check ternaries, index loops over Object.keys, direct property assignment)',
    why: '微信开发者工具将页面 JS 转 ES5 时依赖 babel helper 模块，helper 不在包内会报错（#32：arrayWithHoles 未定义）；真机预览直接报 ?? 语法错误（#36）',
    whyEn: 'When WeChat DevTools transpiles page JS to ES5 it depends on babel helper modules, and a helper missing from the package causes an error (#32: arrayWithHoles is undefined); real-device preview reports a direct ?? syntax error (#36)',
    when: '所有生成的 JS 产物（方法体 / onLoad / 自动 handler）',
    example: {
      before: '// 禁止出现在产物中\nconst [a, b] = arr\nconst v = x ?? 0',
      after: '// 产物实际形态\nconst a = arr[0], b = arr[1]\nconst v = (x === undefined || x === null ? 0 : x)',
    },
    verify: 'grep 扫描产物零残留（决策 #36 验证方式）',
    source: 'src/compiler/script.ts 各处（numOrZero / onLoad 实现 / nav handler）',
    decision: '#32 / #36',
  },
  {
    id: 'script/provide-inject',
    phase: 'script',
    status: 'implemented',
    title: 'provide/inject → getApp().__proteusProvides 全局注册表桥（vue-compat-advance Batch 3/4）',
    titleEn: 'provide/inject → getApp().__proteusProvides global registry bridge (vue-compat-advance Batch 3/4)',
    description: '顶层 provide("key", expr) / const x = inject("key"[, default]) 编译为注册表读写：页面 onLoad 单函数合并块（pageId 命名空间解析一次 + provide 注册 + inject setData）；组件 provide 放 created（先于子组件 attached 注入）、inject 放 attached；provide 值表达式重写裸 ref 名 / ref.value → this.data.<name>；inject 支持默认值（undefined 时取默认）；★Batch 4 响应式联动：裸 ref 提供（provide("key", refName)）→ ref 写入点注入 proteusSyncProvide（同步注册表值 + 通知订阅者），inject 侧订阅 __subs[key]（值变化 setData 刷新）+ detached/onUnload 取消；★Batch 6 页面级隔离：注册表按 pageId 命名空间（页面 onLoad __seq 生成 + 组件 getCurrentPages 栈顶解析，onUnload 删除命名空间防泄漏）；.value/字面量提供保持静态快照（对齐 Vue 语义：传 ref 联动、传值快照）',
    descriptionEn: 'Top-level provide("key", expr) / const x = inject("key"[, default]) compile to registry reads and writes: pages use a single merged onLoad block (pageId namespace resolved once + provide registration + inject setData); component provide goes into created (before child components attach-inject), inject into attached; provide value expressions rewrite bare ref names / ref.value → this.data.<name>; inject supports default values (the default applies when undefined); ★Batch 4 reactive linkage: providing a bare ref (provide("key", refName)) → proteusSyncProvide is injected at ref write points (syncs the registry value + notifies subscribers), and the inject side subscribes to __subs[key] (setData refresh on value change) with cancellation on detached/onUnload; ★Batch 6 page-level isolation: the registry is namespaced per pageId (pages generate __seq in onLoad + components resolve via the top of the getCurrentPages stack; onUnload deletes the namespace to prevent leaks); providing .value/literals keeps a static snapshot (aligned with Vue semantics: passing a ref links it, passing a value snapshots it)',
    why: '小程序组件树无 provide/inject 机制（决策 #117）：全局注册表桥让页面向组件传值（含深层嵌套组件）；MVP 值快照（非响应式联动）+ 全局注册表（重名 key 后写覆盖），页面级隔离/响应式为后续',
    whyEn: 'The mini program component tree has no provide/inject mechanism (decision #117): the global registry bridge lets a page pass values down to components (including deeply nested ones); MVP is value snapshots (no reactive linkage) + a global registry (duplicate keys are overwritten by the later write); page-level isolation/reactive linkage come later',
    when: 'script 顶层出现 provide("key", value) 调用或 const x = inject("key")（仅零缩进单行；provide 值支持字面量/裸 ref/ref.value）',
    example: {
      before: 'provide("user", userInfo)\nconst theme = inject("theme", "light")',
      after: 'onLoad: const provides = (getApp().__proteusProvides || (getApp().__proteusProvides = {})); provides["user"] = this.data.userInfo; if (!provides.__subs) provides.__subs = {}; ...; this.setData({ theme: (provides["theme"] === undefined ? "light" : provides["theme"]) })；userInfo 写入点追加 this.proteusSyncProvide("user", "userInfo")（通知订阅者 setData 刷新）',
    },
    verify: 'tests/vue-compat-advance.test.ts Batch 3/4 用例',
    source: 'packages/compiler/src/script.ts → extractProvideInject + buildProvideInject + rewriteRefAccess（写入点注入）+ transformScriptToPage（created/attached/onLoad 注入点 + proteusSyncProvide/proteusUnsubscribeProvide 生成）',
    decision: '#117',
  },
  {
    id: 'script/reactive-runtime-init',
    phase: 'script',
    status: 'implemented',
    title: 'reactive/readonly/浅族 const → 运行时真 Proxy（@vue/reactivity）',
    titleEn: 'reactive/readonly/shallow-family const → runtime real Proxy (@vue/reactivity)',
    description: '顶层 const s = reactive({...})/readonly({...})/shallowReactive/shallowReadonly 编译为 runtime-init this.s = reactive({...})（@vue/reactivity 真 Proxy，携带 ReactiveFlags 标记位）而非内联普通 data——否则 isReactive(reactive obj) 语义丢失；ref/shallowRef/computed 仍保持编译期内联（MP 高效模型）；constSourceTypes 记为 reactive/readonly 供 isRef 内联判定（均非 ref-like → false）',
    descriptionEn: 'Top-level const s = reactive({...})/readonly({...})/shallowReactive/shallowReadonly compiles to runtime-init this.s = reactive({...}) (a real @vue/reactivity Proxy carrying ReactiveFlags) instead of inlining to plain data — otherwise isReactive(reactive obj) semantics are lost; ref/shallowRef/computed stay compile-time inlined (the efficient MP model); constSourceTypes record reactive/readonly for isRef inline judgment (both are non-ref-like → false)',
    why: '小程序编译器此前把 reactive 内联成普通 data（无 Proxy）→ isReactive/isReadonly/isProxy 无法为真（无标记位）；引入运行时 @vue/reactivity（复用既有依赖，不造轮子）让 reactive 族返回真 Proxy，守卫读 ReactiveFlags 即可与 Web 同语义（对齐 uni-app @dcloudio/uni-mp-vue 做法——Vue3 reactivity 核心复用 + Proxy 桥接 setData）',
    whyEn: 'The MP compiler previously inlined reactive into plain data (no Proxy), so isReactive/isReadonly/isProxy could not be true (no flag); introducing runtime @vue/reactivity (reusing the existing dependency, not reinventing) makes the reactive family return real Proxies, so guards reading ReactiveFlags match Web semantics (aligned with uni-app @dcloudio/uni-mp-vue — reuse Vue3 reactivity core + bridge Proxy to setData)',
    when: 'script 顶层出现 const s = reactive(...)/readonly(...)/shallowReactive(...)/shallowReadonly(...) 时',
    example: {
      before: 'const s = reactive({ name: "x" })',
      after: 'onLoad: this.s = reactive({ name: "x" })（真 Proxy；data 置 s: null 占位模板可读）+ 后续 setData 桥',
    },
    verify: 'tests/vue-compat-reactivity-runtime.test.ts',
    source: 'packages/compiler/src/script.ts → handleConstToData（isReactiveRuntimeInit 拦截）+ transformScriptToPage（runtime-init 发射）',
    decision: 'reactivity-runtime-plan（选项 A spke）',
  },
  {
    id: 'script/reactivity-runtime-require',
    phase: 'script',
    status: 'implemented',
    title: 'reactive 族/守卫按需注入 require(\'@vue/reactivity\')',
    titleEn: 'Reactive family/guards inject require(\'@vue/reactivity\') on demand',
    description: '源码用到 reactive/readonly/shallowReactive/shallowReadonly/isReactive/isReadonly/isProxy/isShallow/toRaw 任一（词边界检测）→ 产物顶部注入 const { ...used } = require(\'@vue/reactivity\')；reactive 族存在时额外补 effect（setData 桥用）；纯 ref/computed 页面不注入——普通页面保持纯内联轻量（按需注入）',
    descriptionEn: 'When the source uses any of reactive/readonly/shallowReactive/shallowReadonly/isReactive/isReadonly/isProxy/isShallow/toRaw (word-boundary detection), the product injects const { ...used } = require(\'@vue/reactivity\') at the top; when the reactive family is present it also adds effect (for the setData bridge); pure ref/computed pages do not inject — keeping ordinary pages lean via inline compilation (on-demand injection)',
    why: 'vue import 在 MP 中被剥离（响应式走编译期内联），但 reactive 族/守卫需要运行时真函数；按需注入 @vue/reactivity（仅用到的 API）而非全量 vue——满足「有的不需要」的轻量诉求',
    whyEn: 'vue imports are stripped in MP (reactivity is inlined), but the reactive family/guards need real runtime functions; injecting @vue/reactivity on demand (only the APIs used) instead of the full vue meets the lightness need for pages that do not use it',
    when: 'script 使用上述任一反应式运行时 API（reactive/readonly/浅族/守卫/toRaw）时',
    example: {
      before: 'import { reactive } from \'vue\'\nconst s = reactive({ name: 1 })',
      after: 'const { reactive, effect } = require(\'@vue/reactivity\')（仅注入用到的符号；纯 ref 页无此行）',
    },
    verify: 'tests/vue-compat-reactivity-runtime.test.ts（按需注入/纯 ref 不注入）',
    source: 'packages/compiler/src/script.ts → transformScriptToPage（usedRuntimeApis 词边界检测 + requireLines 注入）',
    decision: 'reactivity-runtime-plan（选项 A spke）',
  },
  {
    id: 'script/reactive-setdata-bridge',
    phase: 'script',
    status: 'implemented',
    title: 'reactive 族变更 → setData 桥（effect 读透 proxy → 视图刷新）',
    titleEn: 'reactive-family mutation → setData bridge (effect reads through proxy → view refresh)',
    description: 'reactive/readonly 族 runtime-init 之后生成 per-const 桥：__proteusSyncReactive(name) 用 effect 读透 proxy（JSON 序列化即读透每个 getter/ownKeys → 任一字段变更触发重跑）→ setData({ [name]: 扁平快照 })；模板 {{ reactive.name }} 通过 data 占位 null + 桥持续 setData 读到视图；onUnload/detached 解绑 effect（__proteusDisposeReactive）防泄漏；初始 data 置 reactive 名为 null',
    descriptionEn: 'After reactive/readonly family runtime-init, generate a per-const bridge: __proteusSyncReactive(name) uses effect to read through the proxy (JSON serialization reads every getter/ownKeys → any field change re-runs) → setData({ [name]: flat snapshot }); template {{ reactive.name }} reads through the data placeholder null + the bridge keeps setData to the view; onUnload/detached disposes the effect (__proteusDisposeReactive) to prevent leaks; initial data sets reactive names to null',
    why: 'reactive 走运行时真 Proxy 后，logic 层变更需桥接 setData 才能刷新视图（uni-app @dcloudio/uni-mp-vue 核心工作——Proxy 读写桥接 setData 同步模型）；effect 依赖追踪是零造轮子的标准做法（读透即追踪，变更自动重跑）',
    whyEn: 'Once reactive goes through a runtime real Proxy, logic-layer mutations must be bridged to setData to refresh the view (the core of uni-app @dcloudio/uni-mp-vue — bridging Proxy reads/writes to the setData synchronization model); dependency tracking via effect is the standard no-reinvention approach (reading through tracks, mutations auto re-run)',
    when: 'script 含 reactive/readonly/浅族 const（reactiveInits 非空）时',
    example: {
      before: 'const s = reactive({ name: \"x\" })\n// 方法内 s.name = \"y\"',
      after: 'onLoad: this.s = reactive({ name: \"x\" }); this.__proteusSyncReactive(\'s\'); 变更 → 桥 effect 重跑 setData({ s: { name: \"y\" } })；onUnload 解绑',
    },
    verify: 'tests/vue-compat-reactivity-runtime.test.ts',
    source: 'packages/compiler/src/script.ts → transformScriptToPage（__proteusSyncReactive 方法 + reactiveBridgeSetupLine + reactiveDisposeLine）',
    decision: 'reactivity-runtime-plan（选项 A spke）',
  },
  {
    id: 'script/define-options',
    phase: 'script',
    status: 'implemented',
    title: 'defineOptions 剥离 no-op（compileScript 权威源）',
    titleEn: 'defineOptions strip no-op (compileScript authoritative source)',
    description: '顶层 defineOptions({ name, inheritAttrs }) 剥离为编译期 no-op（不裸注入 onLoad → not defined）；name/inheritAttrs 经 @vue/compiler-sfc compileScript 权威提取（展开为组件 options 的 ...{} 段），MP 组件无组件级 name/inheritAttrs 对等 → 警告说明不生效（组件属性请走 properties/attrs 通道）',
    descriptionEn: 'Top-level defineOptions({ name, inheritAttrs }) is stripped to a compile-time no-op (not injected bare into onLoad → not defined); name/inheritAttrs are extracted authoritatively via @vue/compiler-sfc compileScript (expanded into the component options ...{} segment); MP components have no component-level name/inheritAttrs counterpart → warns it is not effective (component attrs go through properties/attrs channel)',
    why: 'defineOptions 是 <script setup> 宏，被当顶层副作用裸注入 onLoad → not defined；宏语义权威源 = compileScript（不手造）——剥离 + 提取语义元数据，非 fail-closed error（消除 unsupported）',
    whyEn: 'defineOptions is a <script setup> macro that would be injected bare into onLoad → not defined; the authoritative macro semantics come from compileScript (no reinvention) — strip + extract semantic metadata rather than fail-closed error (eliminating unsupported)',
    when: 'script 顶层出现 defineOptions({ ... })（单行或多行对象字面量）时',
    example: {
      before: 'defineOptions({ name: "MyComp", inheritAttrs: false })',
      after: '剥离为 no-op（产物不含 defineOptions；警告说明 name/inheritAttrs 不生效）',
    },
    verify: 'tests/vue-compat-define-options.test.ts',
    source: 'packages/compiler/src/sfc-macros.ts → extractSfcMacros（defineOptions） + script.ts → transformScriptToPage（extractTopLevelCalls 跳过）+ extractSfcMacros 消费',
    decision: 'defineOptions 对齐（compileScript 权威源）',
  },
]
