// src/compiler/transforms/style.ts
// style 阶段编译规则注册表 —— 每条规则一份 AI 说明书
// ★阶段三分派层示范：implemented 规则可携带 apply()——AI 覆盖 apply 即生效（底线循环 ①）
import { TAG_MAP, SEMANTIC_CLASS } from '../tags'
import type { TransformRule, RuleContext } from './types'

export const STYLE_RULES: TransformRule[] = [
  {
    id: 'style/px-to-rpx',
    phase: 'style',
    status: 'implemented',
    title: 'px → rpx（仅 MP 端编译期生效）',
    titleEn: 'px → rpx (MP-side only, compile-time)',
    description: 'CSS 数值 px → rpx（rpxRatio 默认 2：48px → 96rpx）；Web 端永不转换（Vite 原生处理）',
    descriptionEn: 'CSS numeric px → rpx (rpxRatio defaults to 2: 48px → 96rpx); never converted on the Web side (handled natively by Vite)',
    why: '小程序 rpx 是屏幕等比单位（750 设计稿），跨端 CSS 一致性的编译期吸收（决策 #9：MP 端 px→rpx，Web 端保持标准 CSS）',
    whyEn: 'Mini Program rpx is a screen-proportional unit (750 design draft); this is a compile-time absorption for cross-end CSS consistency (decision #9: px→rpx on the MP side while the Web side keeps standard CSS)',
    when: 'style 中出现数值 px（style.px2rpx=true）时',
    example: { before: 'padding: 48px;', after: 'padding: 96rpx;' },
    verify: 'tests/mp-transform.test.ts px→rpx 用例',
    source: 'src/compiler/style.ts → transformStyleToWxss（px2rpx 分支）',
    decision: '#9',
    // ★分派层：AI 覆盖此实现（如改换算公式/单位映射）→ 编译输出即时变化，无需改 style.ts
    apply: (ctx: RuleContext) => {
      const input = ctx.input as string
      const ratio = Number(ctx.options?.rpxRatio ?? 2)
      ctx.output = input.replace(/(\d+(?:\.\d+)?)px\b/g, (_m: string, n: string) => `${Number(n) * ratio}rpx`)
    },
  },
  {
    id: 'style/selector-tag',
    phase: 'style',
    status: 'implemented',
    title: '选择器 HTML 标签 → 小程序标签',
    titleEn: 'Selector HTML tags → Mini Program tags',
    description: '选择器中的标签名重写为小程序标签（.links a → .links view、div > p → view > .proteus-p）；属性选择器/类名/ID/长标识符不误伤',
    descriptionEn: 'Tag names in selectors are rewritten to Mini Program tags (.links a → .links view, div > p → view > .proteus-p); attribute selectors/class names/IDs/long identifiers are never touched (no false positives)',
    why: '模板已把 div/a/h1 等映射为 view/text，若样式选择器不重写则匹配不到元素（决策 #57 修复的 bug）；命中条件=标签位于选择器起始或组合器之后，避免 .a/#input/tag-a 误伤',
    whyEn: 'The template already maps div/a/h1 etc. to view/text; if the style selectors were not rewritten, they would not match any element (a bug fixed by decision #57); match condition = the tag sits at the start of the selector or right after a combinator, avoiding false hits on .a/#input/tag-a',
    when: 'style 选择器中含 TAG_MAP 中的标签名时',
    example: { before: '.links a { color: #1a7af8; }', after: '.links .proteus-a { color: #1a7af8; }' },
    verify: 'tests/mp-transform.test.ts 选择器重写用例；产物验证 .links a → .links view 对齐 wxml（决策 #57）',
    source: 'src/compiler/style.ts → rewriteTagSelectors + TAG_SELECTOR_RE',
    decision: '#57',
    mapping: { ...TAG_MAP },
  },
  {
    id: 'style/selector-semantic',
    phase: 'style',
    status: 'implemented',
    title: '语义标签选择器 → proteus-* 类选择器',
    titleEn: 'Semantic tag selectors → proteus-* class selectors',
    description: 'h1-h6/p/a 选择器映射为基础类选择器（.card h3 → .card .proteus-h3、.links a → .links .proteus-a），而非标签',
    descriptionEn: 'h1-h6/p/a selectors are mapped to base class selectors (.card h3 → .card .proteus-h3, .links a → .links .proteus-a) instead of tags',
    why: 'h3 与 p 都映射为 text，若都映射为标签，同特异性规则后写覆盖先写（决策 #61 修复：.card p 的 color 曾污染 h3）；模板侧已附加 proteus-* 类故精确匹配',
    whyEn: 'Both h3 and p map to text; mapping both to tags would let later rules of equal specificity override earlier ones (decision #61 fix: .card p\'s color once leaked into h3); the template side already appends proteus-* classes, so matching is exact',
    when: '选择器中含 h1-h6/p/a 标签时',
    example: { before: '.card h3 { font-weight: 700; }', after: '.card .proteus-h3 { font-weight: 700; }' },
    verify: 'tests/mp-transform.test.ts 选择器重写用例（showcase.wxss 两条规则独立）',
    source: 'src/compiler/style.ts → rewriteTagSelectors（semantic 分支）+ src/compiler/tags.ts SEMANTIC_CLASS',
    decision: '#61',
    mapping: { ...SEMANTIC_CLASS },
  },
  {
    id: 'style/semantic-base-wxss',
    phase: 'style',
    status: 'implemented',
    title: '注入语义基础 WXSS（h1-h6/p/a 视觉还原）',
    titleEn: 'Inject semantic base WXSS (h1-h6/p/a visual restoration)',
    description: '产物 WXSS 头部注入 .proteus-h1~h6/.proteus-p/.proteus-a 基础样式（对齐 HTML 标准附录 D：字号/字重/单边 em 段距/链接色），位于用户样式之前',
    descriptionEn: 'Injects .proteus-h1~h6/.proteus-p/.proteus-a base styles at the head of the output WXSS (aligned with HTML standard Appendix D: font-size/font-weight/one-sided em paragraph spacing/link color), before user styles',
    why: 'Web 浏览器有 UA 默认样式，小程序 text/view 没有；注入基础类还原两端视觉一致（决策 #58）；margin 用单边 bottom + em 相对自身字号——Skyline 自研引擎不折叠 margin，单边 em 与 Web 折叠在主流程组合下视觉一致（决策 #59）',
    whyEn: 'Web browsers have UA default styles while Mini Program text/view do not; injecting base classes restores visual parity between the two sides (decision #58); margins use a one-sided bottom + em relative to the element\'s own font-size — the self-developed Skyline engine does not collapse margins, so one-sided em and Web collapsing are visually consistent under the main-flow combination (decision #59)',
    when: '每次 style 转换（作为产物前缀）',
    example: {
      before: '// 源码无样式时产物仍含',
      after: '.proteus-h1 { display: block; font-size: 64rpx; font-weight: 700; margin: 0 0 0.67em; }\n.proteus-p { display: block; margin: 0 0 1em; }\n.proteus-a { color: #1a7af8; text-decoration: underline; }',
    },
    verify: 'golden fixture showcase.wxss；产物验证 <text class="proteus-h1"> + .proteus-h1（决策 #58）',
    source: 'src/compiler/style.ts → BASE_SEMANTIC_WXSS',
    decision: '#58 / #59',
  },
  {
    id: 'style/default-scoped',
    phase: 'style',
    status: 'implemented',
    title: '默认 scoped：<style> 无标记按局部作用域处理（★2026-08 用户决策）',
    titleEn: 'Scoped by default: <style> without a marker is treated as local scope (★2026-08 user decision)',
    description: '非 <style global> 的 style 块均按 scoped 处理（类名后缀拼接）；<style> 无 scoped/global 标记时编译期警告；<style global>（Proteus 扩展）显式全局（不作用域化）；同文件 scoped+global 分组输出（global 在前）',
    descriptionEn: 'Style blocks other than <style global> are treated as scoped (class-name suffix concatenation); a compile-time warning fires when <style> carries neither a scoped nor a global marker; <style global> (a Proteus extension) is explicitly global (scoped isolation is off); scoped + global blocks in the same file are emitted as groups (global first)',
    why: 'Vue 标准 <style> 为全局——Web 端泄漏到所有页面（真机实测：config-demo 无 scoped 的灰色背景串到内置组件演示页）；用户决策默认局部更安全（跨端一致：Web 端 vite 插件同步改写 <style> → <style scoped>）',
    whyEn: 'Vue standard <style> is global, leaking to every page on the Web side (real-device test: config-demo\'s unscoped gray background bled into the built-in component demo page); the user decision makes local the safer default (cross-end consistent: the Web-side Vite plugin rewrites <style> → <style scoped> in sync)',
    when: '每次 SFC 编译（style 块处理）',
    example: { before: '<style>.box { color: red; }</style>', after: '按 scoped 处理（.box-data-v-x）+ 警告提示全局出口 <style global>' },
    verify: 'tests/mp-transform.test.ts 默认 scoped 用例',
    source: 'packages/compiler/src/index.ts → compileVueSfc（scopedStyles/globalStyles 分组）',
    decision: '2026-08 用户决策（默认 scoped）',
  },
  {
    id: 'style/skyline-unsupported',
    phase: 'style',
    status: 'implemented',
    title: 'Skyline 不支持属性编译期警告',
    titleEn: 'Compile-time warning for Skyline-unsupported properties',
    description: 'float、position: fixed 出现时编译期警告（不阻断构建）',
    descriptionEn: 'Emits a compile-time warning when float or position: fixed appears (does not block the build)',
    why: 'Skyline 自研渲染引擎不支持这些布局属性，编译期警告让开发者提前知道（反黑盒原则：警告可见、可统计）',
    whyEn: 'The self-developed Skyline rendering engine does not support these layout properties; a compile-time warning lets developers know in advance (anti-black-box principle: warnings are visible and countable)',
    when: 'WXSS 中出现 float: 或 position: fixed 时',
    example: { before: '.banner { position: fixed; }', after: '警告：WXSS 检测到 Skyline 不支持的属性：position: fixed（编译期警告）' },
    verify: 'tests/mp-transform.test.ts 警告用例',
    source: 'src/compiler/style.ts → transformStyleToWxss（unsupported 分支）',
  },
  {
    id: 'style/scoped-css',
    phase: 'style',
    status: 'implemented',
    title: 'scoped CSS：选择器类名后缀拼接（★2026-08 真机重构：单类选择器）',
    titleEn: 'scoped CSS: selector class-name suffixing (★2026-08 real-device refactor: single-class selectors)',
    description: '<style scoped> 存在时：选择器内每个类 token 追加 -scopeId（.box → .box-data-v-xxx 单一类选择器）；:deep(X) 去包装后统一后缀；@keyframes 帧/伪类伪元素/@规则不处理；逗号列表逐条',
    descriptionEn: 'When <style scoped> is present: every class token in a selector gets -scopeId appended (.box → .box-data-v-xxx, a single class selector); :deep(X) is unwrapped then suffixed uniformly; @keyframes frames/pseudo-classes, pseudo-elements, and @rules are left untouched; comma-separated lists are handled item by item',
    why: '小程序无 scoped CSS 原生机制，编译期类名后缀等价（v0.3，决策 #77）；★2026-08 真机重构：Skyline glass-easel 不支持属性选择器 [data-v]（f48460c 改 class 复合仍不匹配——.a.b 复合类选择器也静默丢弃，组件自身 wxss 匹配自身根节点都失效）→ 类名后缀是唯一 Skyline 确定支持的路径（单类选择器 ✓）',
    whyEn: 'Mini Program has no native scoped-CSS mechanism, so compile-time class-name suffixing is the equivalent (v0.3, decision #77); ★2026-08 real-device refactor: Skyline glass-easel does not support attribute selectors [data-v] (commit f48460c switched to compound class selectors but they still did not match — .a.b compound selectors were silently dropped, so even a component\'s own wxss failed to match its own root node) → class-name suffixing is the only path Skyline is confirmed to support (single-class selector ✓)',
    when: 'SFC 含 <style scoped> 且规则未被禁用时',
    example: { before: '.card { color: red; }', after: '.card-data-v-abc123 { color: red; }' },
    verify: 'tests/mp-transform.test.ts scoped CSS 用例',
    source: 'packages/compiler/src/style.ts → transformStyleToWxss（scopeId 分支）',
    decision: '#77（v0.3 scoped CSS）+ 2026-08 Skyline 真机重构（类名后缀）',
  },
  {
    id: 'transition/animation-wxss',
    phase: 'style',
    status: 'implemented',
    title: '<transition> 进入动画 keyframes 注入',
    titleEn: '<transition> enter-animation keyframes injection',
    description: 'wxss 尾部注入 proteus-transition-* 进入动画（fade/slide-up/scale keyframes）——配合模板侧 transition 装饰 class',
    descriptionEn: 'Injects proteus-transition-* enter animations at the tail of the wxss (fade/slide-up/scale keyframes) — matching the transition decoration classes on the template side',
    why: 'vue-compat-advance Batch 2（决策 #117）：<transition> 进入动画运行时等价（元素 wx:if 重建时 animation 自动播放）；离开动画 MP 无钩子',
    whyEn: 'vue-compat-advance Batch 2 (decision #117): runtime equivalence of <transition> enter animations (the animation auto-plays when the element is rebuilt via wx:if); leave animations have no hook on the MP side',
    when: '任一页面使用 <transition>（默认注入；rules.disabled 可关）',
    example: { before: '<transition name="fade">…', after: 'wxss 含 .proteus-transition-fade + @keyframes proteus-fade-in' },
    verify: 'tests/vue-compat-advance.test.ts Transition 用例',
    source: 'packages/compiler/src/style.ts → TRANSITION_WXSS 注入',
    decision: '#117',
  },
]
