// src/compiler/transforms/template.ts
// template 阶段编译规则注册表 —— 每条规则一份 AI 说明书
// 映射表与 src/compiler/tags.ts 同源引用（防漂移），registry 测试校验覆盖完整性
// ★阶段三分派层示范：implemented 规则可携带 apply()——AI 覆盖 apply 即生效（底线循环 ①）
import { TAG_MAP, EVENT_MAP, SEMANTIC_CLASS } from '../tags'
import type { TransformRule, RuleContext } from './types'

/** 表驱动规则工厂：从 TAG_MAP 取同源映射（改 tags.ts 自动生效，测试防遗漏） */
function tagRule(
  id: string,
  title: string,
  tags: string[],
  extra: Omit<TransformRule, 'id' | 'phase' | 'title' | 'mapping' | 'status'>,
): TransformRule {
  return {
    id,
    phase: 'template',
    status: 'implemented',
    title,
    mapping: Object.fromEntries(tags.map((t) => [t, TAG_MAP[t]]).filter(([, v]) => v !== undefined)),
    ...extra,
  }
}

export const TEMPLATE_RULES: TransformRule[] = [
  // ============ 标签映射（TAG_MAP） ============
  tagRule('tag/div-to-view', 'div → view', ['div'], {
    description: '块级容器 div → view（小程序通用容器）',
    descriptionEn: 'block-level container div → view (the universal Mini Program container)',
    why: '小程序没有 div，view 是最通用容器标签；业务代码照写标准 HTML（§0.3 原则 1）',
    whyEn: 'Mini Programs have no div; view is the most general-purpose container tag, so business code keeps writing standard HTML (§0.3 Principle 1)',
    when: 'template 中出现 <div> 时',
    example: { before: '<div class="home">…</div>', after: '<view class="home">…</view>' },
    verify: 'tests/mp-transform.test.ts「标准标签映射」',
    source: 'src/compiler/template.ts → serializeElement（TAG_MAP 查表）',
    decision: '#57（样式标签选择器映射）',
  }),
  tagRule('tag/inline-to-text', 'span → text', ['span'], {
    description: '行内文本 span → text（小程序最小文本节点）',
    descriptionEn: 'inline text span → text (the minimal Mini Program text node)',
    why: '小程序无 span，text 是行内文本容器；text 默认不换行、可被 text 嵌套',
    whyEn: 'Mini Programs have no span; text is the inline text container: it does not wrap by default and text can be nested inside text',
    when: 'template 中出现 <span> 时',
    example: { before: '<span>hi</span>', after: '<text>hi</text>' },
    verify: 'tests/mp-transform.test.ts「标准标签映射」',
    source: 'src/compiler/template.ts → serializeElement（TAG_MAP 查表）',
  }),
  tagRule('tag/heading-to-text', 'h1–h6 → text', ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'], {
    description: '标题 h1-h6 → text，并自动附加 proteus-h1~h6 基础类（见 semantic/base-class）',
    descriptionEn: 'headings h1-h6 → text, automatically appending the proteus-h1~h6 base classes (see semantic/base-class)',
    why: '小程序无标题标签；语义（大字号/加粗）由基础类还原（#58），视觉对齐 Web UA 样式',
    whyEn: 'Mini Programs have no heading tags; the semantics (larger size/bold) are restored by the base classes (#58), aligning the visuals with Web UA styles',
    when: 'template 中出现 <h1>~<h6> 时',
    example: { before: '<h1>标题</h1>', after: '<text class="proteus-h1">标题</text>' },
    verify: 'tests/mp-transform.test.ts「语义标签自动附加基础类」',
    source: 'src/compiler/template.ts → serializeElement + src/compiler/style.ts BASE_SEMANTIC_WXSS',
    decision: '#58 / #59',
  }),
  tagRule('tag/para-to-text', 'p → text', ['p'], {
    description: '段落 p → text，并自动附加 proteus-p 基础类（段距对齐 Web）',
    descriptionEn: 'paragraph p → text, automatically appending the proteus-p base class (paragraph spacing aligned with Web)',
    why: 'p 映射为 text 后无 UA 默认段距，基础类注入 margin: 0 0 1em 还原 Web 折叠间距（#59）',
    whyEn: 'once p is mapped to text there is no UA default paragraph spacing, so the base class injects margin: 0 0 1em to restore the Web collapsing spacing (#59)',
    when: 'template 中出现 <p> 时',
    example: { before: '<p>段落</p>', after: '<text class="proteus-p">段落</text>' },
    verify: 'tests/mp-transform.test.ts「标准标签映射」',
    source: 'src/compiler/template.ts → serializeElement',
    decision: '#59（margin 单边 em）',
  }),
  tagRule('tag/link-to-view', 'a → view', ['a'], {
    description: '链接 a → view（带 href 时升级为导航链接，见 nav/navigate-link）',
    descriptionEn: 'link a → view (upgraded to a navigation link when it carries href; see nav/navigate-link)',
    why: '小程序无 a 标签；导航语义由 data-url + bindtap="proteusNavigateTo" 承担，样式语义由 proteus-a 基础类承担',
    whyEn: 'Mini Programs have no a tag; the navigation semantics are carried by data-url + bindtap="proteusNavigateTo", and the styling semantics by the proteus-a base class',
    when: 'template 中出现 <a> 时',
    example: { before: '<a href="/pages/user/index">用户</a>', after: '<view class="proteus-a" data-url="/pages/user/index" bindtap="proteusNavigateTo">用户</view>' },
    verify: 'tests/mp-transform.test.ts 导航链接用例',
    source: 'src/compiler/template.ts → serializeElement（isNavLink 分支）',
    decision: '#24 / #30（导航链接）/ #58（基础类）',
  }),
  tagRule('tag/image', 'img → image', ['img'], {
    description: '图片 img → image；:src 绑定经 directive/v-bind 转为 src="{{url}}"',
    descriptionEn: 'image img → image; the :src binding is converted to src="{{url}}" via directive/v-bind',
    why: '小程序图片标签是 image',
    whyEn: 'the Mini Program image tag is image',
    when: 'template 中出现 <img> 时',
    example: { before: '<img :src="url" />', after: '<image src="{{url}}" />' },
    verify: 'tests/mp-transform.test.ts「标准标签映射」',
    source: 'src/compiler/template.ts → serializeElement（TAG_MAP 查表）',
  }),
  tagRule('tag/passthrough', '同名标签保留', ['button', 'input', 'textarea', 'video', 'canvas', 'scroll-view', 'slot'], {
    description: 'button / input / textarea / video / canvas / scroll-view / slot 同名保留（小程序原生即有）',
    descriptionEn: 'button / input / textarea / video / canvas / scroll-view / slot keep the same name (native to Mini Programs)',
    titleEn: 'same-name tags are kept as-is',
    why: '这些标签在小程序原生存在，无需映射；input/textarea 同时是 v-model 的目标（directive/v-model）',
    whyEn: 'these tags already exist natively in Mini Programs, so no mapping is needed; input/textarea are also the v-model targets (directive/v-model)',
    when: 'template 中出现以上标签时',
    example: { before: '<button>go</button>', after: '<button>go</button>' },
    verify: 'tests/mp-transform.test.ts 事件/表单用例',
    source: 'src/compiler/template.ts → serializeElement（TAG_MAP 查表）',
  }),
  tagRule('tag/router-link', 'router-link → view', ['router-link'], {
    description: 'Vue Router 的 router-link → view + 导航链接（to 属性 → data-url）',
    descriptionEn: 'Vue Router router-link → view + navigation link (the to attribute → data-url)',
    why: '小程序无 Vue Router 组件；统一转导航链接（决策 #24：<a href> / <router-link> 同为导航入口）',
    whyEn: 'Mini Programs have no Vue Router component; they are uniformly converted to navigation links (decision #24: <a href> / <router-link> are both navigation entry points)',
    when: 'template 中出现 <router-link to="..."> 且无 @click 时',
    example: { before: '<router-link to="/pages/user/index">用户</router-link>', after: '<view data-url="/pages/user/index" bindtap="proteusNavigateTo">用户</view>' },
    verify: 'tests/mp-transform.test.ts 导航链接用例',
    source: 'src/compiler/template.ts → serializeElement（isNavLink 分支）',
    decision: '#24',
  }),
  tagRule('tag/rich-text', 'v-html 容器 → rich-text', [], {
    description: '带 v-html 的容器元素 → rich-text（nodes="{{expr}}"）',
    descriptionEn: 'container elements with v-html → rich-text (nodes="{{expr}}")',
    titleEn: 'v-html container → rich-text',
    why: '小程序无 innerHTML，富文本用 rich-text 组件渲染 HTML 节点',
    whyEn: 'Mini Programs have no innerHTML; rich text is rendered as HTML nodes by the rich-text component',
    when: '元素上有 v-html 指令时（v-html 覆盖标签映射）',
    example: { before: '<div v-html="html"></div>', after: '<rich-text nodes="{{html}}" />' },
    verify: 'tests/mp-transform.test.ts v-html 用例',
    source: 'src/compiler/template.ts → serializeElement（hasVHtml 分支）',
  }),
  tagRule('tag/unknown-kebab', '未注册标签 kebab-case 原样输出', [], {
    description: 'TAG_MAP 未覆盖的标签按 kebab-case 原样输出（组件 / 自定义元素逃生舱）',
    descriptionEn: 'tags not covered by TAG_MAP are emitted as-is in kebab-case (the escape hatch for components / custom elements)',
    titleEn: 'unregistered tags are emitted as-is in kebab-case',
    why: '白名单映射 + 未知标签保守保留：标准 Vue 组件体系（原则 9）与原生组件逃生舱（痛点 #11 对策）依赖此通道',
    whyEn: 'whitelist mapping + conservative retention of unknown tags: the standard Vue component system (Principle 9) and the native-component escape hatch (the pain point #11 countermeasure) rely on this channel',
    when: '标签不在 TAG_MAP 且非 router-link 时',
    example: { before: '<custom-comp foo="bar" />', after: '<custom-comp foo="bar" />' },
    verify: 'tests/mp-transform.test.ts 未注册标签用例',
    source: 'src/compiler/template.ts → serializeElement（TAG_MAP[node.tag] ?? kebabCase）',
  }),

  // ============ 语义基础类 ============
  {
    id: 'semantic/base-class',
    phase: 'template',
    status: 'implemented',
    title: '语义标签自动附加 proteus-* 基础类',
    titleEn: 'semantic tags automatically get proteus-* base classes appended',
    description: 'h1-h6/p/a 映射时自动附加 proteus-h1~h6 / proteus-p / proteus-a 类（与用户 class 合并、与 :class 插值拼接）',
    descriptionEn: 'when h1-h6/p/a are mapped, the proteus-h1~h6 / proteus-p / proteus-a classes are appended automatically (merged with the user class and concatenated with :class interpolation)',
    why: 'Web 端 h1-h6/p/a 有浏览器 UA 默认样式，小程序 text/view 没有；基础类 + 基础 WXSS（style/semantic-base-wxss）还原两端视觉一致（#58）',
    whyEn: 'on the Web, h1-h6/p/a carry browser UA default styles, while Mini Program text/view have none; the base classes + base WXSS (style/semantic-base-wxss) restore visual parity across both ends (#58)',
    when: '语义标签且非 v-html 容器时',
    example: {
      before: '<h1 class="title">a</h1>',
      after: '<text class="proteus-h1 title">a</text>',
    },
    verify: 'tests/mp-transform.test.ts「语义标签自动附加基础类」；golden fixture showcase.wxml',
    source: 'src/compiler/template.ts → serializeElement（baseClass 分支）+ src/compiler/tags.ts SEMANTIC_CLASS',
    decision: '#58 / #59',
    mapping: { ...SEMANTIC_CLASS },
  },

  // ============ 事件映射（EVENT_MAP） ============
  {
    id: 'event/click-to-tap',
    phase: 'template',
    status: 'implemented',
    title: '@click → bindtap（EVENT_MAP 全表）',
    titleEn: '@click → bindtap (the full EVENT_MAP table)',
    description: '标准事件 → 小程序事件：click→tap、input/change/submit/focus/blur/touch*/longpress/confirm 同名保留',
    descriptionEn: 'standard events → Mini Program events: click→tap, while input/change/submit/focus/blur/touch*/longpress/confirm keep the same name',
    why: '小程序无 click，点击事件是 tap；其余事件命名一致（EVENT_MAP 集中在 tags.ts 与样式侧共用）',
    whyEn: 'Mini Programs have no click; the tap event is the click counterpart; the other events keep the same names (EVENT_MAP is centralized in tags.ts and shared with the style side)',
    when: '元素上有 @事件 指令时',
    example: { before: '<button @click="handleTap">go</button>', after: '<button bindtap="handleTap">go</button>' },
    verify: 'tests/mp-transform.test.ts「事件映射」',
    source: 'src/compiler/template.ts → serializeElement（on 分支）+ src/compiler/tags.ts EVENT_MAP',
    mapping: { ...EVENT_MAP },
  },
  {
    id: 'event/modifier-catch',
    phase: 'template',
    title: '.stop / .prevent 修饰符 → catch 前缀',
    titleEn: '.stop / .prevent modifiers → the catch prefix',
    description: '@click.stop / @click.prevent → catchtap（阻止冒泡）；其余修饰符忽略',
    descriptionEn: '@click.stop / @click.prevent → catchtap (prevents bubbling); the other modifiers are ignored',
    why: '小程序无事件修饰符语法，catch* 事件天然阻止冒泡，等价 .stop 语义；.prevent 无对等机制，映射为 catch 兜底',
    whyEn: 'Mini Programs have no event-modifier syntax; catch* events natively stop propagation, which is equivalent to .stop; .prevent has no counterpart, so it is mapped to catch as a fallback',
    when: '事件指令带 stop 或 prevent 修饰符时',
    example: { before: '<a @click.stop="stopFn">s</a>', after: '<a catchtap="stopFn">s</a>' },
    verify: 'tests/mp-transform.test.ts「事件映射」',
    source: 'src/compiler/template.ts → serializeElement（on 分支 isCatch）',
    status: 'implemented',
  },
  {
    id: 'event/modifier-self-once',
    phase: 'template',
    status: 'implemented',
    title: '.self / .once 修饰符 → 包装方法（v0.3 尾）',
    titleEn: '.self / .once modifiers → wrapper methods (late v0.3)',
    description: '@click.self="fn" → bindtap="proteusSelfFn"（e.target === e.currentTarget 才触发）；@click.once="fn" → bindtap="proteusOnceFn"（data 标记首次触发后不再触发）；仅对简单方法名 handler 包装',
    descriptionEn: '@click.self="fn" → bindtap="proteusSelfFn" (fires only when e.target === e.currentTarget); @click.once="fn" → bindtap="proteusOnceFn" (a data flag prevents firing after the first trigger); only handlers with a simple method name are wrapped',
    why: '小程序无 .self/.once 原生语义，编译期生成包装方法（script 侧）：self 用事件源判断、once 用 data 标记；键位修饰符（@keyup.enter）无对等键盘事件 → 编译期警告（input 请用 @confirm）',
    whyEn: 'Mini Programs have no native .self/.once semantics, so wrapper methods are generated at compile time (on the script side): self uses a source-event check and once uses a data flag; key modifiers (@keyup.enter) have no equivalent keyboard event → a compile-time warning (use @confirm on input)',
    when: '事件指令带 self 或 once 修饰符（且 handler 是简单方法名）时',
    example: {
      before: '@click.self="handleTap" / @click.once="handleTap"',
      after: 'bindtap="proteusSelfHandleTap" / bindtap="proteusOnceHandleTap"（包装方法生成于 Page methods）',
    },
    verify: 'tests/mp-transform.test.ts 事件修饰符用例',
    source: 'packages/compiler/src/template.ts（on 分支）+ script.ts（proteusSelf/Once 生成）',
    decision: '#88（v0.3 尾指令补全）',
  },
  {
    id: 'event/handler-simple-ref',
    phase: 'template',
    title: '事件处理器仅支持简单方法引用',
    titleEn: 'event handlers support only simple method references',
    description: '仅支持 handleTap / handleTap($event)；复杂表达式编译期警告并原样输出',
    descriptionEn: 'only handleTap / handleTap($event) are supported; complex expressions raise a compile-time warning and are emitted as-is',
    why: 'MVP 收缩（原则 10）：小程序事件处理器必须是 Page methods 中的方法名，内联表达式无法静态编译',
    whyEn: 'MVP contraction (Principle 10): Mini Program event handlers must be method names in Page methods; inline expressions cannot be statically compiled',
    when: '事件指令的表达式不是简单方法引用时',
    example: {
      before: '@click="count > 0 ? go() : back()"',
      after: '编译期警告：不是简单方法引用，原样输出（产物需人工处理）',
    },
    verify: 'tests/mp-transform.test.ts 事件警告用例',
    source: 'src/compiler/template.ts → cleanHandler',
    status: 'limitation',
  },

  // ============ 指令映射 ============
  {
    id: 'directive/v-if',
    phase: 'template',
    status: 'implemented',
    title: 'v-if → wx:if',
    description: 'v-if="show" → wx:if="{{show}}"',
    descriptionEn: 'v-if="show" → wx:if="{{show}}"',
    why: '小程序条件渲染指令是 wx:if',
    whyEn: 'the Mini Program conditional-rendering directive is wx:if',
    when: '元素上有 v-if 指令时',
    example: { before: '<p v-if="show">a</p>', after: '<p wx:if="{{show}}">a</p>' },
    verify: 'tests/mp-transform.test.ts「v-if / v-else」',
    source: 'src/compiler/template.ts → serializeElement（if 分支）',
  },
  {
    id: 'directive/v-else-if',
    phase: 'template',
    status: 'implemented',
    title: 'v-else-if → wx:elif',
    description: 'v-else-if="cond" → wx:elif="{{cond}}"',
    descriptionEn: 'v-else-if="cond" → wx:elif="{{cond}}"',
    why: '小程序条件链指令是 wx:elif',
    whyEn: 'the Mini Program conditional-chain directive is wx:elif',
    when: '元素上有 v-else-if 指令时',
    example: { before: '<p v-else-if="b">c</p>', after: '<p wx:elif="{{b}}">c</p>' },
    verify: 'tests/mp-transform.test.ts「v-if / v-else」',
    source: 'src/compiler/template.ts → serializeElement（else-if 分支）',
  },
  {
    id: 'directive/v-else',
    phase: 'template',
    status: 'implemented',
    title: 'v-else → wx:else',
    description: 'v-else → wx:else（无值）',
    descriptionEn: 'v-else → wx:else (takes no value)',
    why: '小程序条件链指令是 wx:else',
    whyEn: 'the Mini Program conditional-chain directive is wx:else',
    when: '元素上有 v-else 指令时',
    example: { before: '<p v-else>b</p>', after: '<p wx:else>b</p>' },
    verify: 'tests/mp-transform.test.ts「v-if / v-else」',
    source: 'src/compiler/template.ts → serializeElement（else 分支）',
  },
  {
    id: 'directive/v-for',
    phase: 'template',
    status: 'implemented',
    title: 'v-for → wx:for / wx:for-item / wx:for-index',
    description: 'v-for="(item, idx) in list" → wx:for="{{list}}" + wx:for-item + wx:for-index（支持 in/of）',
    descriptionEn: 'v-for="(item, idx) in list" → wx:for="{{list}}" + wx:for-item + wx:for-index (supports in/of)',
    why: '小程序循环指令是 wx:for，且需显式声明 item/index 变量名',
    whyEn: 'the Mini Program loop directive is wx:for, and the item/index variable names must be declared explicitly',
    when: '元素上有 v-for 指令时',
    example: {
      before: '<div v-for="(item, idx) in list" :key="idx">{{ item }}</div>',
      after: '<view wx:for="{{list}}" wx:for-item="item" wx:for-index="idx" wx:key="idx">{{ item }}</view>',
    },
    verify: 'tests/mp-transform.test.ts「v-for」',
    source: 'src/compiler/template.ts → serializeElement（for 分支）+ parseForExpr',
  },
  {
    id: 'directive/v-bind',
    phase: 'template',
    status: 'implemented',
    title: '普通 :prop 绑定 → prop="{{expr}}"',
    titleEn: 'plain :prop binding → prop="{{expr}}"',
    description: ':src / :href / 任意属性绑定 → 属性="{{表达式}}"，静态属性原样保留',
    descriptionEn: ':src / :href / any attribute binding → attribute="{{expression}}"; static attributes are kept as-is',
    why: '小程序属性绑定语法是 {{expr}}；静态属性（如 placeholder="x"）直接透传',
    whyEn: 'Mini Program attribute-binding syntax is {{expr}}; static attributes (e.g. placeholder="x") are passed through directly',
    when: '元素上有 v-bind 且 arg 不是 class/style/key 时',
    example: { before: '<img :src="url" />', after: '<image src="{{url}}" />' },
    verify: 'tests/mp-transform.test.ts「标准标签映射」',
    source: 'src/compiler/template.ts → serializeElement（bind 分支）',
  },
  {
    id: 'directive/v-bind-class',
    phase: 'template',
    status: 'implemented',
    title: ':class 绑定（对象/数组语法 → 三元拼接）',
    titleEn: ':class binding (object/array syntax → ternary concatenation)',
    description: ':class="{ active: on }" → {{(on?\'active \':\'\')}}；数组语法（v0.3）→ 逐项拼接（字符串/对象/简单变量/三元）',
    descriptionEn: ':class="{ active: on }" → {{(on?\'active \':\'\')}}; the array syntax (v0.3) → item-by-item concatenation (string/object/simple variable/ternary)',
    why: '小程序无 class 对象/数组语法，编译期为三元表达式拼接；数组语法 v0.3 补齐（splitTopLevel 顶层逗号分割，跳过字符串/括号内逗号）',
    whyEn: 'Mini Programs have no object/array class syntax, so the compiler concatenates ternary expressions; the array syntax was completed in v0.3 (splitTopLevel splits at top-level commas, skipping commas inside strings/parentheses)',
    when: '元素上有 :class 绑定且带语义基础类或对象/数组表达式时',
    example: {
      before: '<p :class="[activeClass, { active: on }]">b</p>',
      after: '<text class="proteus-p {{((activeClass)?(activeClass)+\' \':\'\')+(on?\'active \':\'\')}}">b</text>',
    },
    verify: 'tests/mp-transform.test.ts「语义标签自动附加基础类」+ :class 数组用例',
    source: 'packages/compiler/src/template.ts → formatClassBinding + splitTopLevel',
    decision: '#61 / #77（v0.3 数组语法）',
  },
  {
    id: 'directive/v-bind-style',
    phase: 'template',
    status: 'implemented',
    title: ':style 绑定（对象语法 → prop:{{expr}} 拼接）',
    titleEn: ':style binding (object syntax → prop:{{expr}} concatenation)',
    description: ':style="{ color: c }" → style="color:{{c}}"；属性名 camelCase → kebab-case',
    descriptionEn: ':style="{ color: c }" → style="color:{{c}}"; camelCase property names → kebab-case',
    why: '小程序 style 属性支持内联插值，逐属性编译可静态验证',
    whyEn: 'the Mini Program style attribute supports inline interpolation, so compiling per-property can be statically validated',
    when: '元素上有 :style 绑定且为对象语法时',
    example: { before: ':style="{ backgroundColor: bg }"', after: 'style="background-color:{{bg}}"' },
    verify: 'tests/mp-transform.test.ts :style 用例',
    source: 'src/compiler/template.ts → formatStyleBinding',
  },
  {
    id: 'directive/v-bind-key',
    phase: 'template',
    status: 'implemented',
    title: ':key → wx:key（仅简单标识符）',
    titleEn: ':key → wx:key (simple identifiers only)',
    description: ':key="idx" → wx:key="idx"；非简单标识符编译期警告并忽略',
    descriptionEn: ':key="idx" → wx:key="idx"; identifiers that are not simple trigger a compile-time warning and are ignored',
    why: '小程序列表复用标识是 wx:key，仅接受简单标识符',
    whyEn: 'the Mini Program list-reuse key is wx:key, which accepts only simple identifiers',
    when: '元素上有 :key 绑定（通常在 v-for 内）时',
    example: { before: ':key="idx"', after: 'wx:key="idx"' },
    verify: 'tests/mp-transform.test.ts「v-for」',
    source: 'src/compiler/template.ts → serializeElement（key 分支）',
  },
  {
    id: 'directive/v-model',
    phase: 'template',
    status: 'implemented',
    title: 'v-model → value + bindinput 自动 handler',
    titleEn: 'v-model → value + an automatic bindinput handler',
    description: 'input/textarea 的 v-model="x" → value="{{x}}" + bindinput="proteusOnXInput"（handler 由 script 阶段注入 setData）',
    descriptionEn: 'v-model="x" on input/textarea → value="{{x}}" + bindinput="proteusOnXInput" (the handler that performs the setData is injected by the script phase)',
    why: '小程序无 v-model 语法，需双向绑定的两半：value 绑定 + 输入事件回写（script/vmodel-handler）',
    whyEn: 'Mini Programs have no v-model syntax; the two halves of two-way binding are needed: a value binding + a write-back on the input event (script/vmodel-handler)',
    when: 'input 或 textarea 上有 v-model 指令时',
    example: {
      before: '<input v-model="name" />',
      after: '<input value="{{name}}" bindinput="proteusOnNameInput" />',
    },
    verify: 'tests/mp-transform.test.ts v-model 用例',
    source: 'src/compiler/template.ts → serializeElement（model 分支）',
    decision: '#29（方法名避免 __ 前缀）',
  },
  {
    id: 'directive/v-html',
    phase: 'template',
    status: 'implemented',
    title: 'v-html → rich-text nodes',
    description: 'v-html="html" → rich-text nodes="{{html}}"（容器标签映射为 rich-text）',
    descriptionEn: 'v-html="html" → rich-text nodes="{{html}}" (the container tag is mapped to rich-text)',
    why: '小程序无 innerHTML，富文本用 rich-text 组件（原生能力兜底，痛点 #11 对策）',
    whyEn: 'Mini Programs have no innerHTML; rich text uses the rich-text component (native capability as the fallback, the pain point #11 countermeasure)',
    when: '元素上有 v-html 指令时',
    example: { before: '<div v-html="html"></div>', after: '<rich-text nodes="{{html}}" />' },
    verify: 'tests/mp-transform.test.ts v-html 用例',
    source: 'src/compiler/template.ts → serializeElement（hasVHtml / html 分支）',
  },
  {
    id: 'directive/v-show',
    phase: 'template',
    status: 'implemented',
    title: 'v-show → hidden 属性',
    titleEn: 'v-show → the hidden attribute',
    description: 'v-show="show" → hidden="{{!show}}"（小程序 hidden 属性 = display:none，元素始终渲染）',
    descriptionEn: 'v-show="show" → hidden="{{!show}}" (the Mini Program hidden attribute equals display:none, and the element is always rendered)',
    why: '小程序无 v-show 指令，hidden 属性语义对齐（display:none 切换）；元素保留在文档流中，与 v-if 的移除不同（v0.3 补齐，原为 MVP 限制）',
    whyEn: 'Mini Programs have no v-show directive; the hidden attribute is its semantic equivalent (toggling display:none); the element stays in the document flow, unlike v-if which removes it (completed in v0.3; previously an MVP limitation)',
    when: '元素上有 v-show 指令时',
    example: { before: '<p v-show="show">a</p>', after: '<p hidden="{{!show}}">a</p>' },
    verify: 'tests/mp-transform.test.ts v-show 用例',
    source: 'packages/compiler/src/template.ts → serializeElement（show 分支）',
    decision: '#76（v0.3 指令补全）',
  },
  {
    id: 'directive/custom',
    phase: 'template',
    status: 'implemented',
    title: '自定义指令剥离（无对等警告）',
    titleEn: 'custom directives are stripped (warning when there is no equivalent)',
    description: 'v-focus 等自定义指令在小程序无对等机制——编译期警告并剥离（逻辑不执行），不再静默',
    descriptionEn: 'custom directives such as v-focus have no equivalent mechanism in Mini Programs — warned at compile time and stripped (the logic never executes), no longer silently',
    why: '反黑盒（vue-compat Batch A，决策 #116）：平台无对等能力必须编译期显式警告',
    whyEn: 'anti-black-box (vue-compat Batch A, decision #116): when the platform has no equivalent capability, it must warn explicitly at compile time',
    when: '元素上有非内置 v-xxx 指令（不在 if/else/for/show/model/html/text/on/bind/slot/pre/once/cloak）',
    example: { before: '<input v-focus />', after: '<input /> + 警告（已剥离）' },
    verify: 'tests/vue-compat.test.ts 自定义指令用例',
    source: 'packages/compiler/src/template.ts → serializeElement（switch default 分支）',
    decision: '#116',
  },
  {
    id: 'template/is-component',
    phase: 'template',
    status: 'implemented',
    title: '动态组件 <component :is> 无对等警告',
    titleEn: 'dynamic component <component :is> has no equivalent — warning',
    description: '<component :is> 动态组件在小程序无对等机制——警告（产物为无效标签），建议 v-if/v-else 条件渲染',
    descriptionEn: 'the <component :is> dynamic component has no equivalent mechanism in Mini Programs — a warning is raised (the output would be an invalid tag); conditional rendering with v-if/v-else is recommended',
    why: '反黑盒（vue-compat Batch A，决策 #116）：不再静默输出无效产物',
    whyEn: 'anti-black-box (vue-compat Batch A, decision #116): no longer silently emitting invalid output',
    when: '模板出现 <component> 标签',
    example: { before: '<component :is="which" />', after: '警告 + 原样输出（无效标签）' },
    verify: 'tests/vue-compat.test.ts 动态组件用例',
    source: 'packages/compiler/src/template.ts → serializeElement（component 分支）',
    decision: '#116',
  },
  {
    id: 'event/inline-expression',
    phase: 'template',
    status: 'implemented',
    title: '内联事件表达式 → 包装方法（vue-compat Batch B）',
    titleEn: 'inline event expressions → wrapper methods (vue-compat Batch B)',
    description: '@click="count++"（自增/自减）与 @click="fn(1)"（简单方法调用）→ 生成 proteusInlineXxx 包装方法（setData 更新 / this.fn(1)），产物可运行；复杂表达式仍警告',
    descriptionEn: '@click="count++" (increment/decrement) and @click="fn(1)" (a simple method call) → a proteusInlineXxx wrapper method is generated (setData update / this.fn(1)), keeping the output runnable; complex expressions still warn',
    why: 'Vue 常见写法支持（决策 #116 Batch B）：不再原样输出无效 bindtap；对齐 ref 重写（this.data.x ± 1，决策 #36）',
    whyEn: 'support for common Vue patterns (decision #116 Batch B): no longer emitting an invalid bindtap as-is; aligned with the ref rewriting (this.data.x ± 1, decision #36)',
    when: '事件处理器为自增/自减或简单方法调用（无 . 链）时',
    example: { before: '@click="count++"', after: 'bindtap="proteusInlineIncCount" + 方法 setData({ count: this.data.count + 1 })' },
    verify: 'tests/vue-compat.test.ts 内联表达式用例',
    source: 'packages/compiler/src/template.ts → tryInlineHandler + script.ts → inlineHandlers 注入',
    decision: '#116',
  },
  {
    id: 'slot/scoped-slot',
    phase: 'template',
    status: 'implemented',
    title: '作用域插槽警告（★Batch 7：MP/Skyline 平台限制确认 + 替代模式）',
    titleEn: 'scoped-slot warning (★Batch 7: MP/Skyline platform-limitation confirmation + alternative pattern)',
    description: '<slot :item="x"> 作用域插槽在小程序无对等机制（父侧拿不到子数据）——★平台限制：微信无模板传参机制（webview 的 template import 无法动态选择多父模板，Skyline 不支持跨文件模板），uni-app/Taro MP 端同样不完整——编译期警告 + 替代模式：子组件 props 接收数据 + 自定义事件回调传数据（<MyList :items :item-tap>）',
    descriptionEn: '<slot :item="x"> scoped slots have no equivalent mechanism in Mini Programs (the parent cannot access child data) — ★platform limitation: WeChat has no template parameter-passing mechanism (webview template import cannot dynamically pick among multiple parent templates, and Skyline does not support cross-file templates); the uni-app/Taro MP sides are likewise incomplete — compile-time warning + alternative pattern: the child component receives data via props and reports it back through custom-event callbacks (<MyList :items :item-tap>)',
    why: '反黑盒（vue-compat-advance Batch 1/7，决策 #117）：不再静默输出无效属性；运行时等价受 MP 平台能力限制（非待办，替代模式 props+事件已由组件系统完整支持）',
    whyEn: 'anti-black-box (vue-compat-advance Batch 1/7, decision #117): no longer silently emitting invalid attributes; runtime equivalence is limited by MP platform capabilities (not a TODO — the props + events alternative is fully supported by the component system)',
    when: '<slot> 元素上有 v-bind 属性（非 class/style/name）',
    example: { before: '<slot :item="item" />', after: '<slot /> + 警告（替代：props 传子 + triggerEvent 事件回调）' },
    verify: 'tests/vue-compat-advance.test.ts 作用域插槽用例',
    source: 'packages/compiler/src/template.ts → serializeElement（bind 分支 slot 检测）',
    decision: '#117',
  },
  {
    id: 'transition/component',
    phase: 'template',
    status: 'implemented',
    title: '<transition> → 装饰式进入动画（子元素注入动画 class）',
    titleEn: '<transition> → decorative enter animation (an animation class is injected into the child element)',
    description: '<transition name="fade"> 装饰式处理：过渡标签不输出，子元素注入 class="proteus-transition-{name}"（进入动画由重建自动播放）；wxss 按 usesTransition 按需注入 keyframes（fade/slide-up/scale）',
    descriptionEn: '<transition name="fade"> is handled decoratively: the transition tag itself is not emitted, and the child element is injected with class="proteus-transition-{name}" (the enter animation replays automatically on re-mount); wxss injects keyframes on demand according to usesTransition (fade/slide-up/scale)',
    why: 'Vue <transition> 运行时等价（vue-compat-advance Batch 2，决策 #117）：MP 无原生 Transition，编译注入动画 class + keyframes 补位；与路由 routeType 转场互补（元素级 vs 页面级）',
    whyEn: 'the runtime equivalent of Vue <transition> (vue-compat-advance Batch 2, decision #117): MP has no native Transition, so the compiler injects an animation class + keyframes to fill the gap; it complements route routeType transitions (element-level vs page-level)',
    when: '模板出现 <transition> 标签',
    example: { before: '<transition name="fade"><view v-if="on">X</view></transition>', after: '<view class="proteus-transition-fade" wx:if="{{__tv0}}">X</view>' },
    verify: 'tests/vue-compat-advance.test.ts Transition 用例',
    source: 'packages/compiler/src/template.ts → serializeElement（transition 分支）+ style.ts TRANSITION_WXSS',
    decision: '#117',
  },
  {
    id: 'transition/leave-state',
    phase: 'template',
    status: 'implemented',
    title: '<transition> 离开动画状态机（裸 ref v-if 延迟移除）',
    titleEn: '<transition> leave-animation state machine (bare-ref v-if removed with a delay)',
    description: 'transition 直接子元素 v-if 为裸 ref 名时启用离开动画：v-if 改写 wx:if="{{__tv{i}}}"（显示状态，初始 = ref 初始值）+ class 插值 {{__tl{i} ? "...-leave" : ""}}（离开中切换 leave 动画）；script 生成 proteusTransitionToggle{i}()（ref 写入点注入：on 变 false → __tl{i}=true 播离开动画 + setTimeout 时长后 __tv{i}=false 延迟移除；on 变 true → 取消定时器恢复进入动画）；wxss 按需注入 leave class + keyframes（forwards 保持末帧）',
    descriptionEn: 'the leave animation is enabled when the v-if on a direct child of transition is a bare ref name: v-if is rewritten to wx:if="{{__tv{i}}}" (the visible state, initially equal to the ref initial value) plus the class interpolation {{__tl{i} ? "...-leave" : ""}} (switching to the leave animation while leaving); the script generates proteusTransitionToggle{i}() (injected at the ref write points: when on turns false → __tl{i}=true plays the leave animation and, after a setTimeout of that duration, __tv{i}=false delays the removal; when on turns true → the timer is cancelled and the enter animation resumes); wxss injects the leave class and keyframes on demand (forwards keeps the last frame)',
    why: 'Vue transition 离开语义：v-if 变 false 先播离开动画再移除（vue-compat-advance Batch 5）；MP wx:if 立即移除无动画——编译期状态机补位；仅裸 ref v-if 支持（复杂表达式保持 Batch 2 现状）',
    whyEn: 'the Vue transition leave semantics: when v-if turns false, the leave animation plays first and only then is the element removed (vue-compat-advance Batch 5); MP wx:if removes immediately without animation — a compile-time state machine fills the gap; only bare-ref v-if is supported (complex expressions keep the Batch 2 behavior)',
    when: '<transition> 直接子元素带 v-if 且表达式为裸 ref 名',
    example: { before: '<transition name="fade"><view v-if="on">X</view></transition>', after: '<view wx:if="{{__tv0}}" class="proteus-transition-fade {{__tl0 ? \'proteus-transition-fade-leave\' : \'\'}}">X</view> + data __tv0/__tl0 + proteusTransitionToggle0()' },
    verify: 'tests/vue-compat-advance.test.ts Batch 5 用例',
    source: 'packages/compiler/src/template.ts → serializeElement（v-if 分支 + class 注入）+ script.ts（data/方法/写入点注入）+ style.ts TRANSITION_WXSS',
    decision: '#117',
  },
  {
    id: 'template/template-ref',
    phase: 'template',
    status: 'implemented',
    title: '模板 ref 无对等警告',
    titleEn: 'template ref has no equivalent — warning',
    description: 'ref="el" 模板 ref 在小程序无对等绑定（永不赋值）——警告，建议 this.selectComponent("#id")',
    descriptionEn: 'a template ref such as ref="el" has no equivalent binding in Mini Programs (never assigned) — a warning is raised; this.selectComponent("#id") is recommended',
    why: '反黑盒（vue-compat Batch A，决策 #116）：不再静默无效',
    whyEn: 'anti-black-box (vue-compat Batch A, decision #116): no longer silent about having no effect',
    when: '元素上有 ref 属性',
    example: { before: '<input ref="el" />', after: '<input /> + 警告' },
    verify: 'tests/vue-compat.test.ts 模板 ref 用例',
    source: 'packages/compiler/src/template.ts → serializeElement（ref 属性分支）',
    decision: '#116',
  },
  {
    id: 'template/no-peer',
    phase: 'template',
    status: 'implemented',
    title: '平台无对等组件警告（Transition/Teleport 等）',
    titleEn: 'warnings for platform components with no equivalent (Transition/Teleport, etc.)',
    description: 'transition/transition-group/teleport/suspense/keep-alive 在小程序无对等组件——警告（原样输出不生效）',
    descriptionEn: 'transition/transition-group/teleport/suspense/keep-alive have no equivalent in Mini Programs — a warning is raised (kept as-is, without effect)',
    why: '反黑盒（vue-compat Batch A，决策 #116）：转场请用路由 routeType，缓存/传送请移除',
    whyEn: 'anti-black-box (vue-compat Batch A, decision #116): use the routeType transition for transitions; remove keep-alive/teleport usage',
    when: '模板出现这些标签',
    example: { before: '<transition name="fade">…</transition>', after: '警告 + 原样输出' },
    verify: 'tests/vue-compat.test.ts 无对等组件用例',
    source: 'packages/compiler/src/template.ts → serializeElement（no-peer 分支）',
    decision: '#116',
  },

  // ============ 导航链接 ============
  {
    id: 'nav/navigate-link',
    phase: 'template',
    status: 'implemented',
    title: '<a href> / <router-link to> → 导航链接',
    titleEn: '<a href> / <router-link to> → navigation link',
    description: '带 href/to 的导航链接 → data-url + data-route-type + bindtap="proteusNavigateTo"（handler 由 script/nav-handler 注入）',
    descriptionEn: 'navigation links with href/to → data-url + data-route-type + bindtap="proteusNavigateTo" (the handler is injected by script/nav-handler)',
    why: 'Web 端 <a> 走浏览器导航，小程序端需转 data-url + 点击跳转（决策 #24）；保留前导 / 为绝对路径（#30 真机教训：无前导 / 会相对当前页目录解析导致双重前缀）',
    whyEn: 'on the Web <a> relies on browser navigation, while on Mini Programs it must become data-url + a tap-based jump (decision #24); the leading / is kept as an absolute path (#30 real-device lesson: without the leading / the path resolves against the current page directory and doubles the prefix)',
    when: 'a 或 router-link 且无 @click、含 href/to（静态或 :bind）时',
    example: {
      before: '<a href="/pages/user/index">用户</a>',
      after: '<view class="proteus-a" data-url="/pages/user/index" bindtap="proteusNavigateTo">用户</view>',
    },
    verify: 'tests/mp-transform.test.ts 导航链接用例；真机验证归档决策 #30',
    source: 'src/compiler/template.ts → serializeElement（isNavLink / hasNavTarget 分支）',
    decision: '#24 / #30 / #29',
  },
  {
    id: 'nav/route-type',
    phase: 'template',
    status: 'implemented',
    title: '导航链接 route-type 属性 → data-route-type',
    titleEn: 'navigation-link route-type attribute → data-route-type',
    description: '<a route-type="halfScreen"> → data-route-type="halfScreen"（proteusNavigateTo 透传为 wx.navigateTo 的 routeType）',
    descriptionEn: '<a route-type="halfScreen"> → data-route-type="halfScreen" (proteusNavigateTo forwards it as the routeType of wx.navigateTo)',
    why: 'Skyline 自定义路由转场从导航链接发起时，需把 routeType 传到运行期（决策 #44：routeType 双端同 API）',
    whyEn: 'when a Skyline custom route transition is initiated from a navigation link, routeType must reach the runtime (decision #44: routeType shares the same API on both ends)',
    when: '导航链接元素上有 route-type 属性时',
    example: {
      before: '<a href="/pages/user/profile" route-type="halfScreen">资料</a>',
      after: '<view data-url="/pages/user/profile" data-route-type="halfScreen" bindtap="proteusNavigateTo">资料</view>',
    },
    verify: 'tests/mp-transform.test.ts 导航链接用例',
    source: 'src/compiler/template.ts → serializeElement（route-type 分支）',
    decision: '#28 / #44',
  },

  // ============ 通用节点 ============
  {
    id: 'node/interpolation',
    phase: 'template',
    status: 'implemented',
    title: '插值 {{ expr }} 保留',
    titleEn: 'interpolations {{ expr }} are preserved',
    description: '{{ title }} → {{ title }}（表达式原样透传，文本节点紧凑单行输出）',
    descriptionEn: '{{ title }} → {{ title }} (the expression is passed through as-is; text nodes are emitted compactly on a single line)',
    why: '小程序插值语法同为 {{expr}}，无需转换；纯文本子节点紧凑单行保证产物可读（决策 #15）',
    whyEn: 'the Mini Program interpolation syntax is also {{expr}}, so no conversion is needed; text-only child nodes are compacted onto a single line to keep the output readable (decision #15)',
    when: '模板出现 {{ }} 插值或纯文本子节点时',
    example: { before: '<p>tapped {{ count }} times</p>', after: '<text class="proteus-p">tapped {{ count }} times</text>' },
    verify: 'golden fixture basic.wxml',
    source: 'src/compiler/template.ts → serializeNode（TEXT / INTERPOLATION 分支）',
    decision: '#15',
  },
  {
    id: 'annotation/line-note',
    phase: 'template',
    status: 'implemented',
    title: 'PROTEUS_DEBUG 源码行号注释',
    titleEn: 'PROTEUS_DEBUG source-line comments',
    description: 'annotateLines=true 时 WXML 每个元素前注入 <!-- @行号 标签 -->，产物可反查源码位置',
    descriptionEn: 'when annotateLines=true, a <!-- @line tag --> comment is injected before every WXML element so the output can be traced back to a source location',
    why: '反编译黑盒机制（#17）：默认关闭，npm run debug:mp 开启——AI/人拿到产物即可定位到源码行',
    whyEn: 'anti-black-box mechanism (#17): off by default, turned on by npm run debug:mp — whoever gets the output (AI/human) can locate the source line',
    when: '编译选项 annotateLines=true（PROTEUS_DEBUG=1 构建）时',
    example: { before: '第 26 行 <h1>{{ title }}</h1>', after: '<!-- @26 h1 -->\n<text class="proteus-h1">{{ title }}</text>' },
    verify: 'tests/mp-transform.test.ts annotateLines 用例；PROJECT_MEMORY #17',
    source: 'src/compiler/template.ts → serializeElement（lineNote 分支）',
    decision: '#17',
  },
  {
    id: 'template/scope-attr',
    phase: 'template',
    status: 'implemented',
    title: 'scoped CSS：用户 class 与 scopeId 拼接为单一类（★2026-08 真机重构：类名后缀）',
    titleEn: 'scoped CSS: user class and scopeId merged into one class (★2026-08 real-device refactor: class-name suffix)',
    description: '<style scoped> 存在时，模板元素 class 值 token 追加 -scopeId（.box → box-data-v-xxx）；:class 字符串字面量/对象键同样后缀（动态变量类名编译期警告）；样式侧选择器 .box-data-v-xxx 匹配',
    descriptionEn: 'when <style scoped> is present, every class-value token on a template element gets -scopeId appended (.box → box-data-v-xxx); :class string literals and object keys are suffixed the same way (dynamic variable class names warn at compile time); the selector .box-data-v-xxx then matches on the style side',
    why: '小程序无 scoped CSS 原生机制，编译期类名后缀等价（v0.3，决策 #77）；★2026-08 真机重构：Skyline 不支持属性选择器/复合类选择器 → 类名拼接为唯一单类选择器路径',
    whyEn: 'Mini Programs have no native scoped-CSS mechanism, so a compile-time class-name suffix is the equivalent (v0.3, decision #77); ★2026-08 real-device refactor: Skyline does not support attribute selectors/compound class selectors → the class is merged into a single unique single-class-selector path',
    when: 'SFC 含 <style scoped>（compileVueSfc 生成 scopeId 并注入）时',
    example: { before: '<div class="card">…</div>', after: '<view class="card-data-v-abc123">…</view>' },
    verify: 'tests/mp-transform.test.ts scoped CSS 用例',
    source: 'packages/compiler/src/template.ts → serializeElement（scopeSuffix 分支）',
    decision: '#77（v0.3 scoped CSS）+ 2026-08 Skyline 真机重构（类名后缀）',
    // ★分派层示范：输入 { tag, scopeId } → 输出作用域后缀片段（AI 覆盖可改后缀名）
    apply: (ctx: RuleContext) => {
      const input = ctx.input as { tag: string; scopeId: string }
      ctx.output = input.scopeId
    },
  },
  {
    id: 'component/root-class',
    phase: 'template',
    status: 'implemented',
    title: '组件标签 class 透传：root-class 属性 → 组件根节点 {{rootClass}}（Vue class 继承语义）',
    titleEn: 'component-tag class pass-through: root-class attribute → {{rootClass}} on the component root node (Vue class-inheritance semantics)',
    description: '自定义组件标签（非原生基础标签）的 class（scope class + 用户 class + :class 绑定）合并为单个 root-class 属性发射；组件模板根节点 class 追加 {{rootClass}}；script 侧组件注入 rootClass property（value: ""）',
    descriptionEn: 'the class of a custom component tag (a non-native base tag) — scope class + user class + :class binding — is merged and emitted as a single root-class attribute; {{rootClass}} is appended to the class of the component template root node; on the script side, the component is injected with a rootClass property (value: "")',
    why: 'Vue 的 class 继承语义（父组件 class 作用于子组件根节点）在微信无原生对等——组件 host 节点 class 合并后，页面 wxss 无法可靠作用（真机实测：p-view 外层容器 box 样式不生效，即使 styleIsolation: apply-shared）——编译期等价：class 经 root-class 属性传入组件，根节点绑定 {{rootClass}}，配合 apply-shared 让页面样式作用组件根节点',
    whyEn: 'Vue class-inheritance semantics (the parent class applies to the child root node) has no native equivalent in WeChat — once the class is merged onto the component host node, page wxss cannot reliably apply (real-device test: the box style on the p-view outer container does not take effect, even with styleIsolation: apply-shared) — the compile-time equivalent: the class enters the component via the root-class attribute, the root node binds {{rootClass}}, and together with apply-shared page styles reach the component root node',
    when: '模板出现非小程序原生标签（组件标签，如 p-view/counter）且规则未禁用时；组件模式根节点绑定',
    example: { before: '<p-view class="box">…</p-view>', after: '<p-view root-class="data-v-abc123 box" />（组件根节点 class="… {{rootClass}}"）' },
    verify: 'tests/mp-transform.test.ts 组件 class 透传用例',
    source: 'packages/compiler/src/template.ts → serializeElement（isComponentTag 分支）+ transformTemplateToWxml（isComponentRoot）；packages/compiler/src/script.ts → transformScriptToPage（properties.rootClass）',
    decision: '2026-08 真机实测（Skyline）',
  },
  {
    id: 'layout/auto-flex-row',
    phase: 'template',
    status: 'implemented',
    title: '行内场景自动 flex row（Skyline 无 inline 布局）',
    titleEn: 'inline scenarios automatically become flex row (Skyline has no inline layout)',
    description: '容器直接子元素同时含 text 与行内控件（switch/slider/icon/image/button/input/textarea/checkbox/radio/label/navigator/progress）→ 自动附加 proteus-flex-row 类（display:flex;row;align-items:center）；BASE 注入对应规则',
    descriptionEn: 'when the direct children of a container mix text with inline controls (switch/slider/icon/image/button/input/textarea/checkbox/radio/label/navigator/progress) → the proteus-flex-row class is appended automatically (display:flex;row;align-items:center); BASE injects the matching rule',
    why: 'Skyline 引擎不支持 inline 布局（官方 Inline × 开发中）——text 天生 block 占满一行，行内排布（text + switch 同行）唯一路径是 flex row（用户实测）；自动检测免开发者手动包 flex（双端一致）',
    whyEn: 'the Skyline engine does not support inline layout (officially Inline is under development) — text is block by nature and takes a full line, so the only way to arrange items inline (text + switch on one line) is flex row (verified by users); the automatic detection saves developers from manually wrapping in flex (consistent on both ends)',
    when: '容器子元素含 text 且含行内控件（rules.disabled 可关）',
    example: { before: '<view><switch/><text>开关</text></view>', after: '<view class="proteus-flex-row"><switch/><text>开关</text></view>' },
    verify: 'tests/mp-transform.test.ts 行内 flex 用例',
    source: 'packages/compiler/src/template.ts → serializeElement（autoFlexRow 判定）+ style.ts → BASE_SEMANTIC_WXSS',
    decision: '2026-08 用户决策（Skyline inline 限制）',
  },
  {
    id: 'component/progress-degrade',
    phase: 'template',
    status: 'implemented',
    title: 'progress 降级自定义 view 进度条（Skyline 官方不支持 progress）',
    titleEn: 'progress downgrades to a custom view progress bar (Skyline officially does not support progress)',
    description: '小程序语义 <progress> 编译为自定义 view 结构（track/inner/info 三节点）——percent→宽度、active-color/color→填充色、stroke-width→高度、show-info（无值=真）→百分比文字；静态属性直出、绑定插值；BASE 注入 .proteus-progress 样式',
    descriptionEn: 'the native Mini Program <progress> element is compiled into a custom view structure (three nodes: track/inner/info) — percent → width, active-color/color → fill color, stroke-width → height, show-info (no value means true) → the percentage text; static attributes are emitted directly and bindings become interpolations; BASE injects the .proteus-progress styles',
    why: 'Skyline 组件支持表 progress 暂不考虑（真机实测不渲染）——降级自定义结构双端一致 + Skyline 可用（16-progress-skyline-degrade）',
    whyEn: 'progress is not currently on the Skyline component-support list (real-device tests show it does not render) — the downgraded custom structure keeps both ends consistent and is usable on Skyline (16-progress-skyline-degrade)',
    when: '模板出现 <progress> 且规则未禁用时',
    example: { before: '<progress :percent="70" show-info />', after: '<view class="proteus-progress"><view class="proteus-progress-track"><view class="proteus-progress-inner" style="width:{{70}}%;background-color:#07c160"></view></view><text wx:if="{{true}}" class="proteus-progress-info">{{70}}%</text></view>' },
    verify: 'tests/mp-transform.test.ts progress 降级用例',
    source: 'packages/compiler/src/template.ts → serializeProgress + style.ts → BASE_SEMANTIC_WXSS',
    decision: '2026-08 真机实测（Skyline 不支持 progress）',
  },
]

// 追踪键（防漂移）：标签 → 规则 ID，由 tag/* 规则的 mapping 反推——实现侧 trace 引用同一份数据
// 只取 tag/ 前缀规则：semantic/base-class（mapping 含 h1-p/a）与 event/click-to-tap（mapping 含 input/click）
// 的键是另一维度的映射，不得混入标签追踪（后定义覆盖会污染）。
// tests/explain.test.ts 校验所有 trace 事件 ruleId 均可解析
export const TAG_RULE_BY_TAG: Record<string, string> = Object.fromEntries(
  TEMPLATE_RULES.filter((r) => r.id.startsWith('tag/')).flatMap((r) =>
    r.mapping ? Object.keys(r.mapping).map((t): [string, string] => [t, r.id]) : [],
  ),
)
