// src/compiler/transforms/template.ts
// template 阶段编译规则注册表 —— 每条规则一份 AI 说明书
// 映射表与 src/compiler/tags.ts 同源引用（防漂移），registry 测试校验覆盖完整性
import { TAG_MAP, EVENT_MAP, SEMANTIC_CLASS } from '../tags'
import type { TransformRule } from './types'

/** 表驱动规则工厂：从 TAG_MAP 取同源映射（改 tags.ts 自动生效，测试防遗漏） */
function tagRule(
  id: string,
  title: string,
  tags: string[],
  extra: Omit<TransformRule, 'id' | 'phase' | 'title' | 'mapping' | 'status'>,
): TransformRule {
  return {
    id,
    phase: 'template',
    status: 'implemented',
    title,
    mapping: Object.fromEntries(tags.map((t) => [t, TAG_MAP[t]]).filter(([, v]) => v !== undefined)),
    ...extra,
  }
}

export const TEMPLATE_RULES: TransformRule[] = [
  // ============ 标签映射（TAG_MAP） ============
  tagRule('tag/div-to-view', 'div → view', ['div'], {
    description: '块级容器 div → view（小程序通用容器）',
    why: '小程序没有 div，view 是最通用容器标签；业务代码照写标准 HTML（§0.3 原则 1）',
    when: 'template 中出现 <div> 时',
    example: { before: '<div class="home">…</div>', after: '<view class="home">…</view>' },
    verify: 'tests/mp-transform.test.ts「标准标签映射」',
    source: 'src/compiler/template.ts → serializeElement（TAG_MAP 查表）',
    decision: '#57（样式标签选择器映射）',
  }),
  tagRule('tag/inline-to-text', 'span → text', ['span'], {
    description: '行内文本 span → text（小程序最小文本节点）',
    why: '小程序无 span，text 是行内文本容器；text 默认不换行、可被 text 嵌套',
    when: 'template 中出现 <span> 时',
    example: { before: '<span>hi</span>', after: '<text>hi</text>' },
    verify: 'tests/mp-transform.test.ts「标准标签映射」',
    source: 'src/compiler/template.ts → serializeElement（TAG_MAP 查表）',
  }),
  tagRule('tag/heading-to-text', 'h1–h6 → text', ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'], {
    description: '标题 h1-h6 → text，并自动附加 proteus-h1~h6 基础类（见 semantic/base-class）',
    why: '小程序无标题标签；语义（大字号/加粗）由基础类还原（#58），视觉对齐 Web UA 样式',
    when: 'template 中出现 <h1>~<h6> 时',
    example: { before: '<h1>标题</h1>', after: '<text class="proteus-h1">标题</text>' },
    verify: 'tests/mp-transform.test.ts「语义标签自动附加基础类」',
    source: 'src/compiler/template.ts → serializeElement + src/compiler/style.ts BASE_SEMANTIC_WXSS',
    decision: '#58 / #59',
  }),
  tagRule('tag/para-to-text', 'p → text', ['p'], {
    description: '段落 p → text，并自动附加 proteus-p 基础类（段距对齐 Web）',
    why: 'p 映射为 text 后无 UA 默认段距，基础类注入 margin: 0 0 1em 还原 Web 折叠间距（#59）',
    when: 'template 中出现 <p> 时',
    example: { before: '<p>段落</p>', after: '<text class="proteus-p">段落</text>' },
    verify: 'tests/mp-transform.test.ts「标准标签映射」',
    source: 'src/compiler/template.ts → serializeElement',
    decision: '#59（margin 单边 em）',
  }),
  tagRule('tag/link-to-view', 'a → view', ['a'], {
    description: '链接 a → view（带 href 时升级为导航链接，见 nav/navigate-link）',
    why: '小程序无 a 标签；导航语义由 data-url + bindtap="proteusNavigateTo" 承担，样式语义由 proteus-a 基础类承担',
    when: 'template 中出现 <a> 时',
    example: { before: '<a href="/pages/user/index">用户</a>', after: '<view class="proteus-a" data-url="/pages/user/index" bindtap="proteusNavigateTo">用户</view>' },
    verify: 'tests/mp-transform.test.ts 导航链接用例',
    source: 'src/compiler/template.ts → serializeElement（isNavLink 分支）',
    decision: '#24 / #30（导航链接）/ #58（基础类）',
  }),
  tagRule('tag/image', 'img → image', ['img'], {
    description: '图片 img → image；:src 绑定经 directive/v-bind 转为 src="{{url}}"',
    why: '小程序图片标签是 image',
    when: 'template 中出现 <img> 时',
    example: { before: '<img :src="url" />', after: '<image src="{{url}}" />' },
    verify: 'tests/mp-transform.test.ts「标准标签映射」',
    source: 'src/compiler/template.ts → serializeElement（TAG_MAP 查表）',
  }),
  tagRule('tag/passthrough', '同名标签保留', ['button', 'input', 'textarea', 'video', 'canvas', 'scroll-view', 'slot'], {
    description: 'button / input / textarea / video / canvas / scroll-view / slot 同名保留（小程序原生即有）',
    why: '这些标签在小程序原生存在，无需映射；input/textarea 同时是 v-model 的目标（directive/v-model）',
    when: 'template 中出现以上标签时',
    example: { before: '<button>go</button>', after: '<button>go</button>' },
    verify: 'tests/mp-transform.test.ts 事件/表单用例',
    source: 'src/compiler/template.ts → serializeElement（TAG_MAP 查表）',
  }),
  tagRule('tag/router-link', 'router-link → view', ['router-link'], {
    description: 'Vue Router 的 router-link → view + 导航链接（to 属性 → data-url）',
    why: '小程序无 Vue Router 组件；统一转导航链接（决策 #24：<a href> / <router-link> 同为导航入口）',
    when: 'template 中出现 <router-link to="..."> 且无 @click 时',
    example: { before: '<router-link to="/pages/user/index">用户</router-link>', after: '<view data-url="/pages/user/index" bindtap="proteusNavigateTo">用户</view>' },
    verify: 'tests/mp-transform.test.ts 导航链接用例',
    source: 'src/compiler/template.ts → serializeElement（isNavLink 分支）',
    decision: '#24',
  }),
  tagRule('tag/rich-text', 'v-html 容器 → rich-text', [], {
    description: '带 v-html 的容器元素 → rich-text（nodes="{{expr}}"）',
    why: '小程序无 innerHTML，富文本用 rich-text 组件渲染 HTML 节点',
    when: '元素上有 v-html 指令时（v-html 覆盖标签映射）',
    example: { before: '<div v-html="html"></div>', after: '<rich-text nodes="{{html}}" />' },
    verify: 'tests/mp-transform.test.ts v-html 用例',
    source: 'src/compiler/template.ts → serializeElement（hasVHtml 分支）',
  }),
  tagRule('tag/unknown-kebab', '未注册标签 kebab-case 原样输出', [], {
    description: 'TAG_MAP 未覆盖的标签按 kebab-case 原样输出（组件 / 自定义元素逃生舱）',
    why: '白名单映射 + 未知标签保守保留：标准 Vue 组件体系（原则 9）与原生组件逃生舱（痛点 #11 对策）依赖此通道',
    when: '标签不在 TAG_MAP 且非 router-link 时',
    example: { before: '<custom-comp foo="bar" />', after: '<custom-comp foo="bar" />' },
    verify: 'tests/mp-transform.test.ts 未注册标签用例',
    source: 'src/compiler/template.ts → serializeElement（TAG_MAP[node.tag] ?? kebabCase）',
  }),

  // ============ 语义基础类 ============
  {
    id: 'semantic/base-class',
    phase: 'template',
    status: 'implemented',
    title: '语义标签自动附加 proteus-* 基础类',
    description: 'h1-h6/p/a 映射时自动附加 proteus-h1~h6 / proteus-p / proteus-a 类（与用户 class 合并、与 :class 插值拼接）',
    why: 'Web 端 h1-h6/p/a 有浏览器 UA 默认样式，小程序 text/view 没有；基础类 + 基础 WXSS（style/semantic-base-wxss）还原两端视觉一致（#58）',
    when: '语义标签且非 v-html 容器时',
    example: {
      before: '<h1 class="title">a</h1>',
      after: '<text class="proteus-h1 title">a</text>',
    },
    verify: 'tests/mp-transform.test.ts「语义标签自动附加基础类」；golden fixture showcase.wxml',
    source: 'src/compiler/template.ts → serializeElement（baseClass 分支）+ src/compiler/tags.ts SEMANTIC_CLASS',
    decision: '#58 / #59',
    mapping: { ...SEMANTIC_CLASS },
  },

  // ============ 事件映射（EVENT_MAP） ============
  {
    id: 'event/click-to-tap',
    phase: 'template',
    status: 'implemented',
    title: '@click → bindtap（EVENT_MAP 全表）',
    description: '标准事件 → 小程序事件：click→tap、input/change/submit/focus/blur/touch*/longpress/confirm 同名保留',
    why: '小程序无 click，点击事件是 tap；其余事件命名一致（EVENT_MAP 集中在 tags.ts 与样式侧共用）',
    when: '元素上有 @事件 指令时',
    example: { before: '<button @click="handleTap">go</button>', after: '<button bindtap="handleTap">go</button>' },
    verify: 'tests/mp-transform.test.ts「事件映射」',
    source: 'src/compiler/template.ts → serializeElement（on 分支）+ src/compiler/tags.ts EVENT_MAP',
    mapping: { ...EVENT_MAP },
  },
  {
    id: 'event/modifier-catch',
    phase: 'template',
    title: '.stop / .prevent 修饰符 → catch 前缀',
    description: '@click.stop / @click.prevent → catchtap（阻止冒泡）；其余修饰符忽略',
    why: '小程序无事件修饰符语法，catch* 事件天然阻止冒泡，等价 .stop 语义；.prevent 无对等机制，映射为 catch 兜底',
    when: '事件指令带 stop 或 prevent 修饰符时',
    example: { before: '<a @click.stop="stopFn">s</a>', after: '<a catchtap="stopFn">s</a>' },
    verify: 'tests/mp-transform.test.ts「事件映射」',
    source: 'src/compiler/template.ts → serializeElement（on 分支 isCatch）',
    status: 'implemented',
  },
  {
    id: 'event/modifier-self-once',
    phase: 'template',
    status: 'implemented',
    title: '.self / .once 修饰符 → 包装方法（v0.3 尾）',
    description: '@click.self="fn" → bindtap="proteusSelfFn"（e.target === e.currentTarget 才触发）；@click.once="fn" → bindtap="proteusOnceFn"（data 标记首次触发后不再触发）；仅对简单方法名 handler 包装',
    why: '小程序无 .self/.once 原生语义，编译期生成包装方法（script 侧）：self 用事件源判断、once 用 data 标记；键位修饰符（@keyup.enter）无对等键盘事件 → 编译期警告（input 请用 @confirm）',
    when: '事件指令带 self 或 once 修饰符（且 handler 是简单方法名）时',
    example: {
      before: '@click.self="handleTap" / @click.once="handleTap"',
      after: 'bindtap="proteusSelfHandleTap" / bindtap="proteusOnceHandleTap"（包装方法生成于 Page methods）',
    },
    verify: 'tests/mp-transform.test.ts 事件修饰符用例',
    source: 'packages/compiler/src/template.ts（on 分支）+ script.ts（proteusSelf/Once 生成）',
    decision: '#88（v0.3 尾指令补全）',
  },
  {
    id: 'event/handler-simple-ref',
    phase: 'template',
    title: '事件处理器仅支持简单方法引用',
    description: '仅支持 handleTap / handleTap($event)；复杂表达式编译期警告并原样输出',
    why: 'MVP 收缩（原则 10）：小程序事件处理器必须是 Page methods 中的方法名，内联表达式无法静态编译',
    when: '事件指令的表达式不是简单方法引用时',
    example: {
      before: '@click="count > 0 ? go() : back()"',
      after: '编译期警告：不是简单方法引用，原样输出（产物需人工处理）',
    },
    verify: 'tests/mp-transform.test.ts 事件警告用例',
    source: 'src/compiler/template.ts → cleanHandler',
    status: 'limitation',
  },

  // ============ 指令映射 ============
  {
    id: 'directive/v-if',
    phase: 'template',
    status: 'implemented',
    title: 'v-if → wx:if',
    description: 'v-if="show" → wx:if="{{show}}"',
    why: '小程序条件渲染指令是 wx:if',
    when: '元素上有 v-if 指令时',
    example: { before: '<p v-if="show">a</p>', after: '<p wx:if="{{show}}">a</p>' },
    verify: 'tests/mp-transform.test.ts「v-if / v-else」',
    source: 'src/compiler/template.ts → serializeElement（if 分支）',
  },
  {
    id: 'directive/v-else-if',
    phase: 'template',
    status: 'implemented',
    title: 'v-else-if → wx:elif',
    description: 'v-else-if="cond" → wx:elif="{{cond}}"',
    why: '小程序条件链指令是 wx:elif',
    when: '元素上有 v-else-if 指令时',
    example: { before: '<p v-else-if="b">c</p>', after: '<p wx:elif="{{b}}">c</p>' },
    verify: 'tests/mp-transform.test.ts「v-if / v-else」',
    source: 'src/compiler/template.ts → serializeElement（else-if 分支）',
  },
  {
    id: 'directive/v-else',
    phase: 'template',
    status: 'implemented',
    title: 'v-else → wx:else',
    description: 'v-else → wx:else（无值）',
    why: '小程序条件链指令是 wx:else',
    when: '元素上有 v-else 指令时',
    example: { before: '<p v-else>b</p>', after: '<p wx:else>b</p>' },
    verify: 'tests/mp-transform.test.ts「v-if / v-else」',
    source: 'src/compiler/template.ts → serializeElement（else 分支）',
  },
  {
    id: 'directive/v-for',
    phase: 'template',
    status: 'implemented',
    title: 'v-for → wx:for / wx:for-item / wx:for-index',
    description: 'v-for="(item, idx) in list" → wx:for="{{list}}" + wx:for-item + wx:for-index（支持 in/of）',
    why: '小程序循环指令是 wx:for，且需显式声明 item/index 变量名',
    when: '元素上有 v-for 指令时',
    example: {
      before: '<div v-for="(item, idx) in list" :key="idx">{{ item }}</div>',
      after: '<view wx:for="{{list}}" wx:for-item="item" wx:for-index="idx" wx:key="idx">{{ item }}</view>',
    },
    verify: 'tests/mp-transform.test.ts「v-for」',
    source: 'src/compiler/template.ts → serializeElement（for 分支）+ parseForExpr',
  },
  {
    id: 'directive/v-bind',
    phase: 'template',
    status: 'implemented',
    title: '普通 :prop 绑定 → prop="{{expr}}"',
    description: ':src / :href / 任意属性绑定 → 属性="{{表达式}}"，静态属性原样保留',
    why: '小程序属性绑定语法是 {{expr}}；静态属性（如 placeholder="x"）直接透传',
    when: '元素上有 v-bind 且 arg 不是 class/style/key 时',
    example: { before: '<img :src="url" />', after: '<image src="{{url}}" />' },
    verify: 'tests/mp-transform.test.ts「标准标签映射」',
    source: 'src/compiler/template.ts → serializeElement（bind 分支）',
  },
  {
    id: 'directive/v-bind-class',
    phase: 'template',
    status: 'implemented',
    title: ':class 绑定（对象/数组语法 → 三元拼接）',
    description: ':class="{ active: on }" → {{(on?\'active \':\'\')}}；数组语法（v0.3）→ 逐项拼接（字符串/对象/简单变量/三元）',
    why: '小程序无 class 对象/数组语法，编译期为三元表达式拼接；数组语法 v0.3 补齐（splitTopLevel 顶层逗号分割，跳过字符串/括号内逗号）',
    when: '元素上有 :class 绑定且带语义基础类或对象/数组表达式时',
    example: {
      before: '<p :class="[activeClass, { active: on }]">b</p>',
      after: '<text class="proteus-p {{((activeClass)?(activeClass)+\' \':\'\')+(on?\'active \':\'\')}}">b</text>',
    },
    verify: 'tests/mp-transform.test.ts「语义标签自动附加基础类」+ :class 数组用例',
    source: 'packages/compiler/src/template.ts → formatClassBinding + splitTopLevel',
    decision: '#61 / #77（v0.3 数组语法）',
  },
  {
    id: 'directive/v-bind-style',
    phase: 'template',
    status: 'implemented',
    title: ':style 绑定（对象语法 → prop:{{expr}} 拼接）',
    description: ':style="{ color: c }" → style="color:{{c}}"；属性名 camelCase → kebab-case',
    why: '小程序 style 属性支持内联插值，逐属性编译可静态验证',
    when: '元素上有 :style 绑定且为对象语法时',
    example: { before: ':style="{ backgroundColor: bg }"', after: 'style="background-color:{{bg}}"' },
    verify: 'tests/mp-transform.test.ts :style 用例',
    source: 'src/compiler/template.ts → formatStyleBinding',
  },
  {
    id: 'directive/v-bind-key',
    phase: 'template',
    status: 'implemented',
    title: ':key → wx:key（仅简单标识符）',
    description: ':key="idx" → wx:key="idx"；非简单标识符编译期警告并忽略',
    why: '小程序列表复用标识是 wx:key，仅接受简单标识符',
    when: '元素上有 :key 绑定（通常在 v-for 内）时',
    example: { before: ':key="idx"', after: 'wx:key="idx"' },
    verify: 'tests/mp-transform.test.ts「v-for」',
    source: 'src/compiler/template.ts → serializeElement（key 分支）',
  },
  {
    id: 'directive/v-model',
    phase: 'template',
    status: 'implemented',
    title: 'v-model → value + bindinput 自动 handler',
    description: 'input/textarea 的 v-model="x" → value="{{x}}" + bindinput="proteusOnXInput"（handler 由 script 阶段注入 setData）',
    why: '小程序无 v-model 语法，需双向绑定的两半：value 绑定 + 输入事件回写（script/vmodel-handler）',
    when: 'input 或 textarea 上有 v-model 指令时',
    example: {
      before: '<input v-model="name" />',
      after: '<input value="{{name}}" bindinput="proteusOnNameInput" />',
    },
    verify: 'tests/mp-transform.test.ts v-model 用例',
    source: 'src/compiler/template.ts → serializeElement（model 分支）',
    decision: '#29（方法名避免 __ 前缀）',
  },
  {
    id: 'directive/v-html',
    phase: 'template',
    status: 'implemented',
    title: 'v-html → rich-text nodes',
    description: 'v-html="html" → rich-text nodes="{{html}}"（容器标签映射为 rich-text）',
    why: '小程序无 innerHTML，富文本用 rich-text 组件（原生能力兜底，痛点 #11 对策）',
    when: '元素上有 v-html 指令时',
    example: { before: '<div v-html="html"></div>', after: '<rich-text nodes="{{html}}" />' },
    verify: 'tests/mp-transform.test.ts v-html 用例',
    source: 'src/compiler/template.ts → serializeElement（hasVHtml / html 分支）',
  },
  {
    id: 'directive/v-show',
    phase: 'template',
    status: 'implemented',
    title: 'v-show → hidden 属性',
    description: 'v-show="show" → hidden="{{!show}}"（小程序 hidden 属性 = display:none，元素始终渲染）',
    why: '小程序无 v-show 指令，hidden 属性语义对齐（display:none 切换）；元素保留在文档流中，与 v-if 的移除不同（v0.3 补齐，原为 MVP 限制）',
    when: '元素上有 v-show 指令时',
    example: { before: '<p v-show="show">a</p>', after: '<p hidden="{{!show}}">a</p>' },
    verify: 'tests/mp-transform.test.ts v-show 用例',
    source: 'packages/compiler/src/template.ts → serializeElement（show 分支）',
    decision: '#76（v0.3 指令补全）',
  },

  // ============ 导航链接 ============
  {
    id: 'nav/navigate-link',
    phase: 'template',
    status: 'implemented',
    title: '<a href> / <router-link to> → 导航链接',
    description: '带 href/to 的导航链接 → data-url + data-route-type + bindtap="proteusNavigateTo"（handler 由 script/nav-handler 注入）',
    why: 'Web 端 <a> 走浏览器导航，小程序端需转 data-url + 点击跳转（决策 #24）；保留前导 / 为绝对路径（#30 真机教训：无前导 / 会相对当前页目录解析导致双重前缀）',
    when: 'a 或 router-link 且无 @click、含 href/to（静态或 :bind）时',
    example: {
      before: '<a href="/pages/user/index">用户</a>',
      after: '<view class="proteus-a" data-url="/pages/user/index" bindtap="proteusNavigateTo">用户</view>',
    },
    verify: 'tests/mp-transform.test.ts 导航链接用例；真机验证归档决策 #30',
    source: 'src/compiler/template.ts → serializeElement（isNavLink / hasNavTarget 分支）',
    decision: '#24 / #30 / #29',
  },
  {
    id: 'nav/route-type',
    phase: 'template',
    status: 'implemented',
    title: '导航链接 route-type 属性 → data-route-type',
    description: '<a route-type="halfScreen"> → data-route-type="halfScreen"（proteusNavigateTo 透传为 wx.navigateTo 的 routeType）',
    why: 'Skyline 自定义路由转场从导航链接发起时，需把 routeType 传到运行期（决策 #44：routeType 双端同 API）',
    when: '导航链接元素上有 route-type 属性时',
    example: {
      before: '<a href="/pages/user/profile" route-type="halfScreen">资料</a>',
      after: '<view data-url="/pages/user/profile" data-route-type="halfScreen" bindtap="proteusNavigateTo">资料</view>',
    },
    verify: 'tests/mp-transform.test.ts 导航链接用例',
    source: 'src/compiler/template.ts → serializeElement（route-type 分支）',
    decision: '#28 / #44',
  },

  // ============ 通用节点 ============
  {
    id: 'node/interpolation',
    phase: 'template',
    status: 'implemented',
    title: '插值 {{ expr }} 保留',
    description: '{{ title }} → {{ title }}（表达式原样透传，文本节点紧凑单行输出）',
    why: '小程序插值语法同为 {{expr}}，无需转换；纯文本子节点紧凑单行保证产物可读（决策 #15）',
    when: '模板出现 {{ }} 插值或纯文本子节点时',
    example: { before: '<p>tapped {{ count }} times</p>', after: '<text class="proteus-p">tapped {{ count }} times</text>' },
    verify: 'golden fixture basic.wxml',
    source: 'src/compiler/template.ts → serializeNode（TEXT / INTERPOLATION 分支）',
    decision: '#15',
  },
  {
    id: 'annotation/line-note',
    phase: 'template',
    status: 'implemented',
    title: 'PROTEUS_DEBUG 源码行号注释',
    description: 'annotateLines=true 时 WXML 每个元素前注入 <!-- @行号 标签 -->，产物可反查源码位置',
    why: '反编译黑盒机制（#17）：默认关闭，npm run debug:mp 开启——AI/人拿到产物即可定位到源码行',
    when: '编译选项 annotateLines=true（PROTEUS_DEBUG=1 构建）时',
    example: { before: '第 26 行 <h1>{{ title }}</h1>', after: '<!-- @26 h1 -->\n<text class="proteus-h1">{{ title }}</text>' },
    verify: 'tests/mp-transform.test.ts annotateLines 用例；PROJECT_MEMORY #17',
    source: 'src/compiler/template.ts → serializeElement（lineNote 分支）',
    decision: '#17',
  },
  {
    id: 'template/scope-attr',
    phase: 'template',
    status: 'implemented',
    title: 'scoped CSS：元素附加作用域属性',
    description: '<style scoped> 存在时，模板元素附加 data-v-xxx 作用域属性（样式侧选择器 [data-v-xxx] 精确匹配）',
    why: '小程序无 scoped CSS 原生机制，编译期加属性 + 属性选择器等价（v0.3，决策 #77）',
    when: 'SFC 含 <style scoped>（compileVueSfc 生成 scopeId 并注入）时',
    example: { before: '<div class="card">…</div>', after: '<view data-v-abc123 class="card">…</view>' },
    verify: 'tests/mp-transform.test.ts scoped CSS 用例',
    source: 'packages/compiler/src/template.ts → serializeElement（scopeId 分支）',
    decision: '#77（v0.3 scoped CSS）',
  },
]

// 追踪键（防漂移）：标签 → 规则 ID，由 tag/* 规则的 mapping 反推——实现侧 trace 引用同一份数据
// 只取 tag/ 前缀规则：semantic/base-class（mapping 含 h1-p/a）与 event/click-to-tap（mapping 含 input/click）
// 的键是另一维度的映射，不得混入标签追踪（后定义覆盖会污染）。
// tests/explain.test.ts 校验所有 trace 事件 ruleId 均可解析
export const TAG_RULE_BY_TAG: Record<string, string> = Object.fromEntries(
  TEMPLATE_RULES.filter((r) => r.id.startsWith('tag/')).flatMap((r) =>
    r.mapping ? Object.keys(r.mapping).map((t): [string, string] => [t, r.id]) : [],
  ),
)
