// src/compiler/transforms/validate.ts
// validate 阶段编译规则注册表 —— 每条规则一份 AI 说明书（反黑盒机制核心）
import type { TransformRule } from './types'

export const VALIDATE_RULES: TransformRule[] = [
  {
    id: 'validate/js-syntax',
    phase: 'validate',
    status: 'implemented',
    title: 'JS 产物语法自校验',
    titleEn: 'JS output syntax self-check',
    description: 'new Function(js) 仅解析不执行，语法错误 → 校验失败并携带错误信息',
    descriptionEn: 'new Function(js) is parsed only and never executed; a syntax error → validation fails and carries the error message',
    why: '反编译黑盒机制（决策 #17）：坏产物当场报错指明文件，绝不静默输出不可用的产物（对比 uni-app 产物无法定位问题）',
    whyEn: 'Anti-black-box mechanism (decision #17): broken output errors out on the spot and names the file; it never silently emits unusable output (unlike uni-app, whose artifacts make problems impossible to locate)',
    when: '每次整包编译后（assertValidResult 内）',
    example: {
      before: '// 若产物 js 含语法错误',
      after: 'CompilerError: [proteus-compiler] xxx.vue: js 产物语法错误：Unexpected token ...',
    },
    verify: 'tests/mp-transform.test.ts 校验用例（构造坏产物断言抛错）',
    source: 'src/compiler/validate.ts → validateJs',
    decision: '#17',
  },
  {
    id: 'validate/js-platform-es5',
    phase: 'validate',
    status: 'implemented',
    title: 'JS 产物按平台标准校验（微信 = ES5）',
    titleEn: 'JS output checked against the target platform standard (WeChat = ES5)',
    description: '扫描产物残留的 ES2020 语法（?? ?. ??= ||= &&=，跳过字符串/模板/注释）→ 校验失败并报行号；校验器按平台标准而非宿主 Node 标准（new Function 认识 ES2020，?? / ?. 语法过但微信开发者工具 babel 不解析）',
    descriptionEn: 'Scans the output for leftover ES2020 syntax (?? ?. ??= ||= &&=, skipping strings/templates/comments) → validation fails and reports the line; the validator follows the target platform standard rather than the host Node standard (new Function accepts ES2020, so ?? / ?. pass syntax checks even though WeChat DevTools babel does not parse them)',
    why: '决策 #504 用户点名盲区：node --check / new Function 认识 ES2020 → ?? 产物语法校验永远通过，微信预览上传期才 SyntaxError；把 ES5 tripwire 从外部门禁脚本内建进 compileVueSfc 自校验链，兜底 es5.ts babel 转译失败路径（error 时返回原样代码）',
    whyEn: 'Decision #504 user-flagged blind spot: node --check / new Function accept ES2020, so ?? output always passes syntax checks and only fails as a SyntaxError at WeChat preview/upload time; the ES5 tripwire moves from the external gate script into the compileVueSfc self-check chain, backstopping the es5.ts babel failure path (which returns code unchanged on error)',
    when: '每次整包编译后（assertValidResult 内，validateJs 之后）',
    example: {
      before: '// 产物 js 含 p?.source ?? "?"（babel 失败路径残留）',
      after: 'CompilerError: [proteus-compiler] xxx.vue: 平台 JS 标准违规：ES2020 语法「??」残留于第 N 行第 M 列',
    },
    verify: 'tests/compiler-validate-platform.test.ts',
    source: 'src/compiler/validate.ts → validateMpJsPlatform + scanMpUnsafeEs5',
    decision: '#504/#505',
  },
  {
    id: 'validate/wxml-platform',
    phase: 'validate',
    status: 'implemented',
    title: 'WXML 产物按平台标准校验（蓝本 glass-easel 官方错误码）',
    titleEn: 'WXML output checked against the platform standard (glass-easel official error codes as blueprint)',
    description: '三项官方错误码检查：①DataBindingNotAllowed——wx:key 值含 {{}}（官方 wx:key 禁用数据绑定，直接指定 item 字段名或 *this）；②DuplicatedAttribute——同名属性重复（微信仅保留其一）；③AvoidUppercaseLetters——标签名含大写（产物自定义组件标签应 kebab-case 全小写；属性名大写豁免——camelCase 自定义属性如 modelValue 是合法绑定，官方亦为 Note 级）',
    descriptionEn: 'three official-error-code checks: ① DataBindingNotAllowed — wx:key contains {{}} (official: wx:key forbids data binding; specify the item field name or *this directly); ② DuplicatedAttribute — the same attribute appears twice (WeChat keeps only one); ③ AvoidUppercaseLetters — a tag name contains uppercase (custom-component tags in output should be all-lowercase kebab-case; uppercase attribute names are exempt — camelCase custom attributes like modelValue are legal bindings, and the official level is Note)',
    why: '★#505 G2 平台语义对齐：自造 IR 语义会错（wx:key 曾把 :key="t.id" 整句丢弃）——平台标准 = glass-easel 官方 parser 错误码（docs/compiler-platform-alignment.md §1.3）；产物正常形态永不命中，命中即编译器 bug（呼应「校验器按平台标准而非宿主标准」收紧）',
    whyEn: '★#505 G2 platform-semantic alignment: inventing IR semantics by ourselves goes wrong (wx:key used to drop :key="t.id" entirely) — the platform standard is the glass-easel official parser error codes (docs/compiler-platform-alignment.md §1.3); normal output never hits these, so any hit is a compiler bug (echoing the tightening: validators follow platform standards, not host standards)',
    when: '每次整包编译后（assertValidResult 内，validateWxml 之后）',
    example: { before: '// 产物含 wx:key="{{x}}" / class 双属性 / <PModal>', after: 'CompilerError: [proteus-compiler] xxx.vue: wxml 产物平台标准违规：[DataBindingNotAllowed] …' },
    verify: 'tests/compiler-validate-platform.test.ts（wxml 平台三检查）',
    source: 'src/compiler/validate.ts → validateWxmlPlatform + scanWxmlPlatformIssues',
    decision: '#505 G2 / docs/compiler-platform-alignment.md',
  },
  {
    id: 'validate/wxml-pairing',
    phase: 'validate',
    status: 'implemented',
    title: 'WXML 标签配对自校验',
    titleEn: 'WXML tag pairing self-check',
    description: '栈式扫描 WXML 标签配对（先剥离注释，避免行号注释干扰），未闭合/错配 → 校验失败',
    descriptionEn: 'Stack-based scan of WXML tag pairing (comments are stripped first to keep line-number comments from interfering); unclosed/mismatched tags → validation fails',
    why: '反编译黑盒机制（决策 #17）：模板转换出错的常见形态就是标签不配对，编译期拦截比真机报错好定位',
    whyEn: 'Anti-black-box mechanism (decision #17): a common way template conversion breaks is unpaired tags; catching it at compile time is easier to locate than a real-device runtime error',
    when: '每次整包编译后（assertValidResult 内）',
    example: {
      before: '// 若产物 wxml 标签不配对',
      after: 'CompilerError: [proteus-compiler] xxx.vue: wxml 产物结构错误：</view> 与 <text> 不匹配（位置 N）',
    },
    verify: 'tests/mp-transform.test.ts 校验用例',
    source: 'src/compiler/validate.ts → validateWxml',
    decision: '#17',
  },
  {
    id: 'validate/compiler-error',
    phase: 'validate',
    status: 'implemented',
    title: '坏产物抛 CompilerError 指明文件',
    titleEn: 'Broken output throws CompilerError naming the file',
    description: '校验失败 → 抛 CompilerError（携带源文件名，消息含 [proteus-compiler] 前缀）',
    descriptionEn: 'Validation failure → throws CompilerError (carrying the source file name; the message includes the [proteus-compiler] prefix)',
    why: '反黑盒机制的统一错误通道：AI/开发者拿到错误即可定位到具体文件（错误 = 可操作的反馈，而非黑盒失败）',
    whyEn: 'Anti-black-box unified error channel: once AI/developers receive the error they can locate the exact file (error = actionable feedback, not a black-box failure)',
    when: 'js 或 wxml 校验不通过时',
    example: {
      before: '// 静默输出坏产物（反模式）',
      after: 'throw new CompilerError(filename, message)',
    },
    verify: 'tests/mp-transform.test.ts 校验用例',
    source: 'src/compiler/validate.ts → CompilerError + assertValidResult',
    decision: '#17',
  },
]
