// router/auto-routes.ts —— 应用侧路由表（AUTO-GENERATED by scripts/gen-routes.ts，勿手动编辑）
// ★拆包步骤 4：auto-routes 随应用存放（工厂化后路由表由应用注入 createRouter），不再属于 @proteus-vue/router 包
import type { RouteRecord } from '@proteus-vue/router/types'

export const routes: RouteRecord[] = [
  { name: "about", path: "pages/about", component: "../pages/about.vue", parent: "index", meta: {"title":"关于 Proteus"} },
  { name: "backends", path: "pages/backends", component: "../pages/backends.vue", parent: "index", meta: {"title":"多渲染后端"} },
  { name: "capabilities", path: "pages/capabilities", component: "../pages/capabilities.vue", parent: "index", meta: {"title":"原生能力","isTab":true} },
  { name: "components", path: "pages/components", component: "../pages/components.vue", parent: "index", meta: {"title":"组件库","isTab":true} },
  { name: "engineering-i18n", path: "pages/engineering-i18n", component: "../pages/engineering-i18n.vue", parent: "index", meta: {"title":"国际化"} },
  { name: "engineering-router", path: "pages/engineering-router", component: "../pages/engineering-router.vue", parent: "index", meta: {"title":"路由"} },
  { name: "engineering-state", path: "pages/engineering-state", component: "../pages/engineering-state.vue", parent: "index", meta: {"title":"状态管理"} },
  { name: "index", path: "pages/index", component: "../pages/index.vue", meta: {"title":"首页","isTab":true} },
  { name: "mine", path: "pages/mine", component: "../pages/mine.vue", parent: "index", meta: {"title":"我的","isTab":true} },
  { name: "playground", path: "pages/playground", component: "../pages/playground.vue", parent: "index", meta: {"title":"在线编译"} },
  { name: "semantics", path: "pages/semantics", component: "../pages/semantics.vue", parent: "index", meta: {"title":"语义与编译","isTab":true} },
  { name: "system-fluid", path: "pages/system-fluid", component: "../pages/system-fluid.vue", parent: "index", meta: {"title":"柔性布局"} },
  { name: "system-glass", path: "pages/system-glass", component: "../pages/system-glass.vue", parent: "index", meta: {"title":"液态玻璃"} },
  { name: "system-safe", path: "pages/system-safe", component: "../pages/system-safe.vue", parent: "index", meta: {"title":"安全区与自适应"} },
  { name: "transitions", path: "pages/transitions", component: "../pages/transitions.vue", parent: "index", meta: {"title":"转场动效"} },
  { name: "components-pages-p-button", path: "subpackages/components/pages/p-button", component: "../subpackages/components/pages/p-button.vue", subPackage: "components", meta: {"title":"p-button 按钮"} },
  { name: "components-pages-p-input", path: "subpackages/components/pages/p-input", component: "../subpackages/components/pages/p-input.vue", subPackage: "components", meta: {"title":"p-input 输入框"} },
  { name: "capabilities-pages-camera", path: "subpackages/capabilities/pages/camera", component: "../subpackages/capabilities/pages/camera.vue", subPackage: "capabilities", meta: {"title":"useCamera 相机"} },
]

export const tabRoutes: RouteRecord[] = routes.filter(r => r.meta?.isTab)
export const routeMap: Record<string, RouteRecord> = routes.reduce((m, r) => { m[r.name] = r; return m }, {} as Record<string, RouteRecord>)

// ★ 类型提示：按路由名索引的参数类型表（来源：<route> 块 params 声明）
declare module '@proteus-vue/router/types' {
  interface RouteParamsByName {
    'about': {  },
    'backends': {  },
    'capabilities': {  },
    'components': {  },
    'engineering-i18n': {  },
    'engineering-router': {  },
    'engineering-state': {  },
    'index': {  },
    'mine': {  },
    'playground': {  },
    'semantics': {  },
    'system-fluid': {  },
    'system-glass': {  },
    'system-safe': {  },
    'transitions': {  },
    'components-pages-p-button': {  },
    'components-pages-p-input': {  },
    'capabilities-pages-camera': {  },
  }
}